package main

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// generateGo renders the plan as one Go file per kind plus support.go, keyed by
// file name. Nothing is written here: main.go compares and writes, so
// `kinds:gen:check` can render into a temporary directory through the same
// code path that writes the checked-in output.
func generateGo(p *plan, source string) (map[string][]byte, error) {
	out := map[string][]byte{}
	files := map[string]*bytes.Buffer{"support.go": bytes.NewBufferString(supportBody)}
	for _, k := range p.Kinds {
		buf := &bytes.Buffer{}
		emitKind(buf, k)
		files[k.Decl.Name+".go"] = buf
	}
	for name, body := range files {
		var head bytes.Buffer
		fmt.Fprintf(&head, "// Code generated by cmd/kindsgen from %s. DO NOT EDIT.\n", source)
		fmt.Fprintf(&head, "// `mise run kinds:gen` rewrites this file; an edit here is lost.\n\n")
		if name == "support.go" {
			head.WriteString(packageDoc)
		}
		head.WriteString("package corekinds\n\n")
		if imports := goImports(body.String()); imports != "" {
			head.WriteString(imports)
		}
		head.Write(body.Bytes())
		formatted, err := format.Source(head.Bytes())
		if err != nil {
			return nil, fmt.Errorf("%s: generated Go does not parse: %w", name, err)
		}
		out[name] = formatted
	}
	return out, nil
}

// goImports is the import block a rendered body needs, decided by what the body
// actually says. A generated file that imported `time` for a kind with no
// datetime would not compile, and listing imports per emitter would drift from
// what the emitters emit.
func goImports(body string) string {
	candidates := []struct{ path, token string }{
		{"encoding/json", "json."},
		{"fmt", "fmt."},
		{"math", "math."},
		{"math/big", "big."},
		{"regexp", "regexp."},
		{"sort", "sort."},
		{"strconv", "strconv."},
		{"strings", "strings."},
		{"time", "time."},
	}
	var used []string
	for _, c := range candidates {
		if strings.Contains(body, c.token) {
			used = append(used, c.path)
		}
	}
	if len(used) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("import (\n")
	for _, path := range used {
		fmt.Fprintf(&b, "\t%q\n", path)
	}
	b.WriteString(")\n\n")
	return b.String()
}

func emitKind(b *bytes.Buffer, k *kindPlan) {
	for i, s := range k.Structs {
		if i > 0 {
			b.WriteString("\n")
		}
		emitStruct(b, s)
		for _, e := range s.Enums {
			emitEnum(b, e)
		}
		var states []*statePlan
		if s.Root {
			states = k.States
			for _, st := range states {
				emitState(b, st)
			}
			emitKeys(b, k)
			emitDecodeEntry(b, k)
		}
		emitRequired(b, s)
		emitEnumDecoders(b, s, states)
		emitDecode(b, s)
		emitProperties(b, s)
		emitTimeAccessors(b, s)
	}
}

func emitStruct(b *bytes.Buffer, s *structPlan) {
	doc := s.Name + " is " + s.Owner + " as its declaration admits it."
	if !s.Root {
		doc = s.Name + " is one value of the `" + s.Path + "` object declared on " + s.Owner + "."
	}
	if s.Doc != "" {
		doc += "\n\n" + s.Doc
	}
	comment(b, doc)
	fmt.Fprintf(b, "type %s struct {\n", s.Name)
	for i, f := range s.Fields {
		if i > 0 {
			b.WriteString("\n")
		}
		if fd := fieldDoc(f); fd != "" {
			indentedComment(b, fd)
		}
		fmt.Fprintf(b, "\t%s %s\n", f.Name, goType(f))
	}
	b.WriteString("}\n\n")
}

// fieldDoc is the declared description plus the contract markers a caller has
// to know before it writes the property.
func fieldDoc(f *fieldPlan) string {
	var parts []string
	if f.Decl.Description != "" {
		// The declared description is quoted, not re-cased: it is written as the
		// tail of a sentence ("the content hash"), which is exactly where it lands.
		parts = append(parts, f.Decl.Description+".")
	}
	if f.Class == classState {
		parts = append(parts, "A state is NOT stored in properties: it lives in the record's own state column and moves by transition. See "+f.State.Name+".")
	}
	if f.Decl.Implicit {
		parts = append(parts, "declared by a transition's stamp rather than by the properties block: the engine writes it when the move it stamps is performed.")
	}
	if f.Decl.Managed {
		parts = append(parts, "Managed: the engine stamps it, so a write that supplies one is refused.")
	}
	if f.Decl.Writer != "" {
		parts = append(parts, "Writer: only the "+f.Decl.Writer+" actor may write it.")
	}
	if f.Decl.RefersTo != "" {
		parts = append(parts, "Names a "+f.Decl.RefersTo+" in the registry.")
	}
	if f.Class == classReference && f.Decl.To != "" {
		parts = append(parts, "Points at "+f.Decl.To+".")
	}
	if f.keyed() && f.Decl.KeyPattern != "" {
		parts = append(parts, "Its keys hold to the "+f.Decl.KeyPattern+" contract.")
	}
	if len(parts) == 0 {
		return ""
	}
	return f.Name + " is " + strings.Join(parts, " ")
}

// goType is the field's declared container around its element type. An optional
// single value is a POINTER: absence stored is absence authored, and a
// materialized zero would be a value the author never wrote.
func goType(f *fieldPlan) string {
	switch {
	case f.repeated():
		return "[]" + f.GoElem
	case f.keyed():
		return "map[string]" + f.GoElem
	case f.pointer():
		return "*" + f.GoElem
	}
	return f.GoElem
}

func emitEnum(b *bytes.Buffer, e *enumPlan) {
	doc := e.Name + " is a declared enum: the admissible set, in declaration order."
	if e.Doc != "" {
		doc += "\n\n" + e.Doc
	}
	comment(b, doc)
	fmt.Fprintf(b, "type %s string\n\n", e.Name)
	b.WriteString("const (\n")
	for _, v := range e.Values {
		fmt.Fprintf(b, "\t%s%s %s = %q\n", e.Name, identifier(v.Value), e.Name, v.Value)
	}
	b.WriteString(")\n\n")
	comment(b, e.Name+"Values are the declared values in declaration order, which is render order.")
	fmt.Fprintf(b, "var %sValues = []string{%s}\n\n", e.Name, quoted(e.values()))
	if labels := e.labels(); len(labels) > 0 {
		comment(b, e.Name+"Labels are the declared human labels by value: a client renders the label and submits the value. A value with no declared label is absent, and the client humanizes it.")
		fmt.Fprintf(b, "var %sLabels = map[string]string{\n", e.Name)
		for _, v := range labels {
			fmt.Fprintf(b, "\t%q: %q,\n", v.Value, v.Label)
		}
		b.WriteString("}\n\n")
	}
	fmt.Fprintf(b, "// Valid reports whether v is one of the declared values.\n")
	fmt.Fprintf(b, "func (v %s) Valid() bool { return Declared(%sValues, string(v)) }\n\n", e.Name, e.Name)
}

func emitState(b *bytes.Buffer, s *statePlan) {
	doc := s.Name + " is the state of the `" + s.Property + "` machine.\n\n" +
		"A STATE IS NOT A PROPERTY VALUE: it lives in the record's own state column and moves by transition, never by assignment. The declared states, the initial one and the legal moves are the constants and tables here; the field on the properties struct carries what a read reported, which is why Decode admits the key and Properties writes it back."
	if s.Doc != "" {
		doc += "\n\n" + s.Doc
	}
	comment(b, doc)
	fmt.Fprintf(b, "type %s string\n\n", s.Name)
	b.WriteString("const (\n")
	for _, v := range s.Machine.States {
		fmt.Fprintf(b, "\t%s%s %s = %q\n", s.Name, identifier(v), s.Name, v)
	}
	b.WriteString(")\n\n")
	comment(b, s.Name+"Values are the declared states in declaration order.")
	fmt.Fprintf(b, "var %sValues = []string{%s}\n\n", s.Name, quoted(s.Machine.States))
	fmt.Fprintf(b, "// %sInitial is the state a creation is born into.\n", s.Name)
	fmt.Fprintf(b, "const %sInitial = %s%s\n\n", s.Name, s.Name, identifier(s.Machine.Initial))
	comment(b, s.Name+"Transitions are the declared moves, in declaration order. A move absent from this table is not performable: nothing else gates one, since a transition carries no guard.")
	fmt.Fprintf(b, "var %sTransitions = []StateTransition{\n", s.Name)
	for _, t := range s.Machine.Transitions {
		fmt.Fprintf(b, "\t{From: %q, To: %q", t.From, t.To)
		if len(t.Stamps) > 0 {
			b.WriteString(", Stamps: map[string]string{")
			for i, st := range t.Stamps {
				if i > 0 {
					b.WriteString(", ")
				}
				fmt.Fprintf(b, "%q: %q", st.Property, st.Value)
			}
			b.WriteString("}")
		}
		if t.OnEnter != "" {
			fmt.Fprintf(b, ", OnEnter: %q", t.OnEnter)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(b, "// Valid reports whether v is one of the declared states.\n")
	fmt.Fprintf(b, "func (v %s) Valid() bool { return Declared(%sValues, string(v)) }\n\n", s.Name, s.Name)
	comment(b, s.Name+"CanMove reports whether from -> to is a declared move of the `"+s.Property+"` machine.")
	fmt.Fprintf(b, "func %sCanMove(from, to %s) bool {\n", s.Name, s.Name)
	fmt.Fprintf(b, "\tfor _, t := range %sTransitions {\n", s.Name)
	b.WriteString("\t\tif t.From == string(from) && t.To == string(to) {\n\t\t\treturn true\n\t\t}\n\t}\n\treturn false\n}\n\n")
}

func emitKeys(b *bytes.Buffer, k *kindPlan) {
	comment(b, k.Name+"Keys is the admitted key set: every property "+k.Decl.Ref+" declares, sorted. A key outside it is refused by Decode, which is what replaces a hand-kept list of admitted keys in Go.")
	fmt.Fprintf(b, "var %sKeys = []string{%s}\n\n", k.Name, quoted(k.keySet()))
}

func emitDecodeEntry(b *bytes.Buffer, k *kindPlan) {
	comment(b, "Decode"+k.Name+" decodes a properties map into "+k.Name+", refusing what the declaration cannot hold: an undeclared key, a value of the wrong type, an enum or state outside its set, a number outside its declared range or beyond exact integer precision, a key breaking a keyed map's contract. The value is nil unless the problems are empty, so a half-decoded record can never reach a caller.\n\nIt reads a STORED shape and is not the write-admission gate: see the boundary in support.go. An ABSENT required property is admitted, because the write path admits one too — "+k.Name+"Required and Missing are where requiredness lives.")
	fmt.Fprintf(b, "func Decode%s(props map[string]any) (*%s, []Problem) {\n", k.Name, k.Name)
	b.WriteString("\td := &decoder{}\n")
	fmt.Fprintf(b, "\tout, _ := decode%s(d, \"\", props)\n", k.Name)
	b.WriteString("\tif len(d.problems) > 0 {\n\t\treturn nil, d.problems\n\t}\n\treturn &out, nil\n}\n\n")
}

func emitDecode(b *bytes.Buffer, s *structPlan) {
	fmt.Fprintf(b, "// decode%s decodes one %s value at path.\n", s.Name, s.Name)
	fmt.Fprintf(b, "func decode%s(d *decoder, path string, v any) (%s, bool) {\n", s.Name, s.Name)
	b.WriteString("\tprops, mapped := d.mapping(path, v)\n")
	fmt.Fprintf(b, "\tif !mapped {\n\t\treturn %s{}, false\n\t}\n", s.Name)
	fmt.Fprintf(b, "\tvar out %s\n", s.Name)
	b.WriteString("\tfor _, key := range sortedKeys(props) {\n")
	b.WriteString("\t\t// A null is this dialect's delete marker, never a value: it decodes as\n")
	b.WriteString("\t\t// absence, and Properties never writes one.\n")
	b.WriteString("\t\tif props[key] == nil {\n\t\t\tcontinue\n\t\t}\n")
	b.WriteString("\t\tswitch key {\n")
	for _, f := range s.Fields {
		fmt.Fprintf(b, "\t\tcase %q:\n", f.Key)
		emitFieldDecode(b, f)
	}
	b.WriteString("\t\tdefault:\n")
	fmt.Fprintf(b, "\t\t\td.unknown(at(path, key), %q)\n", s.Owner)
	b.WriteString("\t\t}\n\t}\n")
	b.WriteString("\treturn out, true\n}\n\n")
}

// emitRequired writes the declared `required:` set and the check that reads it.
// The DECODER does not: the write path admits a row without a required property
// (vocabulary Property.Required), so refusing one here would refuse stored rows
// the substrate itself wrote. Requiredness stays a form's question, answerable
// without reflection.
func emitRequired(b *bytes.Buffer, s *structPlan) {
	var required []string
	for _, f := range s.Fields {
		if f.Required {
			required = append(required, f.Key)
		}
	}
	if len(required) == 0 {
		return
	}
	sort.Strings(required)
	comment(b, s.Name+"Required names the properties the declaration marks `required:`, sorted. It is a FORM-LEVEL contract: the write path does not enforce it, so Decode admits a value that leaves one absent and this is what a client checks before it submits one.")
	fmt.Fprintf(b, "var %sRequired = []string{%s}\n\n", s.Name, quoted(required))
	comment(b, "Missing names the required properties this value leaves absent, in declaration order. Empty means every declared requirement is answered — not that the value is admissible, which is the substrate's answer and not a type's.")
	fmt.Fprintf(b, "func (v *%s) Missing() []string {\n\tvar out []string\n", s.Name)
	for _, f := range s.Fields {
		if !f.Required {
			continue
		}
		fmt.Fprintf(b, "\tif v.%s == nil {\n\t\tout = append(out, %q)\n\t}\n", f.Name, f.Key)
	}
	b.WriteString("\treturn out\n}\n\n")
}

// emitFieldDecode writes one case body: the declared container around the one
// expression that decodes an element.
func emitFieldDecode(b *bytes.Buffer, f *fieldPlan) {
	fmt.Fprintf(b, "\t\t\tp := at(path, %q)\n", f.Key)
	switch {
	case f.repeated():
		b.WriteString("\t\t\tif items, listed := d.list(p, props[key]); listed {\n")
		fmt.Fprintf(b, "\t\t\t\tlist := make([]%s, 0, len(items))\n", f.GoElem)
		b.WriteString("\t\t\t\tfor i, item := range items {\n")
		fmt.Fprintf(b, "\t\t\t\t\tif e, ok := %s; ok {\n", elemDecode(f, "index(p, i)", "item"))
		b.WriteString("\t\t\t\t\t\tlist = append(list, e)\n\t\t\t\t\t}\n\t\t\t\t}\n")
		fmt.Fprintf(b, "\t\t\t\tout.%s = list\n\t\t\t}\n", f.Name)
	case f.keyed():
		b.WriteString("\t\t\tif entries, isMap := d.mapping(p, props[key]); isMap {\n")
		fmt.Fprintf(b, "\t\t\t\tvalues := make(map[string]%s, len(entries))\n", f.GoElem)
		b.WriteString("\t\t\t\tfor _, mk := range sortedKeys(entries) {\n")
		fmt.Fprintf(b, "\t\t\t\t\tif entries[mk] == nil || !d.key(p, mk, %q) {\n\t\t\t\t\t\tcontinue\n\t\t\t\t\t}\n", f.Decl.KeyPattern)
		fmt.Fprintf(b, "\t\t\t\t\tif e, ok := %s; ok {\n", elemDecode(f, "at(p, mk)", "entries[mk]"))
		b.WriteString("\t\t\t\t\t\tvalues[mk] = e\n\t\t\t\t\t}\n\t\t\t\t}\n")
		fmt.Fprintf(b, "\t\t\t\tout.%s = values\n\t\t\t}\n", f.Name)
	default:
		fmt.Fprintf(b, "\t\t\tif e, ok := %s; ok {\n", elemDecode(f, "p", "props[key]"))
		if f.pointer() {
			fmt.Fprintf(b, "\t\t\t\tout.%s = &e\n\t\t\t}\n", f.Name)
		} else {
			fmt.Fprintf(b, "\t\t\t\tout.%s = e\n\t\t\t}\n", f.Name)
		}
	}
}

// elemDecode is the one expression that decodes an element of the field's
// declared datatype, returning (element, ok).
func elemDecode(f *fieldPlan, path, value string) string {
	switch f.Class {
	case classText:
		return fmt.Sprintf("d.text(%s, %s, %s, %s)", path, value, valueSet(f), patternRef(f))
	case classEnum:
		return fmt.Sprintf("decode%s(d, %s, %s)", f.Enum.Name, path, value)
	case classState:
		return fmt.Sprintf("decode%s(d, %s, %s)", f.State.Name, path, value)
	case classDatetime:
		return fmt.Sprintf("d.instant(%s, %s)", path, value)
	case classInt:
		return fmt.Sprintf("d.integer(%s, %s, %s)", path, value, bounds(f))
	case classFloat:
		return fmt.Sprintf("d.number(%s, %s, %s)", path, value, bounds(f))
	case classBool:
		return fmt.Sprintf("d.flag(%s, %s)", path, value)
	case classSecret:
		return fmt.Sprintf("d.secret(%s, %s)", path, value)
	case classDigest:
		return fmt.Sprintf("d.digest(%s, %s)", path, value)
	case classBlobRef:
		return fmt.Sprintf("d.blob(%s, %s)", path, value)
	case classJSON:
		return fmt.Sprintf("d.dynamic(%s, %s)", path, value)
	case classReference:
		return fmt.Sprintf("d.reference(%s, %s, %q)", path, value, f.Decl.To)
	case classObject:
		return fmt.Sprintf("decode%s(d, %s, %s)", f.Nested.Name, path, value)
	}
	panic("unreachable: every class decodes")
}

// valueSet is the declared value set a non-enum string property may carry (a
// state's declared list reads the same way), or nil.
func valueSet(f *fieldPlan) string {
	if len(f.Decl.Values) == 0 {
		return "nil"
	}
	out := make([]string, 0, len(f.Decl.Values))
	for _, v := range f.Decl.Values {
		out = append(out, v.Value)
	}
	return "[]string{" + quoted(out) + "}"
}

func patternRef(f *fieldPlan) string {
	if f.Decl.Pattern == "" {
		return "nil"
	}
	return fmt.Sprintf("regexp.MustCompile(%q)", f.Decl.Pattern)
}

func bounds(f *fieldPlan) string {
	var parts []string
	if f.Decl.Min != nil {
		parts = append(parts, "Min: bound("+formatFloat(*f.Decl.Min)+")")
	}
	if f.Decl.Max != nil {
		parts = append(parts, "Max: bound("+formatFloat(*f.Decl.Max)+")")
	}
	return "Bounds{" + strings.Join(parts, ", ") + "}"
}

func formatFloat(f float64) string { return strconv.FormatFloat(f, 'g', -1, 64) }

// emitDecode's enum and state elements go through one generated function each,
// so every element decode is a single expression and the container code above
// stays one shape.
func emitEnumDecoders(b *bytes.Buffer, s *structPlan, states []*statePlan) {
	for _, e := range s.Enums {
		fmt.Fprintf(b, "// decode%s decodes a declared %s value.\n", e.Name, e.Name)
		fmt.Fprintf(b, "func decode%s(d *decoder, path string, v any) (%s, bool) {\n", e.Name, e.Name)
		fmt.Fprintf(b, "\ts, ok := d.text(path, v, %sValues, nil)\n", e.Name)
		fmt.Fprintf(b, "\tif !ok {\n\t\treturn \"\", false\n\t}\n\treturn %s(s), true\n}\n\n", e.Name)
	}
	for _, st := range states {
		fmt.Fprintf(b, "// decode%s decodes a declared state of the `%s` machine.\n", st.Name, st.Property)
		fmt.Fprintf(b, "func decode%s(d *decoder, path string, v any) (%s, bool) {\n", st.Name, st.Name)
		fmt.Fprintf(b, "\ts, ok := d.text(path, v, %sValues, nil)\n", st.Name)
		fmt.Fprintf(b, "\tif !ok {\n\t\treturn \"\", false\n\t}\n\treturn %s(s), true\n}\n\n", st.Name)
	}
}

func emitProperties(b *bytes.Buffer, s *structPlan) {
	decoder := "decode" + s.Name
	if s.Root {
		decoder = "Decode" + s.Name
	}
	comment(b, "Properties is "+s.Name+" as the properties map holds it, and "+decoder+"'s exact inverse: a nil pointer, a nil slice and a nil map each omit their key, so absence survives the round trip.")
	fmt.Fprintf(b, "func (v *%s) Properties() map[string]any {\n", s.Name)
	b.WriteString("\tout := map[string]any{}\n")
	for _, f := range s.Fields {
		emitFieldEncode(b, f)
	}
	b.WriteString("\treturn out\n}\n\n")
}

func emitFieldEncode(b *bytes.Buffer, f *fieldPlan) {
	access := "v." + f.Name
	switch {
	case f.repeated():
		fmt.Fprintf(b, "\tif %s != nil {\n", access)
		fmt.Fprintf(b, "\t\titems := make([]any, 0, len(%s))\n", access)
		fmt.Fprintf(b, "\t\tfor i := range %s {\n", access)
		fmt.Fprintf(b, "\t\t\titems = append(items, %s)\n", encodeExpr(f, access+"[i]"))
		b.WriteString("\t\t}\n")
		fmt.Fprintf(b, "\t\tout[%q] = items\n\t}\n", f.Key)
	case f.keyed():
		fmt.Fprintf(b, "\tif %s != nil {\n", access)
		fmt.Fprintf(b, "\t\tvalues := make(map[string]any, len(%s))\n", access)
		fmt.Fprintf(b, "\t\tfor key, item := range %s {\n", access)
		fmt.Fprintf(b, "\t\t\tvalues[key] = %s\n", encodeExpr(f, "item"))
		b.WriteString("\t\t}\n")
		fmt.Fprintf(b, "\t\tout[%q] = values\n\t}\n", f.Key)
	case f.Class == classJSON:
		// Dynamic carries its own absence: nil IS an absent json property, and
		// there is no pointer to distinguish.
		fmt.Fprintf(b, "\tif %s != nil {\n\t\tout[%q] = %s\n\t}\n", access, f.Key, access)
	case f.pointer():
		fmt.Fprintf(b, "\tif %s != nil {\n\t\tout[%q] = %s\n\t}\n", access, f.Key, encodeExpr(f, "*"+access))
	default:
		fmt.Fprintf(b, "\tout[%q] = %s\n", f.Key, encodeExpr(f, access))
	}
}

// encodeExpr is the element as the properties map holds it: a plain Go string,
// number or bool, an object's own map, never a named type. The map is the wire,
// and a named string in it would decode as the wrong type on the way back.
func encodeExpr(f *fieldPlan, access string) string {
	switch f.Class {
	case classEnum, classState, classSecret, classDigest, classBlobRef:
		return "string(" + access + ")"
	case classReference, classObject:
		if strings.HasPrefix(access, "*") {
			return strings.TrimPrefix(access, "*") + ".Properties()"
		}
		return access + ".Properties()"
	}
	return access
}

func emitTimeAccessors(b *bytes.Buffer, s *structPlan) {
	for _, f := range s.Fields {
		if f.Class != classDatetime || f.repeated() || f.keyed() {
			continue
		}
		comment(b, f.Name+"Time is "+f.Name+" parsed. The stored form is the string, so this is a reading of it and never a second source of truth; an absent value reads as the zero time with no error, because absence is not a malformed instant.")
		fmt.Fprintf(b, "func (v *%s) %sTime() (time.Time, error) {\n", s.Name, f.Name)
		if f.pointer() {
			fmt.Fprintf(b, "\tif v.%s == nil {\n\t\treturn time.Time{}, nil\n\t}\n", f.Name)
			fmt.Fprintf(b, "\treturn time.Parse(time.RFC3339, *v.%s)\n}\n\n", f.Name)
			continue
		}
		fmt.Fprintf(b, "\treturn time.Parse(time.RFC3339, v.%s)\n}\n\n", f.Name)
	}
}

// --- comment and literal helpers ---

const commentWidth = 76

func comment(b *bytes.Buffer, text string) { writeComment(b, text, "") }

func indentedComment(b *bytes.Buffer, text string) { writeComment(b, text, "\t") }

// writeComment wraps a doc comment at commentWidth, keeping blank lines: a
// generated comment is read by the same people who read a hand-written one.
func writeComment(b *bytes.Buffer, text, indent string) {
	for i, para := range strings.Split(text, "\n\n") {
		if i > 0 {
			fmt.Fprintf(b, "%s//\n", indent)
		}
		for _, line := range wrap(para, commentWidth-len(indent)*4) {
			fmt.Fprintf(b, "%s// %s\n", indent, line)
		}
	}
}

func wrap(text string, width int) []string {
	words := strings.Fields(text)
	if len(words) == 0 {
		return nil
	}
	var lines []string
	line := words[0]
	for _, w := range words[1:] {
		if len(line)+1+len(w) > width {
			lines = append(lines, line)
			line = w
			continue
		}
		line += " " + w
	}
	return append(lines, line)
}

func quoted(values []string) string {
	out := make([]string, 0, len(values))
	for _, v := range values {
		out = append(out, strconv.Quote(v))
	}
	return strings.Join(out, ", ")
}

func upperFirstRune(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// sortedNames is the generator's own determinism: a map iterated for output is
// a diff that changes without a declaration changing.
func sortedNames[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
