package main

// packageDoc heads support.go. It is the one place the generated package
// explains its own rules, so the per-kind files can stay declarations.
const packageDoc = `// Package corekinds is the core vocabulary as Go types: one struct per kind
// declared under kinds/core.substrate.reamde.dev, generated by cmd/kindsgen.
// The declarations are the source of truth and this package is their shadow —
// mise run kinds:gen rewrites it, and CI refuses a tree where the two disagree.
//
// Three rules are worth knowing before reading a type.
//
// THE MAP IS THE WIRE. Decode<Kind> and (*Kind).Properties are each other's
// exact inverse over map[string]any, which is the form the API, the changelog
// and jsonb all carry. There are no struct tags: a second encoder would be a
// second answer about what a property is called.
//
// EVERY SINGLE VALUE IS A POINTER. Absence stored is absence authored, and a
// materialized zero value is the likeliest silent round-trip bug — an empty
// string written where the author wrote nothing. A REQUIRED property is a
// pointer too: the write path does not enforce a required: hint, so a stored
// row may lack one, and a value type there would invent a
// zero for it. <Kind>Required and Missing carry the requirement instead.
// Slices and maps carry nil-versus-empty natively.
//
// DECODE READS A STORED SHAPE. It is not the write-admission gate, and the
// difference is deliberate rather than an omission:
//
//   - What it refuses: an undeclared key, a value of the wrong type, an enum or
//     state outside its declared set, a value outside a declared set or pattern,
//     a number outside a declared range, an integer past exact precision, a key
//     breaking a keyed map's contract, and a shape that is not the declared
//     container.
//   - What it does NOT check: the SEMANTICS of the string family. An absolute
//     URL, an RFC 5322 mailbox, an E.164 phone number, an IANA time zone, an
//     RRULE, a civil date, an ISO 8601 duration — engine coerceProps refuses each of
//     those on the way IN, and every stored value has already been through it.
//     Repeating the checks here would be a second grammar to keep in step, and
//     the one place they could differ is a row admitted by an older binary,
//     which refusing now would lock out of its own repository.
//   - Where it is STRICTER than the write path: a datetime must be RFC 3339,
//     because coerceProps normalizes every admitted spelling to RFC 3339 Nano
//     before storing. A stored datetime that is not one did not come from a
//     write.
//   - What needs the repository and so cannot be here: whether a reference's
//     referent exists, whether a transition is legal from where the record
//     stands, whether this writer may write a managed property.
`

// supportBody is the shared vocabulary of every generated file: the types the
// generated structs are built from and the decoder they call. It is generated
// rather than hand-written so that one task rewrites the whole package and no
// half of it can be edited into disagreement with the other.
const supportBody = `
// ReferencePath is a typed POINTER stored as a property value: the referent's
// record PATH, "<kind>/<id>" — ONE string, the whole stored value, so a pointer
// compares and indexes as the single value it is.
//
//	core.substrate.reamde.dev/llmprovider/claude   a published kind's record
//	task/abc123                                    a repository-local kind's
type ReferencePath string

// SplitReferencePath splits a reference into the referent's kind and id.
//
// It rests on the KIND GRAMMAR and nothing else, so it needs no registry: an
// authority always carries a dot and a kind NAME never does. The first segment
// therefore decides which form this is, and the id is everything after the kind
// — slashes included, because a DECLARATION record's id is itself a kind
// reference.
//
// This is a SECOND spelling of vocabulary.SplitRecordPath, which the leaf rule
// forces: package corekinds imports nothing from the module. The two are held
// together by TestSplitReferencePathAgreesWithVocabulary, not by hope.
func SplitReferencePath(path ReferencePath) (kind, id string, ok bool) {
	first, rest, split := strings.Cut(string(path), "/")
	if !split || first == "" || rest == "" {
		return "", "", false
	}
	if !strings.Contains(first, ".") {
		return first, rest, true
	}
	name, remainder, split := strings.Cut(rest, "/")
	if !split || name == "" || remainder == "" {
		return "", "", false
	}
	return first + "/" + name, remainder, true
}

// SecretRef is what a secret property STORES: an opaque ref into the engine's
// sealed store, never the material. Reads redact even the ref, so a decoded
// value is as often Redacted as it is a ref.
type SecretRef string

// Digest is a server-minted comparator: 64 lowercase hex characters of
// SHA-256, matched in SQL and never revealed. Reads redact it too.
type Digest string

// BlobDigest names bytes in the content-addressed store by the blob record's
// id, which is the digest.
type BlobDigest string

// BlobDigestPrefix is what every blob digest starts with. It mirrors
// substrate.BlobDigestPrefix, which this package does not import: a leaf with
// no substrate imports is what lets the write path and the generator both
// depend on it.
const BlobDigestPrefix = "blob-sha256-"

// Redacted is what a sensitive property reads back as. Sending it back is a
// round trip rather than an assignment, so a decoder admits it where a digest's
// own grammar would not.
const Redacted = "<redacted>"

// Dynamic is a json property: a payload whose shape core does not own. It is an
// ALIAS rather than a named type, so a caller passes an ordinary map or slice
// without a conversion, and nil is its absence — which is why a Dynamic field
// is never a pointer.
type Dynamic = any

// Problem is one structural refusal: the property path it sits at, in the
// declaration's own spelling, and what was wrong there.
type Problem struct {
	Path    string
	Message string
}

func (p Problem) Error() string { return p.Path + ": " + p.Message }

// StateTransition is one declared move of a machine. It carries no guard:
// anyone may perform any declared move, and the stamps are the properties the
// move writes.
type StateTransition struct {
	From    string
	To      string
	Stamps  map[string]string
	OnEnter string
	// Notifies is the thread-reference property the move reports into.
	Notifies string
}

// Bounds is a declared numeric range, each half present only where the
// declaration wrote one.
type Bounds struct {
	Min *float64
	Max *float64
}

// bound is how the generated code spells a declared bound.
func bound(v float64) *float64 { return &v }

// Declared reports whether name is one of a generated key set's names: the
// membership half of every <Kind>Keys.
func Declared(keys []string, name string) bool {
	for _, k := range keys {
		if k == name {
			return true
		}
	}
	return false
}

// The contracts a keyed map's keys hold to, as anchored regular expressions.
// The grammars are vocabulary.KeyPatternRegexp's, and TestKeyContractsAgree in
// this package holds the two spellings to one answer. A keyed map's keys are
// also counted in Postgres (the narrowing guard), so a grammar that drifted
// here would be a third answer to a question that has one.
const (
	KeyPatternCamelRegexp   = ` + "`" + `^[a-z][a-zA-Z0-9]*$` + "`" + `
	KeyPatternKindRefRegexp = ` + "`" + `^([a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+/)?[a-z][a-z0-9]*$` + "`" + `
)

var (
	reCamel   = regexp.MustCompile(KeyPatternCamelRegexp)
	reKindRef = regexp.MustCompile(KeyPatternKindRefRegexp)
	reDigest  = regexp.MustCompile(` + "`" + `^[0-9a-f]{64}$` + "`" + `)
)

// sortedKeys is the order every decode walks a map in, so the problems a bad
// document produces read the same on every run.
func sortedKeys(m map[string]any) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// at is a property path with one segment appended. The root's own properties
// carry no prefix, so a top-level problem reads "pricing" and not ".pricing".
func at(path, segment string) string {
	if path == "" {
		return segment
	}
	return path + "." + segment
}

// index is the path of one element of a repeated value.
func index(path string, i int) string { return path + "[" + strconv.Itoa(i) + "]" }

// decoder accumulates every problem in one pass. A decoder that stopped at the
// first one would make a form show its errors one at a time, which is a form
// nobody finishes.
type decoder struct {
	problems []Problem
}

func (d *decoder) problemf(path, format string, args ...any) {
	d.problems = append(d.problems, Problem{Path: path, Message: fmt.Sprintf(format, args...)})
}

func (d *decoder) unknown(path, kind string) { d.problemf(path, "not declared on %s", kind) }

func (d *decoder) mapping(path string, v any) (map[string]any, bool) {
	m, ok := v.(map[string]any)
	if !ok {
		d.problemf(path, "expected an object")
		return nil, false
	}
	return m, true
}

func (d *decoder) list(path string, v any) ([]any, bool) {
	items, ok := v.([]any)
	if !ok {
		d.problemf(path, "expected a list")
		return nil, false
	}
	return items, true
}

// key holds one key of a keyed map to its declared contract. The KEYS are data,
// so an undeclared one is admitted — that is what a map is for — and the
// contract is the whole check standing between a writer and the stored value.
func (d *decoder) key(path, key, pattern string) bool {
	if key == "" {
		d.problemf(path, "a keyed map's key is never empty")
		return false
	}
	switch pattern {
	case "camel":
		if !reCamel.MatchString(key) {
			d.problemf(at(path, key), "a key must be camelCase")
			return false
		}
	case "kindRef":
		if !reKindRef.MatchString(key) {
			d.problemf(at(path, key), "a key must be a kind reference")
			return false
		}
	}
	return true
}

// text decodes a string-family value, held to the declared value set and
// pattern where the declaration carries either — and to NOTHING else. The
// semantics of a url, an email, a phone, a timezone, a recurrence, a date or a
// duration are the write path's gate (engine coerceProps); a stored value has
// already passed it, and a second grammar here would be a second answer. The
// package doc has the whole boundary.
//
// NOTHING is coerced: a number is not a string, because a decoder that accepted
// one would hand back a value the author never wrote.
func (d *decoder) text(path string, v any, values []string, pattern *regexp.Regexp) (string, bool) {
	s, ok := v.(string)
	if !ok {
		d.problemf(path, "expected a string")
		return "", false
	}
	if len(values) > 0 && !Declared(values, s) {
		d.problemf(path, "expected one of %s", strings.Join(values, ", "))
		return "", false
	}
	if pattern != nil && !pattern.MatchString(s) {
		d.problemf(path, "does not match %s", pattern.String())
		return "", false
	}
	return s, true
}

// instant decodes a datetime VERBATIM, checking only that it is an RFC 3339
// instant — which every STORED datetime is, because coerceProps normalizes the
// spellings it admits to RFC 3339 Nano before storing. This is the one place the
// decoder is stricter than the write path, and it is stricter about the form it
// is guaranteed to be handed.
//
// Normalizing here is what it must not do: the stored string is the value, and
// rewriting it would stop Decode and Properties being each other's inverse.
func (d *decoder) instant(path string, v any) (string, bool) {
	s, ok := v.(string)
	if !ok {
		d.problemf(path, "expected an RFC 3339 instant")
		return "", false
	}
	if _, err := time.Parse(time.RFC3339, s); err != nil {
		d.problemf(path, "expected an RFC 3339 instant")
		return "", false
	}
	return s, true
}

// numeric reads a FLOAT in every spelling one arrives in. jsonb reads back as
// float64 and YAML decodes as int, so refusing either would refuse values that
// have merely been through storage.
func (d *decoder) numeric(path string, v any) (float64, bool) {
	switch n := v.(type) {
	case int:
		return float64(n), true
	case int32:
		return float64(n), true
	case int64:
		return float64(n), true
	case float32:
		return float64(n), true
	case float64:
		return n, true
	case json.Number:
		f, err := n.Float64()
		if err != nil {
			d.problemf(path, "expected a number")
			return 0, false
		}
		return f, true
	}
	d.problemf(path, "expected a number")
	return 0, false
}

// maxExactInteger is 2^53: the largest integer every float64 below it can hold
// exactly. Above it, float64 arithmetic skips odd values — 9007199254740993
// becomes ...992 — so an integer that has NOT been through a float keeps its
// spelling here, and one that arrives as a float above the line is refused
// rather than silently rounded into a stored value nobody wrote.
const maxExactInteger = 1 << 53

// integer decodes an int WITHOUT going through a float: an int64 that came from
// a Go caller or a json.Number that came off the wire keeps every bit, which is
// what makes Decode and Properties inverses at the top of the range.
func (d *decoder) integer(path string, v any, b Bounds) (int64, bool) {
	var n int64
	switch t := v.(type) {
	case int:
		n = int64(t)
	case int32:
		n = int64(t)
	case int64:
		n = t
	case json.Number:
		parsed, ok := d.numberInteger(path, t)
		if !ok {
			return 0, false
		}
		n = parsed
	case float32, float64:
		f, _ := d.numeric(path, v)
		if f != math.Trunc(f) {
			d.problemf(path, "expected an integer")
			return 0, false
		}
		// A float64 past the exact-integer line is a value that may already have
		// been rounded, and there is no way to tell which integer it was.
		if f >= maxExactInteger || f <= -maxExactInteger {
			d.problemf(path, "expected an integer within exact precision (%d); a larger one must not arrive as a float", int64(maxExactInteger))
			return 0, false
		}
		n = int64(f)
	default:
		d.problemf(path, "expected an integer")
		return 0, false
	}
	if !d.inIntBounds(path, n, b) {
		return 0, false
	}
	return n, true
}

// numberInteger reads an integer out of a json.Number's OWN SPELLING, exactly.
// ParseInt is the fast path and covers every plain-digit form; an exponent form
// (1e3, 10e-1) is one the write path accepts and normalizes, so it is parsed as
// an exact rational rather than through a float64, which would round the large
// ones into a value nobody wrote.
func (d *decoder) numberInteger(path string, n json.Number) (int64, bool) {
	if v, err := strconv.ParseInt(string(n), 10, 64); err == nil {
		return v, true
	}
	r, ok := new(big.Rat).SetString(string(n))
	if !ok || !r.IsInt() {
		d.problemf(path, "expected an integer")
		return 0, false
	}
	whole := r.Num()
	if !whole.IsInt64() {
		d.problemf(path, "expected an integer an int64 can hold")
		return 0, false
	}
	return whole.Int64(), true
}

// inIntBounds holds an integer to a declared range WITHOUT a float in the
// comparison. Converting the value would undo the work above: under a max of
// 9007199254740992, the value 9007199254740993 rounds down to the bound itself
// and is admitted.
func (d *decoder) inIntBounds(path string, n int64, b Bounds) bool {
	if b.Min != nil && !atLeast(n, *b.Min) {
		d.problemf(path, "must be >= %v", *b.Min)
		return false
	}
	if b.Max != nil && !atMost(n, *b.Max) {
		d.problemf(path, "must be <= %v", *b.Max)
		return false
	}
	return true
}

// The int64 range as float64. Both are exactly representable (2^63), so a bound
// compared against them is compared exactly.
const (
	minInt64Float = -9223372036854775808.0
	maxInt64Float = 9223372036854775808.0
)

// atLeast compares an integer with a declared lower bound AS INTEGERS. The bound
// rounds up, because the value is an integer and nothing integral sits between
// 0.5 and 1. A bound outside the int64 range is not a comparison but an answer
// about the whole range.
func atLeast(n int64, min float64) bool {
	threshold := math.Ceil(min)
	switch {
	case threshold >= maxInt64Float:
		return false
	case threshold < minInt64Float:
		return true
	}
	return n >= int64(threshold)
}

// atMost is atLeast's twin: the bound rounds DOWN, for the same reason.
func atMost(n int64, max float64) bool {
	threshold := math.Floor(max)
	switch {
	case threshold >= maxInt64Float:
		return true
	case threshold < minInt64Float:
		return false
	}
	return n <= int64(threshold)
}

func (d *decoder) number(path string, v any, b Bounds) (float64, bool) {
	f, ok := d.numeric(path, v)
	if !ok || !d.inBounds(path, f, b) {
		return 0, false
	}
	return f, true
}

// inBounds holds a FLOAT to a declared range. An int goes through inIntBounds
// instead: there the comparison itself has to be exact.
func (d *decoder) inBounds(path string, f float64, b Bounds) bool {
	if b.Min != nil && f < *b.Min {
		d.problemf(path, "must be >= %v", *b.Min)
		return false
	}
	if b.Max != nil && f > *b.Max {
		d.problemf(path, "must be <= %v", *b.Max)
		return false
	}
	return true
}

func (d *decoder) flag(path string, v any) (bool, bool) {
	b, ok := v.(bool)
	if !ok {
		d.problemf(path, "expected a bool")
		return false, false
	}
	return b, true
}

// secret decodes the REF a secret property stores. Any string is a shape a
// sealed store can hold — the engine mints the ref, so nothing here can know
// its alphabet — and the redaction sentinel is one of them, because a read
// hands it back and a write may hand it straight on.
func (d *decoder) secret(path string, v any) (SecretRef, bool) {
	s, ok := d.text(path, v, nil, nil)
	if !ok {
		return "", false
	}
	return SecretRef(s), true
}

// digest decodes a server-minted comparator: 64 lowercase hex, or the redaction
// sentinel a read handed back.
func (d *decoder) digest(path string, v any) (Digest, bool) {
	s, ok := d.text(path, v, nil, nil)
	if !ok {
		return "", false
	}
	if s != Redacted && !reDigest.MatchString(s) {
		d.problemf(path, "expected a SHA-256 digest (64 lowercase hex)")
		return "", false
	}
	return Digest(s), true
}

func (d *decoder) blob(path string, v any) (BlobDigest, bool) {
	s, ok := d.text(path, v, nil, nil)
	if !ok {
		return "", false
	}
	if !strings.HasPrefix(s, BlobDigestPrefix) || !reDigest.MatchString(strings.TrimPrefix(s, BlobDigestPrefix)) {
		d.problemf(path, "expected a blob digest (%s<64 hex>)", BlobDigestPrefix)
		return "", false
	}
	return BlobDigest(s), true
}

// reference decodes a record PATH, taking the kind from the declaration's pin
// where a bare id was written and the declaration pins a concrete referent —
// the shorthand a single-target edge has always admitted.
//
// The {kind, id} arm reads the RELEASED dialect-1 shape, which stored rows
// written before the flat form still hold. Nothing authors it.
func (d *decoder) reference(path string, v any, to string) (ReferencePath, bool) {
	var id string
	switch t := v.(type) {
	case string:
		if t == "" {
			d.problemf(path, "a reference needs an id")
			return "", false
		}
		if _, _, ok := SplitReferencePath(ReferencePath(t)); ok {
			return ReferencePath(t), true
		}
		id = t
	case map[string]any:
		kind, _ := t["kind"].(string)
		rid, _ := t["id"].(string)
		if rid == "" {
			d.problemf(path, "a reference needs an id")
			return "", false
		}
		if kind != "" {
			return ReferencePath(kind + "/" + rid), true
		}
		id = rid
	default:
		d.problemf(path, "expected a \"<kind>/<id>\" reference path")
		return "", false
	}
	if to == "" || to == "any" {
		d.problemf(path, "a reference to any kind needs a full \"<kind>/<id>\" path")
		return "", false
	}
	return ReferencePath(to + "/" + id), true
}

// dynamic decodes a json property, which is every shape: core does not own it,
// so there is nothing here to check that would not be a guess.
func (d *decoder) dynamic(path string, v any) (Dynamic, bool) { return v, true }
`
