package main

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"unicode"
)

// generateTS renders the plan as ONE dependency-free TypeScript module. It
// declares its own Reference and its own scalar aliases rather than importing
// the hand-written wire types: a generated module that reached into
// src/lib/api would make the console's import graph depend on generation order,
// and the shapes here are the declarations', not the REST envelope's.
func generateTS(p *plan, source string) []byte {
	b := &bytes.Buffer{}
	fmt.Fprintf(b, "// Code generated by cmd/kindsgen from %s. DO NOT EDIT.\n", source)
	fmt.Fprintf(b, "// `mise run kinds:gen` rewrites this file; an edit here is lost.\n\n")
	tsComment(b, "The core vocabulary as TypeScript: one interface per kind declared under "+source+".\n\nEVERY PROPERTY IS OPTIONAL, a `required:` one included. These interfaces describe what a STORED record can hold, and the server does not enforce `required:` — it is a form-level hint — so a non-optional field would promise a value nothing guarantees. The requirement is data instead: `<kind>Required` names it, and a form is what refuses to submit without it.\n\nA `json` property is Dynamic (unknown), because its shape is one core does not own — narrow it where you read it.\n\nA state is NOT a stored property value: it lives in the record's own state column and moves by transition. It appears on the interface because every read surface shows it in the properties map, and its declared states, initial state and legal moves are the consts beside the interface.", "")
	b.WriteString("\n")

	tsComment(b, "A typed pointer, as the referent's record PATH: `<kind>/<id>` — one string, the whole stored value. `core.substrate.reamde.dev/llmprovider/claude` names the llmprovider `claude`; a repository-local kind drops the authority, `task/abc`.", "")
	b.WriteString("export type ReferencePath = string\n\n")

	tsComment(b, "What a secret property STORES: an opaque ref into the server's sealed store, never the material. Reads redact even the ref.", "")
	b.WriteString("export type SecretRef = string\n\n")
	tsComment(b, "A server-minted comparator, 64 lowercase hex characters of SHA-256. Reads redact it.", "")
	b.WriteString("export type Digest = string\n\n")
	tsComment(b, "Bytes in the content-addressed store, named by the blob record's id.", "")
	b.WriteString("export type BlobDigest = string\n\n")
	tsComment(b, "A json property: a payload whose shape core does not own.", "")
	b.WriteString("export type Dynamic = unknown\n\n")
	tsComment(b, "One declared move of a machine. It carries no guard — anyone may perform any declared move — and the stamps are the properties the move writes.", "")
	b.WriteString("export interface StateTransition<S extends string = string> {\n")
	b.WriteString("  from: S\n  to: S\n  stamps?: Record<string, string>\n  onEnter?: string\n}\n")

	for _, k := range p.Kinds {
		for _, s := range k.Structs {
			b.WriteString("\n")
			tsStruct(b, s)
			for _, e := range s.Enums {
				tsEnum(b, e)
			}
			if s.Root {
				for _, st := range k.States {
					tsState(b, st)
				}
			}
		}
	}
	return b.Bytes()
}

func tsStruct(b *bytes.Buffer, s *structPlan) {
	doc := s.Name + " is " + s.Owner + "."
	if !s.Root {
		doc = s.Name + " is one value of the `" + s.Path + "` object declared on " + s.Owner + "."
	}
	if s.Doc != "" {
		doc += "\n\n" + s.Doc
	}
	tsComment(b, doc, "")
	// A fieldless object is CLOSED: it declares no field, so it admits no key,
	// and the empty record is the type that says so. `interface X {}` says it
	// too, but eslint's no-empty-object-type refuses that spelling because it
	// reads as "any non-nullish value" everywhere else it appears.
	if len(s.Fields) == 0 {
		fmt.Fprintf(b, "export type %s = Record<string, never>\n", s.Name)
		return
	}
	fmt.Fprintf(b, "export interface %s {\n", s.Name)
	for _, f := range s.Fields {
		if doc := tsFieldDoc(f); doc != "" {
			tsComment(b, doc, "  ")
		}
		// EVERY property is optional, `required:` ones included. The interface
		// describes what a STORED record can hold, and the write path does not
		// enforce `required:` — a non-optional field would promise a value the
		// server never guaranteed. The requirement is data instead, below.
		fmt.Fprintf(b, "  %s?: %s\n", tsKey(f.Key), tsType(f))
	}
	b.WriteString("}\n")
	var required []string
	for _, f := range s.Fields {
		if f.Required {
			required = append(required, f.Key)
		}
	}
	if len(required) == 0 {
		return
	}
	sort.Strings(required)
	b.WriteString("\n")
	tsComment(b, "The properties "+s.Name+"'s declaration marks required. A form refuses to submit without them; the server does not, so nothing here is a guarantee about a record that arrives.", "")
	tsAssign(b, "export const "+uncapitalize(s.Name)+"Required: string[]", tsStrings(required))
}

func tsFieldDoc(f *fieldPlan) string {
	var parts []string
	if f.Decl.Description != "" {
		parts = append(parts, upperFirstRune(f.Decl.Description)+".")
	}
	if f.Class == classJSON {
		parts = append(parts, "Its shape is not core's to declare: narrow it where you read it.")
	}
	if f.Class == classState {
		parts = append(parts, "A state moves by transition, never by assignment.")
	}
	if f.Decl.Implicit {
		parts = append(parts, "Stamped by a transition, not written by hand: render it read-only.")
	}
	if f.Decl.Managed {
		parts = append(parts, "Managed: the server stamps it, so render it read-only.")
	}
	if f.Decl.Writer != "" {
		parts = append(parts, "Only the "+f.Decl.Writer+" actor may write it.")
	}
	if f.Class == classReference && f.Decl.To != "" {
		parts = append(parts, "Points at "+f.Decl.To+".")
	}
	return strings.Join(parts, " ")
}

func tsType(f *fieldPlan) string {
	switch {
	case f.repeated():
		return f.TSElem + "[]"
	case f.keyed():
		return "Record<string, " + f.TSElem + ">"
	}
	return f.TSElem
}

// tsKey quotes a property name only where TypeScript needs it. Declared names
// are camelCase, so this is a guard rather than a habit.
func tsKey(name string) string {
	for i, r := range name {
		if unicode.IsLetter(r) || r == '_' || r == '$' || (i > 0 && unicode.IsDigit(r)) {
			continue
		}
		return fmt.Sprintf("%q", name)
	}
	return name
}

func tsEnum(b *bytes.Buffer, e *enumPlan) {
	b.WriteString("\n")
	doc := e.Name + " is a declared enum: the admissible set, in declaration order."
	if e.Doc != "" {
		doc += "\n\n" + e.Doc
	}
	tsComment(b, doc, "")
	values := make([]string, 0, len(e.Values))
	for _, v := range e.Values {
		values = append(values, v.Value)
	}
	tsUnion(b, e.Name, values)
	b.WriteString("\n")
	name := uncapitalize(e.Name)
	tsAssign(b, fmt.Sprintf("export const %sValues: %s[]", name, e.Name), tsStrings(values))
	labels := e.labels()
	if len(labels) == 0 {
		return
	}
	b.WriteString("\n")
	tsComment(b, "The declared human labels: render the label, submit the value. A value with no declared label is absent, and the client humanizes it.", "")
	object := make(tsObject, 0, len(labels))
	for _, v := range labels {
		object = append(object, tsPair{Key: v.Value, Value: tsLiteral(v.Label)})
	}
	lhs := fmt.Sprintf("export const %sLabels: Partial<Record<%s, string>>", name, e.Name)
	// Prettier breaks a generic annotation whose one type argument is ITSELF
	// generic before it breaks the assignment, so a name long enough to overflow
	// the declaration line splits `Partial<>` and leaves the object where it is.
	// (`StateTransition<X>[]` and `X[]` below never take this shape: a lone
	// simple type argument hugs its brackets at any width.)
	if len(lhs)+len(" = {") > printWidth {
		lhs = fmt.Sprintf("export const %sLabels: Partial<\n  Record<%s, string>\n>", name, e.Name)
	}
	tsAssign(b, lhs, object)
}

func tsState(b *bytes.Buffer, s *statePlan) {
	b.WriteString("\n")
	doc := s.Name + " is the state of the `" + s.Property + "` machine.\n\n" +
		"A state is not a stored property value: it lives in the record's own state column and moves by transition. The declared moves are below; nothing else gates one, since a transition carries no guard."
	if s.Doc != "" {
		doc += "\n\n" + s.Doc
	}
	tsComment(b, doc, "")
	tsUnion(b, s.Name, s.Machine.States)
	name := uncapitalize(s.Name)
	b.WriteString("\n")
	tsAssign(b, fmt.Sprintf("export const %sValues: %s[]", name, s.Name), tsStrings(s.Machine.States))
	b.WriteString("\n")
	tsComment(b, "The state a creation is born into.", "")
	tsAssign(b, fmt.Sprintf("export const %sInitial: %s", name, s.Name), tsLiteral(s.Machine.Initial))
	b.WriteString("\n")
	transitions := make(tsArray, 0, len(s.Machine.Transitions))
	for _, t := range s.Machine.Transitions {
		move := tsObject{{Key: "from", Value: tsLiteral(t.From)}, {Key: "to", Value: tsLiteral(t.To)}}
		if len(t.Stamps) > 0 {
			stamps := make(tsObject, 0, len(t.Stamps))
			for _, st := range t.Stamps {
				stamps = append(stamps, tsPair{Key: st.Property, Value: tsLiteral(st.Value)})
			}
			move = append(move, tsPair{Key: "stamps", Value: stamps})
		}
		if t.OnEnter != "" {
			move = append(move, tsPair{Key: "onEnter", Value: tsLiteral(t.OnEnter)})
		}
		transitions = append(transitions, move)
	}
	tsAssign(b, fmt.Sprintf("export const %sTransitions: StateTransition<%s>[]", name, s.Name), transitions)
}

// printWidth is the console's prettier `printWidth`, and the reason this
// generator lays its output out at all rather than emitting one construct per
// line: `kinds:gen:check` demands the checked-in module be BYTE-EQUAL to what
// the generator produces, while `console:fmt:check` demands prettier's shape,
// so the only text that satisfies both is text prettier would already leave
// alone. Everything below is prettier's layout for the four constructs this
// file emits, and a change to any of them is checked by running both gates.
const printWidth = 80

// tsValue is the small value language the generated module is written in: a
// literal, an array or an object. It exists to answer two questions per value,
// which is all prettier's layout needs — how wide the flat form is, and what
// the broken form looks like at a given indent.
type tsValue interface {
	flat() string
	// mustBreak reports a value prettier refuses to print flat at ANY width.
	mustBreak() bool
	// render writes the broken form. The opening bracket goes at the cursor and
	// the closing one at indent, so a caller that hugs an `=` and one that broke
	// after it pass different indents for the same value.
	render(b *bytes.Buffer, indent int)
}

// tsLiteral is an already-quotable scalar: a string, the only leaf kind this
// generator emits. It never breaks.
type tsLiteral string

func (l tsLiteral) flat() string                  { return fmt.Sprintf("%q", string(l)) }
func (l tsLiteral) mustBreak() bool               { return false }
func (l tsLiteral) render(b *bytes.Buffer, _ int) { b.WriteString(l.flat()) }

type tsArray []tsValue

// tsStrings is the common array: string literals in the order given.
func tsStrings(values []string) tsArray {
	out := make(tsArray, 0, len(values))
	for _, v := range values {
		out = append(out, tsLiteral(v))
	}
	return out
}

func (a tsArray) flat() string {
	parts := make([]string, 0, len(a))
	for _, v := range a {
		parts = append(parts, v.flat())
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// mustBreak is prettier's own rule for an array of objects: more than one
// element, every one of them an object carrying more than one property, and it
// breaks however short the line would be.
func (a tsArray) mustBreak() bool {
	if len(a) < 2 {
		return false
	}
	for _, v := range a {
		object, ok := v.(tsObject)
		if !ok || len(object) < 2 {
			return false
		}
	}
	return true
}

func (a tsArray) render(b *bytes.Buffer, indent int) {
	if len(a) == 0 {
		b.WriteString("[]")
		return
	}
	b.WriteString("[\n")
	for _, v := range a {
		b.WriteString(strings.Repeat(" ", indent+2))
		tsInline(b, v, indent+2, 0)
		b.WriteString(",\n")
	}
	b.WriteString(strings.Repeat(" ", indent) + "]")
}

type tsPair struct {
	Key   string
	Value tsValue
}

type tsObject []tsPair

func (o tsObject) flat() string {
	if len(o) == 0 {
		return "{}"
	}
	parts := make([]string, 0, len(o))
	for _, p := range o {
		parts = append(parts, tsKey(p.Key)+": "+p.Value.flat())
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}

func (o tsObject) mustBreak() bool { return false }

func (o tsObject) render(b *bytes.Buffer, indent int) {
	if len(o) == 0 {
		b.WriteString("{}")
		return
	}
	b.WriteString("{\n")
	for _, p := range o {
		key := tsKey(p.Key) + ": "
		b.WriteString(strings.Repeat(" ", indent+2) + key)
		tsInline(b, p.Value, indent+2, len(key))
		b.WriteString(",\n")
	}
	b.WriteString(strings.Repeat(" ", indent) + "}")
}

// tsInline writes v where a trailing comma follows it: flat when the flat form
// and that comma still fit, broken otherwise. used is what the line already
// holds past the indent.
func tsInline(b *bytes.Buffer, v tsValue, indent, used int) {
	if !v.mustBreak() && indent+used+len(v.flat())+len(",") <= printWidth {
		b.WriteString(v.flat())
		return
	}
	v.render(b, indent)
}

// tsAssign writes `<lhs> = <value>` in prettier's assignment layout, which is
// three shapes and not two: the whole declaration on one line where it fits;
// the value's opening bracket HUGGING the `=` where that bracket fits, its body
// broken beneath; and, only where even the bracket would overflow, a break
// after the `=` with the value indented on the next line. A literal has no
// bracket to hug, so it takes the third shape directly.
func tsAssign(b *bytes.Buffer, lhs string, v tsValue) {
	head := lhs + " = "
	// The LAST line is the one the value has to fit beside: an lhs whose type
	// annotation already broke leaves only `> = ` in front of the value.
	width := len(head)
	if i := strings.LastIndex(head, "\n"); i >= 0 {
		width = len(head) - i - 1
	}
	if !v.mustBreak() && width+len(v.flat()) <= printWidth {
		b.WriteString(head + v.flat() + "\n")
		return
	}
	_, literal := v.(tsLiteral)
	if !literal && width+len("[") <= printWidth {
		b.WriteString(head)
		v.render(b, 0)
		b.WriteString("\n")
		return
	}
	b.WriteString(lhs + " =\n  ")
	if !v.mustBreak() && 2+len(v.flat()) <= printWidth {
		b.WriteString(v.flat() + "\n")
		return
	}
	v.render(b, 2)
	b.WriteString("\n")
}

// tsUnion writes a union type alias in prettier's three shapes for one: the
// members on the declaration line where they fit, flat on the next line where
// they fit there, and one `|`-led member per line otherwise.
func tsUnion(b *bytes.Buffer, name string, members []string) {
	lhs := "export type " + name + " ="
	quoted := make([]string, 0, len(members))
	for _, m := range members {
		quoted = append(quoted, fmt.Sprintf("%q", m))
	}
	flat := strings.Join(quoted, " | ")
	switch {
	case len(lhs)+len(" ")+len(flat) <= printWidth:
		b.WriteString(lhs + " " + flat + "\n")
	case 2+len(flat) <= printWidth:
		b.WriteString(lhs + "\n  " + flat + "\n")
	default:
		b.WriteString(lhs + "\n")
		for _, m := range quoted {
			b.WriteString("  | " + m + "\n")
		}
	}
}

// tsComment writes a JSDoc block wrapped at the console's print width, so the
// generated module reads like the hand-written lib files beside it.
func tsComment(b *bytes.Buffer, text, indent string) {
	paras := strings.Split(text, "\n\n")
	lines := wrap(paras[0], commentWidth-len(indent))
	if len(paras) == 1 && len(lines) == 1 {
		fmt.Fprintf(b, "%s/** %s */\n", indent, lines[0])
		return
	}
	fmt.Fprintf(b, "%s/** %s\n", indent, lines[0])
	for _, line := range lines[1:] {
		fmt.Fprintf(b, "%s * %s\n", indent, line)
	}
	for _, para := range paras[1:] {
		fmt.Fprintf(b, "%s *\n", indent)
		for _, line := range wrap(para, commentWidth-len(indent)) {
			fmt.Fprintf(b, "%s * %s\n", indent, line)
		}
	}
	fmt.Fprintf(b, "%s */\n", indent)
}

// uncapitalize renders a type name as the const name beside it: the leading
// initialism run lowercases whole, except its last letter when a word follows
// it, so LLMProviderWire is llmProviderWire and Blob is blob.
func uncapitalize(s string) string {
	runes := []rune(s)
	upper := 0
	for upper < len(runes) && unicode.IsUpper(runes[upper]) {
		upper++
	}
	switch {
	case upper == 0:
		return s
	case upper == 1 || upper == len(runes):
		for i := range runes[:upper] {
			runes[i] = unicode.ToLower(runes[i])
		}
	default:
		for i := range runes[:upper-1] {
			runes[i] = unicode.ToLower(runes[i])
		}
	}
	return string(runes)
}
