package main

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"unicode"
)

// generateTS renders the plan as ONE dependency-free TypeScript module. It
// declares its own Reference and its own scalar aliases rather than importing
// the hand-written wire types: a generated module that reached into
// src/lib/api would make the console's import graph depend on generation order,
// and the shapes here are the declarations', not the REST envelope's.
func generateTS(p *plan, source string) []byte {
	b := &bytes.Buffer{}
	fmt.Fprintf(b, "// Code generated by cmd/kindsgen from %s. DO NOT EDIT.\n", source)
	fmt.Fprintf(b, "// `mise run kinds:gen` rewrites this file; an edit here is lost.\n\n")
	tsComment(b, "The core vocabulary as TypeScript: one interface per kind declared under "+source+".\n\nAn OPTIONAL property is optional here too, and a required one is not: absence stored is absence authored, and a field materialized to an empty string is a value nobody wrote. A `json` property is Dynamic (unknown), because its shape is one core does not own — narrow it where you read it.\n\nA state is NOT a stored property value: it lives in the record's own state column and moves by transition. It appears on the interface because every read surface shows it in the properties map, and its declared states, initial state and legal moves are the consts beside the interface.", "")
	b.WriteString("\n")

	tsComment(b, "A typed pointer: the referent's kind reference and its id, the same {kind, id} pair an edge target wears.", "")
	b.WriteString("export interface Reference {\n  kind: string\n  id: string\n}\n\n")

	tsComment(b, "What a secret property STORES: an opaque ref into the server's sealed store, never the material. Reads redact even the ref.", "")
	b.WriteString("export type SecretRef = string\n\n")
	tsComment(b, "A server-minted comparator, 64 lowercase hex characters of SHA-256. Reads redact it.", "")
	b.WriteString("export type Digest = string\n\n")
	tsComment(b, "Bytes in the content-addressed store, named by the blob record's id.", "")
	b.WriteString("export type BlobDigest = string\n\n")
	tsComment(b, "A json property: a payload whose shape core does not own.", "")
	b.WriteString("export type Dynamic = unknown\n\n")
	tsComment(b, "One declared move of a machine. It carries no guard — anyone may perform any declared move — and the stamps are the properties the move writes.", "")
	b.WriteString("export interface StateTransition<S extends string = string> {\n")
	b.WriteString("  from: S\n  to: S\n  stamps?: Record<string, string>\n  onEnter?: string\n}\n")

	for _, k := range p.Kinds {
		for _, s := range k.Structs {
			b.WriteString("\n")
			tsStruct(b, s)
			for _, e := range s.Enums {
				tsEnum(b, e)
			}
			if s.Root {
				for _, st := range k.States {
					tsState(b, st)
				}
			}
		}
	}
	return b.Bytes()
}

func tsStruct(b *bytes.Buffer, s *structPlan) {
	doc := s.Name + " is " + s.Owner + "."
	if !s.Root {
		doc = s.Name + " is one value of the `" + s.Path + "` object declared on " + s.Owner + "."
	}
	if s.Doc != "" {
		doc += "\n\n" + s.Doc
	}
	tsComment(b, doc, "")
	fmt.Fprintf(b, "export interface %s {\n", s.Name)
	for _, f := range s.Fields {
		if doc := tsFieldDoc(f); doc != "" {
			tsComment(b, doc, "  ")
		}
		// EVERY property is optional, `required:` ones included. The interface
		// describes what a STORED record can hold, and the write path does not
		// enforce `required:` — a non-optional field would promise a value the
		// server never guaranteed. The requirement is data instead, below.
		fmt.Fprintf(b, "  %s?: %s\n", tsKey(f.Key), tsType(f))
	}
	b.WriteString("}\n")
	var required []string
	for _, f := range s.Fields {
		if f.Required {
			required = append(required, f.Key)
		}
	}
	if len(required) == 0 {
		return
	}
	sort.Strings(required)
	b.WriteString("\n")
	tsComment(b, "The properties "+s.Name+"'s declaration marks required. A form refuses to submit without them; the server does not, so nothing here is a guarantee about a record that arrives.", "")
	fmt.Fprintf(b, "export const %sRequired: string[] = [\n", uncapitalize(s.Name))
	for _, key := range required {
		fmt.Fprintf(b, "  %q,\n", key)
	}
	b.WriteString("]\n")
}

func tsFieldDoc(f *fieldPlan) string {
	var parts []string
	if f.Decl.Description != "" {
		parts = append(parts, upperFirstRune(f.Decl.Description)+".")
	}
	if f.Class == classJSON {
		parts = append(parts, "Its shape is not core's to declare: narrow it where you read it.")
	}
	if f.Class == classState {
		parts = append(parts, "A state moves by transition, never by assignment.")
	}
	if f.Decl.Implicit {
		parts = append(parts, "Stamped by a transition, not written by hand: render it read-only.")
	}
	if f.Decl.Managed {
		parts = append(parts, "Managed: the server stamps it, so render it read-only.")
	}
	if f.Decl.Writer != "" {
		parts = append(parts, "Only the "+f.Decl.Writer+" actor may write it.")
	}
	if f.Decl.RefersTo != "" {
		parts = append(parts, "Names a "+f.Decl.RefersTo+": offer a picker, not a text box.")
	}
	if f.Class == classReference && f.Decl.To != "" {
		parts = append(parts, "Points at "+f.Decl.To+".")
	}
	return strings.Join(parts, " ")
}

func tsType(f *fieldPlan) string {
	switch {
	case f.repeated():
		return f.TSElem + "[]"
	case f.keyed():
		return "Record<string, " + f.TSElem + ">"
	}
	return f.TSElem
}

// tsKey quotes a property name only where TypeScript needs it. Declared names
// are camelCase, so this is a guard rather than a habit.
func tsKey(name string) string {
	for i, r := range name {
		if unicode.IsLetter(r) || r == '_' || r == '$' || (i > 0 && unicode.IsDigit(r)) {
			continue
		}
		return fmt.Sprintf("%q", name)
	}
	return name
}

func tsEnum(b *bytes.Buffer, e *enumPlan) {
	b.WriteString("\n")
	doc := e.Name + " is a declared enum: the admissible set, in declaration order."
	if e.Doc != "" {
		doc += "\n\n" + e.Doc
	}
	tsComment(b, doc, "")
	fmt.Fprintf(b, "export type %s =\n", e.Name)
	for _, v := range e.Values {
		fmt.Fprintf(b, "  | %q\n", v.Value)
	}
	b.WriteString("\n")
	name := uncapitalize(e.Name)
	fmt.Fprintf(b, "export const %sValues: %s[] = [\n", name, e.Name)
	for _, v := range e.Values {
		fmt.Fprintf(b, "  %q,\n", v.Value)
	}
	b.WriteString("]\n")
	labels := e.labels()
	if len(labels) == 0 {
		return
	}
	b.WriteString("\n")
	tsComment(b, "The declared human labels: render the label, submit the value. A value with no declared label is absent, and the client humanizes it.", "")
	fmt.Fprintf(b, "export const %sLabels: Partial<Record<%s, string>> = {\n", name, e.Name)
	for _, v := range labels {
		fmt.Fprintf(b, "  %q: %q,\n", v.Value, v.Label)
	}
	b.WriteString("}\n")
}

func tsState(b *bytes.Buffer, s *statePlan) {
	b.WriteString("\n")
	doc := s.Name + " is the state of the `" + s.Property + "` machine.\n\n" +
		"A state is not a stored property value: it lives in the record's own state column and moves by transition. The declared moves are below; nothing else gates one, since a transition carries no guard."
	if s.Doc != "" {
		doc += "\n\n" + s.Doc
	}
	tsComment(b, doc, "")
	fmt.Fprintf(b, "export type %s =\n", s.Name)
	for _, v := range s.Machine.States {
		fmt.Fprintf(b, "  | %q\n", v)
	}
	name := uncapitalize(s.Name)
	b.WriteString("\n")
	fmt.Fprintf(b, "export const %sValues: %s[] = [\n", name, s.Name)
	for _, v := range s.Machine.States {
		fmt.Fprintf(b, "  %q,\n", v)
	}
	b.WriteString("]\n\n")
	tsComment(b, "The state a creation is born into.", "")
	fmt.Fprintf(b, "export const %sInitial: %s = %q\n\n", name, s.Name, s.Machine.Initial)
	fmt.Fprintf(b, "export const %sTransitions: StateTransition<%s>[] = [\n", name, s.Name)
	for _, t := range s.Machine.Transitions {
		fmt.Fprintf(b, "  { from: %q, to: %q", t.From, t.To)
		if len(t.Stamps) > 0 {
			b.WriteString(", stamps: { ")
			for i, st := range t.Stamps {
				if i > 0 {
					b.WriteString(", ")
				}
				fmt.Fprintf(b, "%q: %q", st.Property, st.Value)
			}
			b.WriteString(" }")
		}
		if t.OnEnter != "" {
			fmt.Fprintf(b, ", onEnter: %q", t.OnEnter)
		}
		b.WriteString(" },\n")
	}
	b.WriteString("]\n")
}

// tsComment writes a JSDoc block wrapped at the console's print width, so the
// generated module reads like the hand-written lib files beside it.
func tsComment(b *bytes.Buffer, text, indent string) {
	paras := strings.Split(text, "\n\n")
	lines := wrap(paras[0], commentWidth-len(indent))
	if len(paras) == 1 && len(lines) == 1 {
		fmt.Fprintf(b, "%s/** %s */\n", indent, lines[0])
		return
	}
	fmt.Fprintf(b, "%s/** %s\n", indent, lines[0])
	for _, line := range lines[1:] {
		fmt.Fprintf(b, "%s * %s\n", indent, line)
	}
	for _, para := range paras[1:] {
		fmt.Fprintf(b, "%s *\n", indent)
		for _, line := range wrap(para, commentWidth-len(indent)) {
			fmt.Fprintf(b, "%s * %s\n", indent, line)
		}
	}
	fmt.Fprintf(b, "%s */\n", indent)
}

// uncapitalize renders a type name as the const name beside it: the leading
// initialism run lowercases whole, except its last letter when a word follows
// it, so LLMProviderWire is llmProviderWire and Blob is blob.
func uncapitalize(s string) string {
	runes := []rune(s)
	upper := 0
	for upper < len(runes) && unicode.IsUpper(runes[upper]) {
		upper++
	}
	switch {
	case upper == 0:
		return s
	case upper == 1 || upper == len(runes):
		for i := range runes[:upper] {
			runes[i] = unicode.ToLower(runes[i])
		}
	default:
		for i := range runes[:upper-1] {
			runes[i] = unicode.ToLower(runes[i])
		}
	}
	return string(runes)
}
