-- Every record names the kind version that last wrote it.
--
-- `records.version` is the edit counter a write asserts with `ifVersion`;
-- nothing said which DEFINITION of the kind validated the row's properties.
-- A later conversion (a property rename, a remap) cannot tell a value written
-- under version 3 of a kind from one written under version 4 by looking at
-- the value alone, because admission refuses narrowing and never backfills,
-- so both are valid under the live definition.
--
-- `kind_version` is the kind's EFFECTIVE version at the write that last
-- moved the row: the kind's own pin where it has one, else its package's
-- (internal/vocabulary/load.go). It travels in the `record` delta and the
-- fold restores it (fold.go rowDelta.KindVersion), so a rebuild reproduces
-- it and nothing recomputes it from the live registry.
--
-- 0 is the absent stamp, the same spelling declaration versions use for
-- "none stored" (decision 0002): every row written before this column, and
-- every replayed entry whose delta carries no `kindVersion`, reads 0. Nothing
-- reconstructs the history; the value stays 0 until a write moves the row.
ALTER TABLE records ADD COLUMN IF NOT EXISTS kind_version bigint NOT NULL DEFAULT 0;
