-- The repository has one name, its authority, and its user logs in with it
-- (decision record 0074). `repositories.username` was the login name and the
-- lookup key every door started from; the authority is both now, so the
-- column and its unique index go. Nothing reads it: the credential record
-- carries the repository it admits to, and every lookup is by id.
--
-- A database whose users registered under the default authority loses
-- nothing they cannot type: `ada` is `ada.<the server's host>`, which is what
-- the login field takes. There is no way back — the column is dropped, not
-- kept — and the tree assumes fresh repositories before v1, as 0052 already
-- did.
--
-- Idempotent: a database that never had the column, or one that has already
-- dropped it, passes through.
ALTER TABLE repositories DROP COLUMN IF EXISTS username;
