#!/usr/bin/env bash
#
# The changelog, rendered from the two things that already say what changed:
# the upgrade notes under docs/changes/ and the conventional commit subjects.
# Nothing writes a CHANGELOG file. A release is a tag, and a note belongs to
# the first tag whose range ADDED it, so both inputs are read back from git
# and the output cannot disagree with what shipped.
#
#   changelog.sh                   every release, newest first, plus what main
#                                  holds past the last tag
#   changelog.sh --release <tag>   that release's notes alone: the header the
#                                  release job hands goreleaser, empty when the
#                                  range added no note
#
# docs/changes/README.md is the note format; lint:docs holds it, so this
# script trusts the frontmatter to be lines 1 to 3.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

groups=(breaking deprecated feature fix)
declare -A titles=(
  [breaking]="Breaking changes"
  [deprecated]="Deprecations"
  [feature]="Features"
  [fix]="Fixes"
)

# hashes prints $1 '#' characters.
hashes() { printf '%*s' "$1" '' | tr ' ' '#'; }

# The empty tree, so the first release's range has a start to diff from.
empty_tree="$(git hash-object -t tree /dev/null)"

# notes_in prints the notes ADDED after $1 up to $2, one path per line; $1
# empty means from the beginning. A note edited later stays in the release
# that added it.
notes_in() {
  git diff --name-only --diff-filter=A "${1:-$empty_tree}" "$2" -- 'docs/changes/*.md' |
    grep -v '/README\.md$' || true
}

# render_notes prints the notes added after $1 up to $2 grouped by type, the
# group heading at level $3 and each note's own headings pushed below it.
# Prints nothing when the range added none.
render_notes() {
  local from="$1" to="$2" level="$3" paths path group
  paths="$(notes_in "$from" "$to")"
  [ -n "$paths" ] || return 0
  for group in "${groups[@]}"; do
    local matched=()
    while IFS= read -r path; do
      # A note is never deleted once merged; one that was anyway is skipped
      # rather than failing every later render.
      [ -f "$path" ] || continue
      [ "$(sed -n '2p' "$path")" = "type: ${group}" ] && matched+=("$path")
    done <<<"$paths"
    [ "${#matched[@]}" -gt 0 ] || continue
    printf '%s %s\n\n' "$(hashes "$level")" "${titles[$group]}"
    for path in "${matched[@]}"; do
      # Lines 4 on, with every heading outside a code fence moved down by
      # $level, so a note's `#` lands one below its group.
      tail -n +4 "$path" | awk -v shift="$(hashes "$level")" '
        /^```/ { fence = !fence }
        !fence && /^#+ / { print shift $0; next }
        { print }
      ' | sed -e '/./,$!d'
      printf '\n'
    done
  done
}

# render_commits lists the feat and fix subjects and every break after $1 up
# to $2, oldest first, as goreleaser's release notes do, at level $3.
render_commits() {
  local from="$1" to="$2" level="$3" range="$2" subjects
  [ -n "$from" ] && range="${from}..${to}"
  subjects="$(git log --reverse --no-merges --format='%s (%h)' "$range" |
    grep -E '^(feat|fix)(\([^)]*\))?!?: |^[a-z]+(\([^)]*\))?!: ' || true)"
  [ -n "$subjects" ] || return 0
  printf '%s Commits\n\n' "$(hashes "$level")"
  while IFS= read -r line; do printf -- '- %s\n' "$line"; done <<<"$subjects"
  printf '\n'
}

mapfile -t tags < <(git tag --list 'v*' --sort=v:refname)

# previous_tag prints the tag before $1, or nothing for the first one.
previous_tag() {
  local i
  for i in "${!tags[@]}"; do
    if [ "${tags[$i]}" = "$1" ]; then
      [ "$i" -gt 0 ] && printf '%s' "${tags[$((i - 1))]}"
      return 0
    fi
  done
  echo "changelog: no tag $1" >&2
  return 1
}

if [ "${1:-}" = "--release" ]; then
  tag="${2:?changelog: --release needs a tag}"
  prev="$(previous_tag "$tag")"
  render_notes "$prev" "$tag" 2
  exit 0
fi

printf '# Changelog\n\n'
# shellcheck disable=SC2016 # the backticks are Markdown, not a substitution
printf 'Generated by `mise run changelog` from docs/changes/ and the commit log.\n\n'

last="${tags[${#tags[@]} - 1]:-}"
if [ -n "$last" ] && [ -n "$(git rev-list "${last}..HEAD")" ]; then
  printf '## Unreleased\n\n'
  render_notes "$last" HEAD 3
  render_commits "$last" HEAD 3
fi

for ((i = ${#tags[@]} - 1; i >= 0; i--)); do
  tag="${tags[$i]}"
  prev=""
  [ "$i" -gt 0 ] && prev="${tags[$((i - 1))]}"
  printf '## %s (%s)\n\n' "$tag" "$(git log -1 --format=%cs "$tag")"
  render_notes "$prev" "$tag" 3
  render_commits "$prev" "$tag" 3
done
