#!/usr/bin/env bash
#
# The changelog, rendered from the two things that already say what changed:
# the upgrade notes under docs/changes/ and the conventional commit subjects.
# Nothing writes a CHANGELOG file. A release is a tag, and a note belongs to
# the first tag that contains the commit which ADDED it, so both inputs are
# read back from git and the output cannot disagree with what shipped. The
# one exception is a note written after its release: its `release:` key
# names the tag, and wins.
#
#   changelog.sh                   every release, newest first, plus what main
#                                  holds past the last tag
#   changelog.sh --release <tag>   that release's notes alone: the header the
#                                  release job hands goreleaser, empty when it
#                                  has none
#
# docs/changes/README.md is the note format; lint:docs holds it, so this
# script trusts the frontmatter to be `---`, `type:`, an optional `release:`,
# then `---`.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

groups=(breaking deprecated feature fix)
declare -A titles=(
  [breaking]="Breaking changes"
  [deprecated]="Deprecations"
  [feature]="Features"
  [fix]="Fixes"
)

# hashes prints $1 '#' characters.
hashes() { printf '%*s' "$1" '' | tr ' ' '#'; }

# placement maps each note to the tag it belongs to, or `unreleased`.
declare -A placement=()
for path in docs/changes/*.md; do
  [ -e "$path" ] || continue
  [ "$(basename "$path")" = "README.md" ] && continue
  third="$(sed -n '3p' "$path")"
  if [[ "$third" == release:\ * ]]; then
    placement[$path]="${third#release: }"
    continue
  fi
  added="$(git log --diff-filter=A --format=%H -- "$path" | tail -n 1)"
  tag=""
  [ -n "$added" ] && tag="$(git tag --contains "$added" --list 'v*' --sort=v:refname | head -n 1)"
  placement[$path]="${tag:-unreleased}"
done

# render_notes prints the notes placed at $1 grouped by type, the group
# heading at level $2 and each note's own headings pushed below it. Prints
# nothing when none is placed there.
render_notes() {
  local at="$1" level="$2" path group body_from
  for group in "${groups[@]}"; do
    local matched=()
    for path in "${!placement[@]}"; do
      [ "${placement[$path]}" = "$at" ] || continue
      [ "$(sed -n '2p' "$path")" = "type: ${group}" ] && matched+=("$path")
    done
    [ "${#matched[@]}" -gt 0 ] || continue
    mapfile -t matched < <(printf '%s\n' "${matched[@]}" | LC_ALL=C sort)
    printf '%s %s\n\n' "$(hashes "$level")" "${titles[$group]}"
    for path in "${matched[@]}"; do
      # The body starts after the frontmatter's closing `---`, with every
      # heading outside a code fence moved down by $level, so a note's `#`
      # lands one below its group.
      body_from=4
      [ "$(sed -n '3p' "$path")" = "---" ] || body_from=5
      tail -n +"$body_from" "$path" | awk -v shift="$(hashes "$level")" '
        /^```/ { fence = !fence }
        !fence && /^#+ / { print shift $0; next }
        { print }
      ' | sed -e '/./,$!d'
      printf '\n'
    done
  done
}

# render_commits lists the feat and fix subjects and every break after $1 up
# to $2, oldest first, as goreleaser's release notes do, at level $3.
render_commits() {
  local from="$1" to="$2" level="$3" range="$2" subjects
  [ -n "$from" ] && range="${from}..${to}"
  subjects="$(git log --reverse --no-merges --format='%s (%h)' "$range" |
    grep -E '^(feat|fix)(\([^)]*\))?!?: |^[a-z]+(\([^)]*\))?!: ' || true)"
  [ -n "$subjects" ] || return 0
  printf '%s Commits\n\n' "$(hashes "$level")"
  while IFS= read -r line; do printf -- '- %s\n' "$line"; done <<<"$subjects"
  printf '\n'
}

mapfile -t tags < <(git tag --list 'v*' --sort=v:refname)

# previous_tag prints the tag before $1, or nothing for the first one.
previous_tag() {
  local i
  for i in "${!tags[@]}"; do
    if [ "${tags[$i]}" = "$1" ]; then
      [ "$i" -gt 0 ] && printf '%s' "${tags[$((i - 1))]}"
      return 0
    fi
  done
  echo "changelog: no tag $1" >&2
  return 1
}

if [ "${1:-}" = "--release" ]; then
  tag="${2:?changelog: --release needs a tag}"
  previous_tag "$tag" >/dev/null
  render_notes "$tag" 2
  exit 0
fi

printf '# Changelog\n\n'
# shellcheck disable=SC2016 # the backticks are Markdown, not a substitution
printf 'Generated by `mise run changelog` from docs/changes/ and the commit log.\n\n'

last="${tags[${#tags[@]} - 1]:-}"
if [ -n "$last" ] && [ -n "$(git rev-list "${last}..HEAD")" ]; then
  printf '## Unreleased\n\n'
  render_notes unreleased 3
  render_commits "$last" HEAD 3
fi

for ((i = ${#tags[@]} - 1; i >= 0; i--)); do
  tag="${tags[$i]}"
  prev=""
  [ "$i" -gt 0 ] && prev="${tags[$((i - 1))]}"
  printf '## %s (%s)\n\n' "$tag" "$(git log -1 --format=%cs "$tag")"
  render_notes "$tag" 3
  render_commits "$prev" "$tag" 3
done
