// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// Actor is core.substrate.reamde.dev/actor as its declaration admits it.
//
// One declared actor — the name a write is attributed to. Actors are
// attribution and a manager tier, never authorization: `api`, `console` and
// `substratectl` are the doors a human write comes through, and machine hands
// like `function:<name>` are minted at dispatch.
type Actor struct {
	// Version is this declaration's version. Managed: the engine stamps it, so
	// a supplied value does not decide it.
	Version *string

	// Authority is the authority that declares this actor.
	Authority *string

	// Source is builtin for shipped authorities, installed for connector
	// authorities. Managed: the engine stamps it, so a supplied value does not
	// decide it.
	Source *ActorSource

	// Tier is the manager tier this actor's direct writes hold at.
	Tier *ActorTier
}

// ActorSource is a declared enum: the admissible set, in declaration order.
//
// builtin for shipped authorities, installed for connector authorities
type ActorSource string

const (
	ActorSourceBuiltin   ActorSource = "builtin"
	ActorSourceInstalled ActorSource = "installed"
)

// ActorSourceValues are the declared values in declaration order, which is
// render order.
var ActorSourceValues = []string{"builtin", "installed"}

// Valid reports whether v is one of the declared values.
func (v ActorSource) Valid() bool { return Declared(ActorSourceValues, string(v)) }

// ActorTier is a declared enum: the admissible set, in declaration order.
//
// the manager tier this actor's direct writes hold at
type ActorTier string

const (
	ActorTierOwner   ActorTier = "owner"
	ActorTierBundle  ActorTier = "bundle"
	ActorTierMachine ActorTier = "machine"
)

// ActorTierValues are the declared values in declaration order, which is
// render order.
var ActorTierValues = []string{"owner", "bundle", "machine"}

// Valid reports whether v is one of the declared values.
func (v ActorTier) Valid() bool { return Declared(ActorTierValues, string(v)) }

// ActorKeys is the admitted key set: every property
// core.substrate.reamde.dev/actor declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var ActorKeys = []string{"authority", "source", "tier", "version"}

// DecodeActor decodes a properties map into Actor, refusing what the
// declaration cannot hold: an undeclared key, a value of the wrong type, an
// enum or state outside its set, a number outside its declared range or beyond
// exact integer precision, a key breaking a keyed map's contract. The value is
// nil unless the problems are empty, so a half-decoded record can never reach
// a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — ActorRequired and Missing are where
// requiredness lives.
func DecodeActor(props map[string]any) (*Actor, []Problem) {
	d := &decoder{}
	out, _ := decodeActor(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// ActorRequired names the properties the declaration marks `required:`,
// sorted. It is a FORM-LEVEL contract: the write path does not enforce it, so
// Decode admits a value that leaves one absent and this is what a client
// checks before it submits one.
var ActorRequired = []string{"authority"}

// Missing names the required properties this value leaves absent, in
// declaration order. Empty means every declared requirement is answered —
// not that the value is admissible, which is the substrate's answer and not a
// type's.
func (v *Actor) Missing() []string {
	var out []string
	if v.Authority == nil {
		out = append(out, "authority")
	}
	return out
}

// decodeActorSource decodes a declared ActorSource value.
func decodeActorSource(d *decoder, path string, v any) (ActorSource, bool) {
	s, ok := d.text(path, v, ActorSourceValues, nil)
	if !ok {
		return "", false
	}
	return ActorSource(s), true
}

// decodeActorTier decodes a declared ActorTier value.
func decodeActorTier(d *decoder, path string, v any) (ActorTier, bool) {
	s, ok := d.text(path, v, ActorTierValues, nil)
	if !ok {
		return "", false
	}
	return ActorTier(s), true
}

// decodeActor decodes one Actor value at path.
func decodeActor(d *decoder, path string, v any) (Actor, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return Actor{}, false
	}
	var out Actor
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "version":
			p := at(path, "version")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Version = &e
			}
		case "authority":
			p := at(path, "authority")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Authority = &e
			}
		case "source":
			p := at(path, "source")
			if e, ok := decodeActorSource(d, p, props[key]); ok {
				out.Source = &e
			}
		case "tier":
			p := at(path, "tier")
			if e, ok := decodeActorTier(d, p, props[key]); ok {
				out.Tier = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/actor")
		}
	}
	return out, true
}

// Encode is Actor as the properties map holds it, and DecodeActor's exact
// inverse: a nil pointer, a nil slice and a nil map each omit their key, so
// absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *Actor) Encode() map[string]any {
	out := map[string]any{}
	if v.Version != nil {
		out["version"] = *v.Version
	}
	if v.Authority != nil {
		out["authority"] = *v.Authority
	}
	if v.Source != nil {
		out["source"] = string(*v.Source)
	}
	if v.Tier != nil {
		out["tier"] = string(*v.Tier)
	}
	return out
}
