// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// Agent is core.substrate.reamde.dev/agent as its declaration admits it.
//
// One declared agent: a callable whose body is an LLM loop, dispatched like a
// function by a trigger, the call API or another agent. The row IS the prompt
// store, so changing what an agent does is a record write and the changelog is
// its version history.
type Agent struct {
	// Version is this declaration's version.
	Version *string

	// Name is the agent's local name.
	Name *string

	// Authority is the authority that declares it.
	Authority *string

	// Description is the model-facing tool card — what this agent is for as
	// a sub-agent.
	Description *string

	// Prompt is the system prompt; the row is the prompt store.
	Prompt *string

	// Provider is the llmprovider record id this agent's loop completes
	// against.
	Provider *string

	// Model is the model id sent on every completion.
	Model *string

	// Functions is the function records this agent may call as tools.
	Functions []string

	// Subagents is the sub-agent records this agent may delegate to.
	Subagents []string

	// SubagentOnly is only callable by other agents; withheld from the chat
	// surface.
	SubagentOnly *bool

	// Definition is the parsed manifest data the registry rebuilds from.
	Definition Dynamic
}

// AgentKeys is the admitted key set: every property
// core.substrate.reamde.dev/agent declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var AgentKeys = []string{"authority", "definition", "description", "functions", "model", "name", "prompt", "provider", "subagentOnly", "subagents", "version"}

// DecodeAgent decodes a properties map into Agent, refusing what the
// declaration cannot hold: an undeclared key, a value of the wrong type, an
// enum or state outside its set, a number outside its declared range or beyond
// exact integer precision, a key breaking a keyed map's contract. The value is
// nil unless the problems are empty, so a half-decoded record can never reach
// a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — AgentRequired and Missing are where
// requiredness lives.
func DecodeAgent(props map[string]any) (*Agent, []Problem) {
	d := &decoder{}
	out, _ := decodeAgent(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeAgent decodes one Agent value at path.
func decodeAgent(d *decoder, path string, v any) (Agent, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return Agent{}, false
	}
	var out Agent
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "version":
			p := at(path, "version")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Version = &e
			}
		case "name":
			p := at(path, "name")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Name = &e
			}
		case "authority":
			p := at(path, "authority")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Authority = &e
			}
		case "description":
			p := at(path, "description")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Description = &e
			}
		case "prompt":
			p := at(path, "prompt")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Prompt = &e
			}
		case "provider":
			p := at(path, "provider")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Provider = &e
			}
		case "model":
			p := at(path, "model")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Model = &e
			}
		case "functions":
			p := at(path, "functions")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Functions = list
			}
		case "subagents":
			p := at(path, "subagents")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Subagents = list
			}
		case "subagentOnly":
			p := at(path, "subagentOnly")
			if e, ok := d.flag(p, props[key]); ok {
				out.SubagentOnly = &e
			}
		case "definition":
			p := at(path, "definition")
			if e, ok := d.dynamic(p, props[key]); ok {
				out.Definition = e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/agent")
		}
	}
	return out, true
}

// Properties is Agent as the properties map holds it, and DecodeAgent's exact
// inverse: a nil pointer, a nil slice and a nil map each omit their key, so
// absence survives the round trip.
func (v *Agent) Properties() map[string]any {
	out := map[string]any{}
	if v.Version != nil {
		out["version"] = *v.Version
	}
	if v.Name != nil {
		out["name"] = *v.Name
	}
	if v.Authority != nil {
		out["authority"] = *v.Authority
	}
	if v.Description != nil {
		out["description"] = *v.Description
	}
	if v.Prompt != nil {
		out["prompt"] = *v.Prompt
	}
	if v.Provider != nil {
		out["provider"] = *v.Provider
	}
	if v.Model != nil {
		out["model"] = *v.Model
	}
	if v.Functions != nil {
		items := make([]any, 0, len(v.Functions))
		for i := range v.Functions {
			items = append(items, v.Functions[i])
		}
		out["functions"] = items
	}
	if v.Subagents != nil {
		items := make([]any, 0, len(v.Subagents))
		for i := range v.Subagents {
			items = append(items, v.Subagents[i])
		}
		out["subagents"] = items
	}
	if v.SubagentOnly != nil {
		out["subagentOnly"] = *v.SubagentOnly
	}
	if v.Definition != nil {
		out["definition"] = v.Definition
	}
	return out
}
