// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// Agent is core.substrate.reamde.dev/agent as its declaration admits it.
//
// One declared agent: a callable whose body is an LLM loop, dispatched like a
// function by a trigger, the call API or another agent. The row IS the prompt
// store, so changing what an agent does is a record write and the changelog is
// its version history.
type Agent struct {
	// Version is this declaration's version. Managed: the engine stamps it, so
	// a supplied value does not decide it.
	Version *string

	// Authority is the authority that declares it.
	Authority *string

	// Description is the model-facing tool card — what this agent is for as
	// a sub-agent.
	Description *string

	// Prompt is the system prompt; the row is the prompt store.
	Prompt *string

	// Provider is the llmprovider record id this agent's loop completes
	// against. Names a provider in the registry.
	Provider *string

	// Model is the model id sent on every completion.
	Model *string

	// Params is this agent's request knobs; the provider row's defaults sit
	// under them.
	Params *AgentParams

	// Tools is what the model may call, in declaration order.
	Tools []AgentTools

	// Agents is the sub-agent identities the loop exposes as tools. Names a
	// agent in the registry.
	Agents []string

	// Budgets is what bounds one invocation.
	Budgets *AgentBudgets

	// Permissions is what this agent is allowed to do while it runs; leave a
	// grant out and what it covers is refused.
	Permissions *AgentPermissions

	// SubagentOnly is only callable by other agents; withheld from the chat
	// surface.
	SubagentOnly *bool
}

// AgentKeys is the admitted key set: every property
// core.substrate.reamde.dev/agent declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var AgentKeys = []string{"agents", "authority", "budgets", "description", "model", "params", "permissions", "prompt", "provider", "subagentOnly", "tools", "version"}

// DecodeAgent decodes a properties map into Agent, refusing what the
// declaration cannot hold: an undeclared key, a value of the wrong type, an
// enum or state outside its set, a number outside its declared range or beyond
// exact integer precision, a key breaking a keyed map's contract. The value is
// nil unless the problems are empty, so a half-decoded record can never reach
// a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — AgentRequired and Missing are where
// requiredness lives.
func DecodeAgent(props map[string]any) (*Agent, []Problem) {
	d := &decoder{}
	out, _ := decodeAgent(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// AgentRequired names the properties the declaration marks `required:`,
// sorted. It is a FORM-LEVEL contract: the write path does not enforce it, so
// Decode admits a value that leaves one absent and this is what a client
// checks before it submits one.
var AgentRequired = []string{"authority", "description", "model", "prompt", "provider"}

// Missing names the required properties this value leaves absent, in
// declaration order. Empty means every declared requirement is answered —
// not that the value is admissible, which is the substrate's answer and not a
// type's.
func (v *Agent) Missing() []string {
	var out []string
	if v.Authority == nil {
		out = append(out, "authority")
	}
	if v.Description == nil {
		out = append(out, "description")
	}
	if v.Prompt == nil {
		out = append(out, "prompt")
	}
	if v.Provider == nil {
		out = append(out, "provider")
	}
	if v.Model == nil {
		out = append(out, "model")
	}
	return out
}

// decodeAgent decodes one Agent value at path.
func decodeAgent(d *decoder, path string, v any) (Agent, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return Agent{}, false
	}
	var out Agent
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "version":
			p := at(path, "version")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Version = &e
			}
		case "authority":
			p := at(path, "authority")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Authority = &e
			}
		case "description":
			p := at(path, "description")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Description = &e
			}
		case "prompt":
			p := at(path, "prompt")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Prompt = &e
			}
		case "provider":
			p := at(path, "provider")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Provider = &e
			}
		case "model":
			p := at(path, "model")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Model = &e
			}
		case "params":
			p := at(path, "params")
			if e, ok := decodeAgentParams(d, p, props[key]); ok {
				out.Params = &e
			}
		case "tools":
			p := at(path, "tools")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]AgentTools, 0, len(items))
				for i, item := range items {
					if e, ok := decodeAgentTools(d, index(p, i), item); ok {
						list = append(list, e)
					}
				}
				out.Tools = list
			}
		case "agents":
			p := at(path, "agents")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Agents = list
			}
		case "budgets":
			p := at(path, "budgets")
			if e, ok := decodeAgentBudgets(d, p, props[key]); ok {
				out.Budgets = &e
			}
		case "permissions":
			p := at(path, "permissions")
			if e, ok := decodeAgentPermissions(d, p, props[key]); ok {
				out.Permissions = &e
			}
		case "subagentOnly":
			p := at(path, "subagentOnly")
			if e, ok := d.flag(p, props[key]); ok {
				out.SubagentOnly = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/agent")
		}
	}
	return out, true
}

// Encode is Agent as the properties map holds it, and DecodeAgent's exact
// inverse: a nil pointer, a nil slice and a nil map each omit their key, so
// absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *Agent) Encode() map[string]any {
	out := map[string]any{}
	if v.Version != nil {
		out["version"] = *v.Version
	}
	if v.Authority != nil {
		out["authority"] = *v.Authority
	}
	if v.Description != nil {
		out["description"] = *v.Description
	}
	if v.Prompt != nil {
		out["prompt"] = *v.Prompt
	}
	if v.Provider != nil {
		out["provider"] = *v.Provider
	}
	if v.Model != nil {
		out["model"] = *v.Model
	}
	if v.Params != nil {
		out["params"] = v.Params.Encode()
	}
	if v.Tools != nil {
		items := make([]any, 0, len(v.Tools))
		for i := range v.Tools {
			items = append(items, v.Tools[i].Encode())
		}
		out["tools"] = items
	}
	if v.Agents != nil {
		items := make([]any, 0, len(v.Agents))
		for i := range v.Agents {
			items = append(items, v.Agents[i])
		}
		out["agents"] = items
	}
	if v.Budgets != nil {
		out["budgets"] = v.Budgets.Encode()
	}
	if v.Permissions != nil {
		out["permissions"] = v.Permissions.Encode()
	}
	if v.SubagentOnly != nil {
		out["subagentOnly"] = *v.SubagentOnly
	}
	return out
}

// AgentParams is one value of the `params` object declared on
// core.substrate.reamde.dev/agent.
//
// this agent's request knobs; the provider row's defaults sit under them
type AgentParams struct {
	// Temperature is the sampling temperature, when the model accepts one.
	Temperature *float64

	// MaxTokens is the completion cap sent on every request.
	MaxTokens *int64
}

// decodeAgentParams decodes one AgentParams value at path.
func decodeAgentParams(d *decoder, path string, v any) (AgentParams, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return AgentParams{}, false
	}
	var out AgentParams
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "temperature":
			p := at(path, "temperature")
			if e, ok := d.number(p, props[key], Bounds{}); ok {
				out.Temperature = &e
			}
		case "maxTokens":
			p := at(path, "maxTokens")
			if e, ok := d.integer(p, props[key], Bounds{Min: bound(1)}); ok {
				out.MaxTokens = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/agent")
		}
	}
	return out, true
}

// Encode is AgentParams as the properties map holds it, and
// decodeAgentParams's exact inverse: a nil pointer, a nil slice and a nil map
// each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *AgentParams) Encode() map[string]any {
	out := map[string]any{}
	if v.Temperature != nil {
		out["temperature"] = *v.Temperature
	}
	if v.MaxTokens != nil {
		out["maxTokens"] = *v.MaxTokens
	}
	return out
}

// AgentTools is one value of the `tools` object declared on
// core.substrate.reamde.dev/agent.
//
// what the model may call, in declaration order
type AgentTools struct {
	// Callable is the function identity this entry names. Names a function in
	// the registry.
	Callable *string

	// Name is the model-facing tool name, aliasing a callable.
	Name *string

	// Description is the model-facing card, overriding the callable's own.
	Description *string
}

// AgentToolsRequired names the properties the declaration marks `required:`,
// sorted. It is a FORM-LEVEL contract: the write path does not enforce it, so
// Decode admits a value that leaves one absent and this is what a client
// checks before it submits one.
var AgentToolsRequired = []string{"callable"}

// Missing names the required properties this value leaves absent, in
// declaration order. Empty means every declared requirement is answered —
// not that the value is admissible, which is the substrate's answer and not a
// type's.
func (v *AgentTools) Missing() []string {
	var out []string
	if v.Callable == nil {
		out = append(out, "callable")
	}
	return out
}

// decodeAgentTools decodes one AgentTools value at path.
func decodeAgentTools(d *decoder, path string, v any) (AgentTools, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return AgentTools{}, false
	}
	var out AgentTools
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "callable":
			p := at(path, "callable")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Callable = &e
			}
		case "name":
			p := at(path, "name")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Name = &e
			}
		case "description":
			p := at(path, "description")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Description = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/agent")
		}
	}
	return out, true
}

// Encode is AgentTools as the properties map holds it, and decodeAgentTools's
// exact inverse: a nil pointer, a nil slice and a nil map each omit their key,
// so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *AgentTools) Encode() map[string]any {
	out := map[string]any{}
	if v.Callable != nil {
		out["callable"] = *v.Callable
	}
	if v.Name != nil {
		out["name"] = *v.Name
	}
	if v.Description != nil {
		out["description"] = *v.Description
	}
	return out
}

// AgentBudgets is one value of the `budgets` object declared on
// core.substrate.reamde.dev/agent.
//
// what bounds one invocation
type AgentBudgets struct {
	// MaxTurns is completions the loop may spend.
	MaxTurns *int64

	// MaxToolCalls is tool calls the loop may spend.
	MaxToolCalls *int64

	// DeadlineSeconds is wall clock for the whole invocation.
	DeadlineSeconds *int64

	// Depth is how deep the sub-agent chain below may go.
	Depth *int64
}

// decodeAgentBudgets decodes one AgentBudgets value at path.
func decodeAgentBudgets(d *decoder, path string, v any) (AgentBudgets, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return AgentBudgets{}, false
	}
	var out AgentBudgets
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "maxTurns":
			p := at(path, "maxTurns")
			if e, ok := d.integer(p, props[key], Bounds{Min: bound(1), Max: bound(64)}); ok {
				out.MaxTurns = &e
			}
		case "maxToolCalls":
			p := at(path, "maxToolCalls")
			if e, ok := d.integer(p, props[key], Bounds{Min: bound(1), Max: bound(256)}); ok {
				out.MaxToolCalls = &e
			}
		case "deadlineSeconds":
			p := at(path, "deadlineSeconds")
			if e, ok := d.integer(p, props[key], Bounds{Min: bound(1), Max: bound(600)}); ok {
				out.DeadlineSeconds = &e
			}
		case "depth":
			p := at(path, "depth")
			if e, ok := d.integer(p, props[key], Bounds{Min: bound(1), Max: bound(3)}); ok {
				out.Depth = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/agent")
		}
	}
	return out, true
}

// Encode is AgentBudgets as the properties map holds it, and
// decodeAgentBudgets's exact inverse: a nil pointer, a nil slice and a nil map
// each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *AgentBudgets) Encode() map[string]any {
	out := map[string]any{}
	if v.MaxTurns != nil {
		out["maxTurns"] = *v.MaxTurns
	}
	if v.MaxToolCalls != nil {
		out["maxToolCalls"] = *v.MaxToolCalls
	}
	if v.DeadlineSeconds != nil {
		out["deadlineSeconds"] = *v.DeadlineSeconds
	}
	if v.Depth != nil {
		out["depth"] = *v.Depth
	}
	return out
}

// AgentPermissions is one value of the `permissions` object declared on
// core.substrate.reamde.dev/agent.
//
// what this agent is allowed to do while it runs; leave a grant out and what
// it covers is refused
type AgentPermissions struct {
	// Reads is which record kinds this agent may read, and how much; leave it
	// out and the query tool is withheld.
	Reads *AgentPermissionsReads

	// Writes is which record kinds it may create or change, the change
	// requests it proposes among them. Names a kind in the registry.
	Writes []string
}

// decodeAgentPermissions decodes one AgentPermissions value at path.
func decodeAgentPermissions(d *decoder, path string, v any) (AgentPermissions, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return AgentPermissions{}, false
	}
	var out AgentPermissions
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "reads":
			p := at(path, "reads")
			if e, ok := decodeAgentPermissionsReads(d, p, props[key]); ok {
				out.Reads = &e
			}
		case "writes":
			p := at(path, "writes")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Writes = list
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/agent")
		}
	}
	return out, true
}

// Encode is AgentPermissions as the properties map holds it, and
// decodeAgentPermissions's exact inverse: a nil pointer, a nil slice and a nil
// map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *AgentPermissions) Encode() map[string]any {
	out := map[string]any{}
	if v.Reads != nil {
		out["reads"] = v.Reads.Encode()
	}
	if v.Writes != nil {
		items := make([]any, 0, len(v.Writes))
		for i := range v.Writes {
			items = append(items, v.Writes[i])
		}
		out["writes"] = items
	}
	return out
}

// AgentPermissionsReads is one value of the `permissions.reads` object
// declared on core.substrate.reamde.dev/agent.
//
// which record kinds this agent may read, and how much; leave it out and the
// query tool is withheld
type AgentPermissionsReads struct {
	// Kinds is the record kinds every read is held to. Names a kind in the
	// registry.
	Kinds []string

	// Budgets is how much one run may read.
	Budgets *AgentPermissionsReadsBudgets
}

// decodeAgentPermissionsReads decodes one AgentPermissionsReads value at path.
func decodeAgentPermissionsReads(d *decoder, path string, v any) (AgentPermissionsReads, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return AgentPermissionsReads{}, false
	}
	var out AgentPermissionsReads
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "kinds":
			p := at(path, "kinds")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Kinds = list
			}
		case "budgets":
			p := at(path, "budgets")
			if e, ok := decodeAgentPermissionsReadsBudgets(d, p, props[key]); ok {
				out.Budgets = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/agent")
		}
	}
	return out, true
}

// Encode is AgentPermissionsReads as the properties map holds it, and
// decodeAgentPermissionsReads's exact inverse: a nil pointer, a nil slice and
// a nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *AgentPermissionsReads) Encode() map[string]any {
	out := map[string]any{}
	if v.Kinds != nil {
		items := make([]any, 0, len(v.Kinds))
		for i := range v.Kinds {
			items = append(items, v.Kinds[i])
		}
		out["kinds"] = items
	}
	if v.Budgets != nil {
		out["budgets"] = v.Budgets.Encode()
	}
	return out
}

// AgentPermissionsReadsBudgets is one value of the `permissions.reads.budgets`
// object declared on core.substrate.reamde.dev/agent.
//
// how much one run may read
type AgentPermissionsReadsBudgets struct {
	// Calls is how many reads one run may make.
	Calls *int64

	// Rows is how many records one run may read.
	Rows *int64
}

// decodeAgentPermissionsReadsBudgets decodes one AgentPermissionsReadsBudgets value at path.
func decodeAgentPermissionsReadsBudgets(d *decoder, path string, v any) (AgentPermissionsReadsBudgets, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return AgentPermissionsReadsBudgets{}, false
	}
	var out AgentPermissionsReadsBudgets
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "calls":
			p := at(path, "calls")
			if e, ok := d.integer(p, props[key], Bounds{Min: bound(1), Max: bound(1000)}); ok {
				out.Calls = &e
			}
		case "rows":
			p := at(path, "rows")
			if e, ok := d.integer(p, props[key], Bounds{Min: bound(1), Max: bound(10000)}); ok {
				out.Rows = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/agent")
		}
	}
	return out, true
}

// Encode is AgentPermissionsReadsBudgets as the properties map holds it, and
// decodeAgentPermissionsReadsBudgets's exact inverse: a nil pointer, a nil
// slice and a nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *AgentPermissionsReadsBudgets) Encode() map[string]any {
	out := map[string]any{}
	if v.Calls != nil {
		out["calls"] = *v.Calls
	}
	if v.Rows != nil {
		out["rows"] = *v.Rows
	}
	return out
}
