// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// Blob is core.substrate.reamde.dev/blob as its declaration admits it.
//
// One content-addressed blob's manifest — digest, size, name and media type
// — while the bytes themselves live in the store behind /blobs. The digest
// is the id, so identical bytes always mint the same blob, and a blobref
// property elsewhere points at one.
type Blob struct {
	// Digest is the content hash, equal to this record's id.
	Digest *string

	// Size is the byte length of the stored content.
	Size *int64

	// Name is an optional display name, typically the filename the bytes
	// arrived as; never a path.
	Name *string

	// MimeType is the optional media type declared when the bytes were stored.
	MimeType *string

	// CreatedBy is the actor that stored the bytes, for provenance.
	CreatedBy *string

	// Status is pending until bytes land, then stored; failed on a rejected
	// store. A state is NOT stored in properties: it lives in the record's own
	// state column and moves by transition. See BlobStatus.
	Status *BlobStatus
}

// BlobStatus is the state of the `status` machine.
//
// A STATE IS NOT A PROPERTY VALUE: it lives in the record's own state column
// and moves by transition, never by assignment. The declared states, the
// initial one and the legal moves are the constants and tables here; the field
// on the properties struct carries what a read reported, which is why Decode
// admits the key and Properties writes it back.
//
// pending until bytes land, then stored; failed on a rejected store
type BlobStatus string

const (
	BlobStatusPending BlobStatus = "pending"
	BlobStatusStored  BlobStatus = "stored"
	BlobStatusFailed  BlobStatus = "failed"
)

// BlobStatusValues are the declared states in declaration order.
var BlobStatusValues = []string{"pending", "stored", "failed"}

// BlobStatusInitial is the state a creation is born into.
const BlobStatusInitial = BlobStatusPending

// BlobStatusTransitions are the declared moves, in declaration order. A move
// absent from this table is not performable: nothing else gates one, since a
// transition carries no guard.
var BlobStatusTransitions = []StateTransition{
	{From: "pending", To: "stored"},
	{From: "pending", To: "failed"},
	{From: "failed", To: "stored"},
}

// Valid reports whether v is one of the declared states.
func (v BlobStatus) Valid() bool { return Declared(BlobStatusValues, string(v)) }

// BlobStatusCanMove reports whether from -> to is a declared move of the
// `status` machine.
func BlobStatusCanMove(from, to BlobStatus) bool {
	for _, t := range BlobStatusTransitions {
		if t.From == string(from) && t.To == string(to) {
			return true
		}
	}
	return false
}

// BlobKeys is the admitted key set: every property
// core.substrate.reamde.dev/blob declares, sorted. A key outside it is refused
// by Decode, which is what replaces a hand-kept list of admitted keys in Go.
var BlobKeys = []string{"createdBy", "digest", "mimeType", "name", "size", "status"}

// DecodeBlob decodes a properties map into Blob, refusing what the declaration
// cannot hold: an undeclared key, a value of the wrong type, an enum or state
// outside its set, a number outside its declared range or beyond exact integer
// precision, a key breaking a keyed map's contract. The value is nil unless
// the problems are empty, so a half-decoded record can never reach a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — BlobRequired and Missing are where
// requiredness lives.
func DecodeBlob(props map[string]any) (*Blob, []Problem) {
	d := &decoder{}
	out, _ := decodeBlob(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeBlobStatus decodes a declared state of the `status` machine.
func decodeBlobStatus(d *decoder, path string, v any) (BlobStatus, bool) {
	s, ok := d.text(path, v, BlobStatusValues, nil)
	if !ok {
		return "", false
	}
	return BlobStatus(s), true
}

// decodeBlob decodes one Blob value at path.
func decodeBlob(d *decoder, path string, v any) (Blob, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return Blob{}, false
	}
	var out Blob
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "digest":
			p := at(path, "digest")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Digest = &e
			}
		case "size":
			p := at(path, "size")
			if e, ok := d.integer(p, props[key], Bounds{}); ok {
				out.Size = &e
			}
		case "name":
			p := at(path, "name")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Name = &e
			}
		case "mimeType":
			p := at(path, "mimeType")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.MimeType = &e
			}
		case "createdBy":
			p := at(path, "createdBy")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.CreatedBy = &e
			}
		case "status":
			p := at(path, "status")
			if e, ok := decodeBlobStatus(d, p, props[key]); ok {
				out.Status = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/blob")
		}
	}
	return out, true
}

// Encode is Blob as the properties map holds it, and DecodeBlob's exact
// inverse: a nil pointer, a nil slice and a nil map each omit their key, so
// absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *Blob) Encode() map[string]any {
	out := map[string]any{}
	if v.Digest != nil {
		out["digest"] = *v.Digest
	}
	if v.Size != nil {
		out["size"] = *v.Size
	}
	if v.Name != nil {
		out["name"] = *v.Name
	}
	if v.MimeType != nil {
		out["mimeType"] = *v.MimeType
	}
	if v.CreatedBy != nil {
		out["createdBy"] = *v.CreatedBy
	}
	if v.Status != nil {
		out["status"] = string(*v.Status)
	}
	return out
}
