// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// Bundle is core.substrate.reamde.dev/bundle as its declaration admits it.
//
// One installed bundle, the install unit. It names the authority the bundle
// owns and the exact closure it ships — kinds, record mappings, functions,
// agents and triggers — and carries the runtime state the lifecycle verbs
// own: disabled, uninstalled, purging.
type Bundle struct {
	// Version is this declaration's version. Managed: the engine stamps it, so
	// a supplied value does not decide it.
	Version *string

	// Authority is the authority the bundle owns; its first label is the
	// bundle's name.
	Authority *string

	// Description is what the bundle is for, read above its card.
	Description *string

	// Inputs is the bundle's named configuration needs, each naming a kind.
	// Its keys hold to the camel contract.
	Inputs map[string]BundleInputs

	// Installs is the exact identities the bundle ships into its authority.
	Installs []string

	// Requires is the authorities this closure declares against; an install
	// refuses while one is absent.
	Requires []string

	// Modules is the shared library modules the bundle's functions import.
	Modules map[string]string

	// Oauth2 is the bundle's trusted OAuth provider metadata, immutable at
	// runtime.
	Oauth2 *BundleOauth2

	// Disabled is set by the disable verb — execution stopped, reversible.
	// Managed: the engine stamps it, so a supplied value does not decide it.
	Disabled *bool

	// Uninstalled is set by the uninstall verb — runtime registration
	// removed, data stays; cleared by re-applying the closure. Managed: the
	// engine stamps it, so a supplied value does not decide it.
	Uninstalled *bool

	// Purging is set while a purge runs — enable refuses it; an interrupted
	// purge leaves it standing until a purge completes. Managed: the engine
	// stamps it, so a supplied value does not decide it.
	Purging *bool
}

// BundleKeys is the admitted key set: every property
// core.substrate.reamde.dev/bundle declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var BundleKeys = []string{"authority", "description", "disabled", "inputs", "installs", "modules", "oauth2", "purging", "requires", "uninstalled", "version"}

// DecodeBundle decodes a properties map into Bundle, refusing what the
// declaration cannot hold: an undeclared key, a value of the wrong type, an
// enum or state outside its set, a number outside its declared range or beyond
// exact integer precision, a key breaking a keyed map's contract. The value is
// nil unless the problems are empty, so a half-decoded record can never reach
// a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — BundleRequired and Missing are where
// requiredness lives.
func DecodeBundle(props map[string]any) (*Bundle, []Problem) {
	d := &decoder{}
	out, _ := decodeBundle(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// BundleRequired names the properties the declaration marks `required:`,
// sorted. It is a FORM-LEVEL contract: the write path does not enforce it, so
// Decode admits a value that leaves one absent and this is what a client
// checks before it submits one.
var BundleRequired = []string{"authority"}

// Missing names the required properties this value leaves absent, in
// declaration order. Empty means every declared requirement is answered —
// not that the value is admissible, which is the substrate's answer and not a
// type's.
func (v *Bundle) Missing() []string {
	var out []string
	if v.Authority == nil {
		out = append(out, "authority")
	}
	return out
}

// decodeBundle decodes one Bundle value at path.
func decodeBundle(d *decoder, path string, v any) (Bundle, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return Bundle{}, false
	}
	var out Bundle
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "version":
			p := at(path, "version")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Version = &e
			}
		case "authority":
			p := at(path, "authority")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Authority = &e
			}
		case "description":
			p := at(path, "description")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Description = &e
			}
		case "inputs":
			p := at(path, "inputs")
			if entries, isMap := d.mapping(p, props[key]); isMap {
				values := make(map[string]BundleInputs, len(entries))
				for _, mk := range sortedKeys(entries) {
					if entries[mk] == nil || !d.key(p, mk, "camel") {
						continue
					}
					if e, ok := decodeBundleInputs(d, at(p, mk), entries[mk]); ok {
						values[mk] = e
					}
				}
				out.Inputs = values
			}
		case "installs":
			p := at(path, "installs")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Installs = list
			}
		case "requires":
			p := at(path, "requires")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Requires = list
			}
		case "modules":
			p := at(path, "modules")
			if entries, isMap := d.mapping(p, props[key]); isMap {
				values := make(map[string]string, len(entries))
				for _, mk := range sortedKeys(entries) {
					if entries[mk] == nil || !d.key(p, mk, "") {
						continue
					}
					if e, ok := d.text(at(p, mk), entries[mk], nil, nil); ok {
						values[mk] = e
					}
				}
				out.Modules = values
			}
		case "oauth2":
			p := at(path, "oauth2")
			if e, ok := decodeBundleOauth2(d, p, props[key]); ok {
				out.Oauth2 = &e
			}
		case "disabled":
			p := at(path, "disabled")
			if e, ok := d.flag(p, props[key]); ok {
				out.Disabled = &e
			}
		case "uninstalled":
			p := at(path, "uninstalled")
			if e, ok := d.flag(p, props[key]); ok {
				out.Uninstalled = &e
			}
		case "purging":
			p := at(path, "purging")
			if e, ok := d.flag(p, props[key]); ok {
				out.Purging = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/bundle")
		}
	}
	return out, true
}

// Encode is Bundle as the properties map holds it, and DecodeBundle's exact
// inverse: a nil pointer, a nil slice and a nil map each omit their key, so
// absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *Bundle) Encode() map[string]any {
	out := map[string]any{}
	if v.Version != nil {
		out["version"] = *v.Version
	}
	if v.Authority != nil {
		out["authority"] = *v.Authority
	}
	if v.Description != nil {
		out["description"] = *v.Description
	}
	if v.Inputs != nil {
		values := make(map[string]any, len(v.Inputs))
		for key, item := range v.Inputs {
			values[key] = item.Encode()
		}
		out["inputs"] = values
	}
	if v.Installs != nil {
		items := make([]any, 0, len(v.Installs))
		for i := range v.Installs {
			items = append(items, v.Installs[i])
		}
		out["installs"] = items
	}
	if v.Requires != nil {
		items := make([]any, 0, len(v.Requires))
		for i := range v.Requires {
			items = append(items, v.Requires[i])
		}
		out["requires"] = items
	}
	if v.Modules != nil {
		values := make(map[string]any, len(v.Modules))
		for key, item := range v.Modules {
			values[key] = item
		}
		out["modules"] = values
	}
	if v.Oauth2 != nil {
		out["oauth2"] = v.Oauth2.Encode()
	}
	if v.Disabled != nil {
		out["disabled"] = *v.Disabled
	}
	if v.Uninstalled != nil {
		out["uninstalled"] = *v.Uninstalled
	}
	if v.Purging != nil {
		out["purging"] = *v.Purging
	}
	return out
}

// BundleInputs is one value of the `inputs` object declared on
// core.substrate.reamde.dev/bundle.
//
// the bundle's named configuration needs, each naming a kind
type BundleInputs struct {
	// Kind is the kind whose records satisfy this input. Points at
	// core.substrate.reamde.dev/kind.
	Kind *ReferencePath

	// Inject is the consumer the resolved record is handed to; absent means a
	// host facility reads it.
	Inject *BundleInputsInject

	// Description is what the input is for.
	Description *string
}

// BundleInputsInject is a declared enum: the admissible set, in declaration
// order.
//
// the consumer the resolved record is handed to; absent means a host facility
// reads it
type BundleInputsInject string

const (
	BundleInputsInjectFunctions BundleInputsInject = "functions"
)

// BundleInputsInjectValues are the declared values in declaration order, which
// is render order.
var BundleInputsInjectValues = []string{"functions"}

// Valid reports whether v is one of the declared values.
func (v BundleInputsInject) Valid() bool { return Declared(BundleInputsInjectValues, string(v)) }

// decodeBundleInputsInject decodes a declared BundleInputsInject value.
func decodeBundleInputsInject(d *decoder, path string, v any) (BundleInputsInject, bool) {
	s, ok := d.text(path, v, BundleInputsInjectValues, nil)
	if !ok {
		return "", false
	}
	return BundleInputsInject(s), true
}

// decodeBundleInputs decodes one BundleInputs value at path.
func decodeBundleInputs(d *decoder, path string, v any) (BundleInputs, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return BundleInputs{}, false
	}
	var out BundleInputs
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "kind":
			p := at(path, "kind")
			if e, ok := d.reference(p, props[key], "core.substrate.reamde.dev/kind"); ok {
				out.Kind = &e
			}
		case "inject":
			p := at(path, "inject")
			if e, ok := decodeBundleInputsInject(d, p, props[key]); ok {
				out.Inject = &e
			}
		case "description":
			p := at(path, "description")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Description = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/bundle")
		}
	}
	return out, true
}

// Encode is BundleInputs as the properties map holds it, and
// decodeBundleInputs's exact inverse: a nil pointer, a nil slice and a nil map
// each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *BundleInputs) Encode() map[string]any {
	out := map[string]any{}
	if v.Kind != nil {
		out["kind"] = string(*v.Kind)
	}
	if v.Inject != nil {
		out["inject"] = string(*v.Inject)
	}
	if v.Description != nil {
		out["description"] = *v.Description
	}
	return out
}

// BundleOauth2 is one value of the `oauth2` object declared on
// core.substrate.reamde.dev/bundle.
//
// the bundle's trusted OAuth provider metadata, immutable at runtime
type BundleOauth2 struct {
	// ClientInput is the input whose resolved record carries the OAuth client
	// credentials.
	ClientInput *string

	// AuthorizationEndpoint is where the user is sent to consent.
	AuthorizationEndpoint *string

	// TokenEndpoint is where a code and a refresh are exchanged.
	TokenEndpoint *string

	// RevocationEndpoint is where a credential is revoked on teardown, best
	// effort.
	RevocationEndpoint *string

	// EmailEndpoint is where the connected account's own address is read,
	// right after the exchange.
	EmailEndpoint *string

	// EmailProperty is the account property the derived address lands in.
	EmailProperty *string

	// FeatureScopes is which OAuth scopes each account toggle asks for. Its
	// keys hold to the camel contract.
	FeatureScopes map[string]BundleOauth2FeatureScopes
}

// decodeBundleOauth2 decodes one BundleOauth2 value at path.
func decodeBundleOauth2(d *decoder, path string, v any) (BundleOauth2, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return BundleOauth2{}, false
	}
	var out BundleOauth2
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "clientInput":
			p := at(path, "clientInput")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.ClientInput = &e
			}
		case "authorizationEndpoint":
			p := at(path, "authorizationEndpoint")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.AuthorizationEndpoint = &e
			}
		case "tokenEndpoint":
			p := at(path, "tokenEndpoint")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.TokenEndpoint = &e
			}
		case "revocationEndpoint":
			p := at(path, "revocationEndpoint")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.RevocationEndpoint = &e
			}
		case "emailEndpoint":
			p := at(path, "emailEndpoint")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.EmailEndpoint = &e
			}
		case "emailProperty":
			p := at(path, "emailProperty")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.EmailProperty = &e
			}
		case "featureScopes":
			p := at(path, "featureScopes")
			if entries, isMap := d.mapping(p, props[key]); isMap {
				values := make(map[string]BundleOauth2FeatureScopes, len(entries))
				for _, mk := range sortedKeys(entries) {
					if entries[mk] == nil || !d.key(p, mk, "camel") {
						continue
					}
					if e, ok := decodeBundleOauth2FeatureScopes(d, at(p, mk), entries[mk]); ok {
						values[mk] = e
					}
				}
				out.FeatureScopes = values
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/bundle")
		}
	}
	return out, true
}

// Encode is BundleOauth2 as the properties map holds it, and
// decodeBundleOauth2's exact inverse: a nil pointer, a nil slice and a nil map
// each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *BundleOauth2) Encode() map[string]any {
	out := map[string]any{}
	if v.ClientInput != nil {
		out["clientInput"] = *v.ClientInput
	}
	if v.AuthorizationEndpoint != nil {
		out["authorizationEndpoint"] = *v.AuthorizationEndpoint
	}
	if v.TokenEndpoint != nil {
		out["tokenEndpoint"] = *v.TokenEndpoint
	}
	if v.RevocationEndpoint != nil {
		out["revocationEndpoint"] = *v.RevocationEndpoint
	}
	if v.EmailEndpoint != nil {
		out["emailEndpoint"] = *v.EmailEndpoint
	}
	if v.EmailProperty != nil {
		out["emailProperty"] = *v.EmailProperty
	}
	if v.FeatureScopes != nil {
		values := make(map[string]any, len(v.FeatureScopes))
		for key, item := range v.FeatureScopes {
			values[key] = item.Encode()
		}
		out["featureScopes"] = values
	}
	return out
}

// BundleOauth2FeatureScopes is one value of the `oauth2.featureScopes` object
// declared on core.substrate.reamde.dev/bundle.
//
// which OAuth scopes each account toggle asks for
type BundleOauth2FeatureScopes struct {
	// Scopes is the scopes the toggle requests.
	Scopes []string
}

// decodeBundleOauth2FeatureScopes decodes one BundleOauth2FeatureScopes value at path.
func decodeBundleOauth2FeatureScopes(d *decoder, path string, v any) (BundleOauth2FeatureScopes, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return BundleOauth2FeatureScopes{}, false
	}
	var out BundleOauth2FeatureScopes
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "scopes":
			p := at(path, "scopes")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Scopes = list
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/bundle")
		}
	}
	return out, true
}

// Encode is BundleOauth2FeatureScopes as the properties map holds it, and
// decodeBundleOauth2FeatureScopes's exact inverse: a nil pointer, a nil slice
// and a nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *BundleOauth2FeatureScopes) Encode() map[string]any {
	out := map[string]any{}
	if v.Scopes != nil {
		items := make([]any, 0, len(v.Scopes))
		for i := range v.Scopes {
			items = append(items, v.Scopes[i])
		}
		out["scopes"] = items
	}
	return out
}
