// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// Bundle is core.substrate.reamde.dev/bundle as its declaration admits it.
//
// One installed bundle, the install unit. It names the authority the bundle
// owns and the exact closure it ships — kinds, record mappings, functions,
// agents and triggers — and carries the runtime state the lifecycle verbs
// own: disabled, uninstalled, purging.
type Bundle struct {
	// Version is this declaration's version.
	Version *string

	// Name is the bundle's name, the owned authority's first label.
	Name *string

	// Authority is the authority the bundle owns
	// ("<name>.bundles.substrate.reamde.dev").
	Authority *string

	// Definition is the parsed manifest data, installs closure included.
	Definition Dynamic

	// Disabled is set by the disable verb — execution stopped, reversible.
	Disabled *bool

	// Uninstalled is set by the uninstall verb — runtime registration
	// removed, data stays; cleared by re-applying the closure.
	Uninstalled *bool

	// Purging is set while a purge runs — enable refuses it; an interrupted
	// purge leaves it standing until a purge completes.
	Purging *bool
}

// BundleKeys is the admitted key set: every property
// core.substrate.reamde.dev/bundle declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var BundleKeys = []string{"authority", "definition", "disabled", "name", "purging", "uninstalled", "version"}

// DecodeBundle decodes a properties map into Bundle, refusing what the
// declaration cannot hold: an undeclared key, a value of the wrong type, an
// enum or state outside its set, a number outside its declared range or beyond
// exact integer precision, a key breaking a keyed map's contract. The value is
// nil unless the problems are empty, so a half-decoded record can never reach
// a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — BundleRequired and Missing are where
// requiredness lives.
func DecodeBundle(props map[string]any) (*Bundle, []Problem) {
	d := &decoder{}
	out, _ := decodeBundle(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeBundle decodes one Bundle value at path.
func decodeBundle(d *decoder, path string, v any) (Bundle, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return Bundle{}, false
	}
	var out Bundle
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "version":
			p := at(path, "version")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Version = &e
			}
		case "name":
			p := at(path, "name")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Name = &e
			}
		case "authority":
			p := at(path, "authority")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Authority = &e
			}
		case "definition":
			p := at(path, "definition")
			if e, ok := d.dynamic(p, props[key]); ok {
				out.Definition = e
			}
		case "disabled":
			p := at(path, "disabled")
			if e, ok := d.flag(p, props[key]); ok {
				out.Disabled = &e
			}
		case "uninstalled":
			p := at(path, "uninstalled")
			if e, ok := d.flag(p, props[key]); ok {
				out.Uninstalled = &e
			}
		case "purging":
			p := at(path, "purging")
			if e, ok := d.flag(p, props[key]); ok {
				out.Purging = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/bundle")
		}
	}
	return out, true
}

// Properties is Bundle as the properties map holds it, and DecodeBundle's
// exact inverse: a nil pointer, a nil slice and a nil map each omit their key,
// so absence survives the round trip.
func (v *Bundle) Properties() map[string]any {
	out := map[string]any{}
	if v.Version != nil {
		out["version"] = *v.Version
	}
	if v.Name != nil {
		out["name"] = *v.Name
	}
	if v.Authority != nil {
		out["authority"] = *v.Authority
	}
	if v.Definition != nil {
		out["definition"] = v.Definition
	}
	if v.Disabled != nil {
		out["disabled"] = *v.Disabled
	}
	if v.Uninstalled != nil {
		out["uninstalled"] = *v.Uninstalled
	}
	if v.Purging != nil {
		out["purging"] = *v.Purging
	}
	return out
}
