// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// Credential is core.substrate.reamde.dev/credential as its declaration admits
// it.
//
// The user's one login credential, id `self`: a username and sealed-store refs
// to the password hash and the TOTP seed, never the material itself. Only the
// auth endpoints write it, so the changelog records that it changed without
// recording anything crackable.
type Credential struct {
	// Username is the user this credential admits; immutable in v1.
	Username *string

	// PasswordRef is the sealed-store ref holding the argon2id password hash.
	PasswordRef *SecretRef

	// TotpRef is the sealed-store ref holding the TOTP seed and its last
	// consumed step.
	TotpRef *SecretRef
}

// CredentialKeys is the admitted key set: every property
// core.substrate.reamde.dev/credential declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var CredentialKeys = []string{"passwordRef", "totpRef", "username"}

// DecodeCredential decodes a properties map into Credential, refusing what the
// declaration cannot hold: an undeclared key, a value of the wrong type, an
// enum or state outside its set, a number outside its declared range or beyond
// exact integer precision, a key breaking a keyed map's contract. The value is
// nil unless the problems are empty, so a half-decoded record can never reach
// a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — CredentialRequired and Missing are where
// requiredness lives.
func DecodeCredential(props map[string]any) (*Credential, []Problem) {
	d := &decoder{}
	out, _ := decodeCredential(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeCredential decodes one Credential value at path.
func decodeCredential(d *decoder, path string, v any) (Credential, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return Credential{}, false
	}
	var out Credential
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "username":
			p := at(path, "username")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Username = &e
			}
		case "passwordRef":
			p := at(path, "passwordRef")
			if e, ok := d.secret(p, props[key]); ok {
				out.PasswordRef = &e
			}
		case "totpRef":
			p := at(path, "totpRef")
			if e, ok := d.secret(p, props[key]); ok {
				out.TotpRef = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/credential")
		}
	}
	return out, true
}

// Encode is Credential as the properties map holds it, and DecodeCredential's
// exact inverse: a nil pointer, a nil slice and a nil map each omit their key,
// so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *Credential) Encode() map[string]any {
	out := map[string]any{}
	if v.Username != nil {
		out["username"] = *v.Username
	}
	if v.PasswordRef != nil {
		out["passwordRef"] = string(*v.PasswordRef)
	}
	if v.TotpRef != nil {
		out["totpRef"] = string(*v.TotpRef)
	}
	return out
}
