// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// Function is core.substrate.reamde.dev/function as its declaration admits it.
//
// One declared function: a callable reaction to the substrate's own changes,
// invoked by a trigger or called directly. The declaration IS the record — a
// write admits it, the commit activates it, and the dispatcher reads the
// registry this row rebuilds into.
type Function struct {
	// Version is this declaration's version.
	Version *string

	// Name is the function's local name.
	Name *string

	// Authority is the authority that declares it.
	Authority *string

	// Definition is the parsed manifest data, run arm included.
	Definition Dynamic
}

// FunctionKeys is the admitted key set: every property
// core.substrate.reamde.dev/function declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var FunctionKeys = []string{"authority", "definition", "name", "version"}

// DecodeFunction decodes a properties map into Function, refusing what the
// declaration cannot hold: an undeclared key, a value of the wrong type, an
// enum or state outside its set, a number outside its declared range or beyond
// exact integer precision, a key breaking a keyed map's contract. The value is
// nil unless the problems are empty, so a half-decoded record can never reach
// a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — FunctionRequired and Missing are where
// requiredness lives.
func DecodeFunction(props map[string]any) (*Function, []Problem) {
	d := &decoder{}
	out, _ := decodeFunction(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeFunction decodes one Function value at path.
func decodeFunction(d *decoder, path string, v any) (Function, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return Function{}, false
	}
	var out Function
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "version":
			p := at(path, "version")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Version = &e
			}
		case "name":
			p := at(path, "name")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Name = &e
			}
		case "authority":
			p := at(path, "authority")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Authority = &e
			}
		case "definition":
			p := at(path, "definition")
			if e, ok := d.dynamic(p, props[key]); ok {
				out.Definition = e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/function")
		}
	}
	return out, true
}

// Properties is Function as the properties map holds it, and DecodeFunction's
// exact inverse: a nil pointer, a nil slice and a nil map each omit their key,
// so absence survives the round trip.
func (v *Function) Properties() map[string]any {
	out := map[string]any{}
	if v.Version != nil {
		out["version"] = *v.Version
	}
	if v.Name != nil {
		out["name"] = *v.Name
	}
	if v.Authority != nil {
		out["authority"] = *v.Authority
	}
	if v.Definition != nil {
		out["definition"] = v.Definition
	}
	return out
}
