// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// Function is core.substrate.reamde.dev/function as its declaration admits it.
//
// One declared function: a callable reaction to the substrate's own changes,
// invoked by a trigger or called directly. The declaration IS the record — a
// write admits it, the commit activates it, and the dispatcher reads the
// registry this row rebuilds into.
type Function struct {
	// Version is this declaration's version. Managed: the engine stamps it, so
	// a supplied value does not decide it.
	Version *string

	// Authority is the authority that declares it.
	Authority *string

	// Description is the model-facing tool card — what this function does.
	Description *string

	// Runtime is the language the inline body is written in, or host for a
	// built-in.
	Runtime *FunctionRuntime

	// Source is the inline body, on an inline runtime.
	Source *string

	// TimeoutMs is what bounds one invocation's wall clock.
	TimeoutMs *int64

	// Arguments is the named arguments a call carries, in declaration order.
	Arguments []FunctionArguments

	// Returns is the named values the body returns.
	Returns []FunctionReturns

	// Permissions is what this function is allowed to do while it runs; leave
	// a grant out and what it covers is refused.
	Permissions *FunctionPermissions
}

// FunctionRuntime is a declared enum: the admissible set, in declaration
// order.
//
// the language the inline body is written in, or host for a built-in
type FunctionRuntime string

const (
	FunctionRuntimePython FunctionRuntime = "python"
	FunctionRuntimeGo     FunctionRuntime = "go"
	FunctionRuntimeHost   FunctionRuntime = "host"
)

// FunctionRuntimeValues are the declared values in declaration order, which is
// render order.
var FunctionRuntimeValues = []string{"python", "go", "host"}

// Valid reports whether v is one of the declared values.
func (v FunctionRuntime) Valid() bool { return Declared(FunctionRuntimeValues, string(v)) }

// FunctionKeys is the admitted key set: every property
// core.substrate.reamde.dev/function declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var FunctionKeys = []string{"arguments", "authority", "description", "permissions", "returns", "runtime", "source", "timeoutMs", "version"}

// DecodeFunction decodes a properties map into Function, refusing what the
// declaration cannot hold: an undeclared key, a value of the wrong type, an
// enum or state outside its set, a number outside its declared range or beyond
// exact integer precision, a key breaking a keyed map's contract. The value is
// nil unless the problems are empty, so a half-decoded record can never reach
// a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — FunctionRequired and Missing are where
// requiredness lives.
func DecodeFunction(props map[string]any) (*Function, []Problem) {
	d := &decoder{}
	out, _ := decodeFunction(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// FunctionRequired names the properties the declaration marks `required:`,
// sorted. It is a FORM-LEVEL contract: the write path does not enforce it, so
// Decode admits a value that leaves one absent and this is what a client
// checks before it submits one.
var FunctionRequired = []string{"authority", "description", "runtime"}

// Missing names the required properties this value leaves absent, in
// declaration order. Empty means every declared requirement is answered —
// not that the value is admissible, which is the substrate's answer and not a
// type's.
func (v *Function) Missing() []string {
	var out []string
	if v.Authority == nil {
		out = append(out, "authority")
	}
	if v.Description == nil {
		out = append(out, "description")
	}
	if v.Runtime == nil {
		out = append(out, "runtime")
	}
	return out
}

// decodeFunctionRuntime decodes a declared FunctionRuntime value.
func decodeFunctionRuntime(d *decoder, path string, v any) (FunctionRuntime, bool) {
	s, ok := d.text(path, v, FunctionRuntimeValues, nil)
	if !ok {
		return "", false
	}
	return FunctionRuntime(s), true
}

// decodeFunction decodes one Function value at path.
func decodeFunction(d *decoder, path string, v any) (Function, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return Function{}, false
	}
	var out Function
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "version":
			p := at(path, "version")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Version = &e
			}
		case "authority":
			p := at(path, "authority")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Authority = &e
			}
		case "description":
			p := at(path, "description")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Description = &e
			}
		case "runtime":
			p := at(path, "runtime")
			if e, ok := decodeFunctionRuntime(d, p, props[key]); ok {
				out.Runtime = &e
			}
		case "source":
			p := at(path, "source")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Source = &e
			}
		case "timeoutMs":
			p := at(path, "timeoutMs")
			if e, ok := d.integer(p, props[key], Bounds{Min: bound(1), Max: bound(60000)}); ok {
				out.TimeoutMs = &e
			}
		case "arguments":
			p := at(path, "arguments")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]FunctionArguments, 0, len(items))
				for i, item := range items {
					if e, ok := decodeFunctionArguments(d, index(p, i), item); ok {
						list = append(list, e)
					}
				}
				out.Arguments = list
			}
		case "returns":
			p := at(path, "returns")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]FunctionReturns, 0, len(items))
				for i, item := range items {
					if e, ok := decodeFunctionReturns(d, index(p, i), item); ok {
						list = append(list, e)
					}
				}
				out.Returns = list
			}
		case "permissions":
			p := at(path, "permissions")
			if e, ok := decodeFunctionPermissions(d, p, props[key]); ok {
				out.Permissions = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/function")
		}
	}
	return out, true
}

// Encode is Function as the properties map holds it, and DecodeFunction's
// exact inverse: a nil pointer, a nil slice and a nil map each omit their key,
// so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *Function) Encode() map[string]any {
	out := map[string]any{}
	if v.Version != nil {
		out["version"] = *v.Version
	}
	if v.Authority != nil {
		out["authority"] = *v.Authority
	}
	if v.Description != nil {
		out["description"] = *v.Description
	}
	if v.Runtime != nil {
		out["runtime"] = string(*v.Runtime)
	}
	if v.Source != nil {
		out["source"] = *v.Source
	}
	if v.TimeoutMs != nil {
		out["timeoutMs"] = *v.TimeoutMs
	}
	if v.Arguments != nil {
		items := make([]any, 0, len(v.Arguments))
		for i := range v.Arguments {
			items = append(items, v.Arguments[i].Encode())
		}
		out["arguments"] = items
	}
	if v.Returns != nil {
		items := make([]any, 0, len(v.Returns))
		for i := range v.Returns {
			items = append(items, v.Returns[i].Encode())
		}
		out["returns"] = items
	}
	if v.Permissions != nil {
		out["permissions"] = v.Permissions.Encode()
	}
	return out
}

// FunctionArguments is one value of the `arguments` object declared on
// core.substrate.reamde.dev/function.
//
// the named arguments a call carries, in declaration order
type FunctionArguments struct {
	// Name is the argument's name.
	Name *string

	// Type is what the value is.
	Type *FunctionArgumentsType

	// Repeated is a list of the declared type.
	Repeated *bool

	// Required is a call without it is refused.
	Required *bool

	// Description is what the argument is for, as the model reads it.
	Description *string

	// Values is the admitted values, on an enum.
	Values []string
}

// FunctionArgumentsType is a declared enum: the admissible set, in declaration
// order.
//
// what the value is
type FunctionArgumentsType string

const (
	FunctionArgumentsTypeString FunctionArgumentsType = "string"
	FunctionArgumentsTypeInt    FunctionArgumentsType = "int"
	FunctionArgumentsTypeFloat  FunctionArgumentsType = "float"
	FunctionArgumentsTypeBool   FunctionArgumentsType = "bool"
	FunctionArgumentsTypeEnum   FunctionArgumentsType = "enum"
	FunctionArgumentsTypeJson   FunctionArgumentsType = "json"
)

// FunctionArgumentsTypeValues are the declared values in declaration order,
// which is render order.
var FunctionArgumentsTypeValues = []string{"string", "int", "float", "bool", "enum", "json"}

// Valid reports whether v is one of the declared values.
func (v FunctionArgumentsType) Valid() bool { return Declared(FunctionArgumentsTypeValues, string(v)) }

// FunctionArgumentsRequired names the properties the declaration marks
// `required:`, sorted. It is a FORM-LEVEL contract: the write path does not
// enforce it, so Decode admits a value that leaves one absent and this is what
// a client checks before it submits one.
var FunctionArgumentsRequired = []string{"name"}

// Missing names the required properties this value leaves absent, in
// declaration order. Empty means every declared requirement is answered —
// not that the value is admissible, which is the substrate's answer and not a
// type's.
func (v *FunctionArguments) Missing() []string {
	var out []string
	if v.Name == nil {
		out = append(out, "name")
	}
	return out
}

// decodeFunctionArgumentsType decodes a declared FunctionArgumentsType value.
func decodeFunctionArgumentsType(d *decoder, path string, v any) (FunctionArgumentsType, bool) {
	s, ok := d.text(path, v, FunctionArgumentsTypeValues, nil)
	if !ok {
		return "", false
	}
	return FunctionArgumentsType(s), true
}

// decodeFunctionArguments decodes one FunctionArguments value at path.
func decodeFunctionArguments(d *decoder, path string, v any) (FunctionArguments, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return FunctionArguments{}, false
	}
	var out FunctionArguments
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "name":
			p := at(path, "name")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Name = &e
			}
		case "type":
			p := at(path, "type")
			if e, ok := decodeFunctionArgumentsType(d, p, props[key]); ok {
				out.Type = &e
			}
		case "repeated":
			p := at(path, "repeated")
			if e, ok := d.flag(p, props[key]); ok {
				out.Repeated = &e
			}
		case "required":
			p := at(path, "required")
			if e, ok := d.flag(p, props[key]); ok {
				out.Required = &e
			}
		case "description":
			p := at(path, "description")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Description = &e
			}
		case "values":
			p := at(path, "values")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Values = list
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/function")
		}
	}
	return out, true
}

// Encode is FunctionArguments as the properties map holds it, and
// decodeFunctionArguments's exact inverse: a nil pointer, a nil slice and a
// nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *FunctionArguments) Encode() map[string]any {
	out := map[string]any{}
	if v.Name != nil {
		out["name"] = *v.Name
	}
	if v.Type != nil {
		out["type"] = string(*v.Type)
	}
	if v.Repeated != nil {
		out["repeated"] = *v.Repeated
	}
	if v.Required != nil {
		out["required"] = *v.Required
	}
	if v.Description != nil {
		out["description"] = *v.Description
	}
	if v.Values != nil {
		items := make([]any, 0, len(v.Values))
		for i := range v.Values {
			items = append(items, v.Values[i])
		}
		out["values"] = items
	}
	return out
}

// FunctionReturns is one value of the `returns` object declared on
// core.substrate.reamde.dev/function.
//
// the named values the body returns
type FunctionReturns struct {
	// Name is the value's name.
	Name *string

	// Type is what the value is.
	Type *FunctionReturnsType

	// Repeated is a list of the declared type.
	Repeated *bool

	// Required is the body always returns it.
	Required *bool

	// Description is what the value carries, as the model reads it.
	Description *string

	// Values is the admitted values, on an enum.
	Values []string
}

// FunctionReturnsType is a declared enum: the admissible set, in declaration
// order.
//
// what the value is
type FunctionReturnsType string

const (
	FunctionReturnsTypeString FunctionReturnsType = "string"
	FunctionReturnsTypeInt    FunctionReturnsType = "int"
	FunctionReturnsTypeFloat  FunctionReturnsType = "float"
	FunctionReturnsTypeBool   FunctionReturnsType = "bool"
	FunctionReturnsTypeEnum   FunctionReturnsType = "enum"
	FunctionReturnsTypeJson   FunctionReturnsType = "json"
)

// FunctionReturnsTypeValues are the declared values in declaration order,
// which is render order.
var FunctionReturnsTypeValues = []string{"string", "int", "float", "bool", "enum", "json"}

// Valid reports whether v is one of the declared values.
func (v FunctionReturnsType) Valid() bool { return Declared(FunctionReturnsTypeValues, string(v)) }

// FunctionReturnsRequired names the properties the declaration marks
// `required:`, sorted. It is a FORM-LEVEL contract: the write path does not
// enforce it, so Decode admits a value that leaves one absent and this is what
// a client checks before it submits one.
var FunctionReturnsRequired = []string{"name"}

// Missing names the required properties this value leaves absent, in
// declaration order. Empty means every declared requirement is answered —
// not that the value is admissible, which is the substrate's answer and not a
// type's.
func (v *FunctionReturns) Missing() []string {
	var out []string
	if v.Name == nil {
		out = append(out, "name")
	}
	return out
}

// decodeFunctionReturnsType decodes a declared FunctionReturnsType value.
func decodeFunctionReturnsType(d *decoder, path string, v any) (FunctionReturnsType, bool) {
	s, ok := d.text(path, v, FunctionReturnsTypeValues, nil)
	if !ok {
		return "", false
	}
	return FunctionReturnsType(s), true
}

// decodeFunctionReturns decodes one FunctionReturns value at path.
func decodeFunctionReturns(d *decoder, path string, v any) (FunctionReturns, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return FunctionReturns{}, false
	}
	var out FunctionReturns
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "name":
			p := at(path, "name")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Name = &e
			}
		case "type":
			p := at(path, "type")
			if e, ok := decodeFunctionReturnsType(d, p, props[key]); ok {
				out.Type = &e
			}
		case "repeated":
			p := at(path, "repeated")
			if e, ok := d.flag(p, props[key]); ok {
				out.Repeated = &e
			}
		case "required":
			p := at(path, "required")
			if e, ok := d.flag(p, props[key]); ok {
				out.Required = &e
			}
		case "description":
			p := at(path, "description")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Description = &e
			}
		case "values":
			p := at(path, "values")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Values = list
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/function")
		}
	}
	return out, true
}

// Encode is FunctionReturns as the properties map holds it, and
// decodeFunctionReturns's exact inverse: a nil pointer, a nil slice and a nil
// map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *FunctionReturns) Encode() map[string]any {
	out := map[string]any{}
	if v.Name != nil {
		out["name"] = *v.Name
	}
	if v.Type != nil {
		out["type"] = string(*v.Type)
	}
	if v.Repeated != nil {
		out["repeated"] = *v.Repeated
	}
	if v.Required != nil {
		out["required"] = *v.Required
	}
	if v.Description != nil {
		out["description"] = *v.Description
	}
	if v.Values != nil {
		items := make([]any, 0, len(v.Values))
		for i := range v.Values {
			items = append(items, v.Values[i])
		}
		out["values"] = items
	}
	return out
}

// FunctionPermissions is one value of the `permissions` object declared on
// core.substrate.reamde.dev/function.
//
// what this function is allowed to do while it runs; leave a grant out and
// what it covers is refused
type FunctionPermissions struct {
	// Reads is which record kinds this function may read while it runs, and
	// how much; leave it out and any read it attempts fails.
	Reads *FunctionPermissionsReads

	// Writes is which record kinds it may create or change. Names a kind in
	// the registry.
	Writes []string

	// Call is which other functions its code may invoke. Names a function in
	// the registry.
	Call []string

	// Network is the hosts it may reach; any entry grants network access, and
	// enforcement is all-or-nothing today.
	Network []string

	// Mutations is the identity-changing operations it may perform: merge,
	// split.
	Mutations []FunctionPermissionsMutations
}

// FunctionPermissionsMutations is a declared enum: the admissible set, in
// declaration order.
//
// the identity-changing operations it may perform: merge, split
type FunctionPermissionsMutations string

const (
	FunctionPermissionsMutationsMerge FunctionPermissionsMutations = "merge"
	FunctionPermissionsMutationsSplit FunctionPermissionsMutations = "split"
)

// FunctionPermissionsMutationsValues are the declared values in declaration
// order, which is render order.
var FunctionPermissionsMutationsValues = []string{"merge", "split"}

// Valid reports whether v is one of the declared values.
func (v FunctionPermissionsMutations) Valid() bool {
	return Declared(FunctionPermissionsMutationsValues, string(v))
}

// decodeFunctionPermissionsMutations decodes a declared FunctionPermissionsMutations value.
func decodeFunctionPermissionsMutations(d *decoder, path string, v any) (FunctionPermissionsMutations, bool) {
	s, ok := d.text(path, v, FunctionPermissionsMutationsValues, nil)
	if !ok {
		return "", false
	}
	return FunctionPermissionsMutations(s), true
}

// decodeFunctionPermissions decodes one FunctionPermissions value at path.
func decodeFunctionPermissions(d *decoder, path string, v any) (FunctionPermissions, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return FunctionPermissions{}, false
	}
	var out FunctionPermissions
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "reads":
			p := at(path, "reads")
			if e, ok := decodeFunctionPermissionsReads(d, p, props[key]); ok {
				out.Reads = &e
			}
		case "writes":
			p := at(path, "writes")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Writes = list
			}
		case "call":
			p := at(path, "call")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Call = list
			}
		case "network":
			p := at(path, "network")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Network = list
			}
		case "mutations":
			p := at(path, "mutations")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]FunctionPermissionsMutations, 0, len(items))
				for i, item := range items {
					if e, ok := decodeFunctionPermissionsMutations(d, index(p, i), item); ok {
						list = append(list, e)
					}
				}
				out.Mutations = list
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/function")
		}
	}
	return out, true
}

// Encode is FunctionPermissions as the properties map holds it, and
// decodeFunctionPermissions's exact inverse: a nil pointer, a nil slice and a
// nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *FunctionPermissions) Encode() map[string]any {
	out := map[string]any{}
	if v.Reads != nil {
		out["reads"] = v.Reads.Encode()
	}
	if v.Writes != nil {
		items := make([]any, 0, len(v.Writes))
		for i := range v.Writes {
			items = append(items, v.Writes[i])
		}
		out["writes"] = items
	}
	if v.Call != nil {
		items := make([]any, 0, len(v.Call))
		for i := range v.Call {
			items = append(items, v.Call[i])
		}
		out["call"] = items
	}
	if v.Network != nil {
		items := make([]any, 0, len(v.Network))
		for i := range v.Network {
			items = append(items, v.Network[i])
		}
		out["network"] = items
	}
	if v.Mutations != nil {
		items := make([]any, 0, len(v.Mutations))
		for i := range v.Mutations {
			items = append(items, string(v.Mutations[i]))
		}
		out["mutations"] = items
	}
	return out
}

// FunctionPermissionsReads is one value of the `permissions.reads` object
// declared on core.substrate.reamde.dev/function.
//
// which record kinds this function may read while it runs, and how much; leave
// it out and any read it attempts fails
type FunctionPermissionsReads struct {
	// Kinds is the record kinds every read is held to. Names a kind in the
	// registry.
	Kinds []string

	// Budgets is how much one run may read.
	Budgets *FunctionPermissionsReadsBudgets
}

// decodeFunctionPermissionsReads decodes one FunctionPermissionsReads value at path.
func decodeFunctionPermissionsReads(d *decoder, path string, v any) (FunctionPermissionsReads, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return FunctionPermissionsReads{}, false
	}
	var out FunctionPermissionsReads
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "kinds":
			p := at(path, "kinds")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Kinds = list
			}
		case "budgets":
			p := at(path, "budgets")
			if e, ok := decodeFunctionPermissionsReadsBudgets(d, p, props[key]); ok {
				out.Budgets = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/function")
		}
	}
	return out, true
}

// Encode is FunctionPermissionsReads as the properties map holds it, and
// decodeFunctionPermissionsReads's exact inverse: a nil pointer, a nil slice
// and a nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *FunctionPermissionsReads) Encode() map[string]any {
	out := map[string]any{}
	if v.Kinds != nil {
		items := make([]any, 0, len(v.Kinds))
		for i := range v.Kinds {
			items = append(items, v.Kinds[i])
		}
		out["kinds"] = items
	}
	if v.Budgets != nil {
		out["budgets"] = v.Budgets.Encode()
	}
	return out
}

// FunctionPermissionsReadsBudgets is one value of the
// `permissions.reads.budgets` object declared on
// core.substrate.reamde.dev/function.
//
// how much one run may read
type FunctionPermissionsReadsBudgets struct {
	// Calls is how many reads one run may make.
	Calls *int64

	// Rows is how many records one run may read.
	Rows *int64
}

// decodeFunctionPermissionsReadsBudgets decodes one FunctionPermissionsReadsBudgets value at path.
func decodeFunctionPermissionsReadsBudgets(d *decoder, path string, v any) (FunctionPermissionsReadsBudgets, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return FunctionPermissionsReadsBudgets{}, false
	}
	var out FunctionPermissionsReadsBudgets
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "calls":
			p := at(path, "calls")
			if e, ok := d.integer(p, props[key], Bounds{Min: bound(1), Max: bound(1000)}); ok {
				out.Calls = &e
			}
		case "rows":
			p := at(path, "rows")
			if e, ok := d.integer(p, props[key], Bounds{Min: bound(1), Max: bound(10000)}); ok {
				out.Rows = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/function")
		}
	}
	return out, true
}

// Encode is FunctionPermissionsReadsBudgets as the properties map holds it,
// and decodeFunctionPermissionsReadsBudgets's exact inverse: a nil pointer, a
// nil slice and a nil map each omit their key, so absence survives the round
// trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *FunctionPermissionsReadsBudgets) Encode() map[string]any {
	out := map[string]any{}
	if v.Calls != nil {
		out["calls"] = *v.Calls
	}
	if v.Rows != nil {
		out["rows"] = *v.Rows
	}
	return out
}
