// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// Kind is core.substrate.reamde.dev/kind as its declaration admits it.
//
// One declared kind — what a record is, `{authority}/{name}`. The vocabulary
// browses through the same API as data, so every kind this repository holds is
// a row here, and these properties are what the engine validates every write
// against.
type Kind struct {
	// Version is this declaration's version. Managed: the engine stamps it, so
	// a supplied value does not decide it.
	Version *string

	// Source is builtin for seeded kinds, installed for bundle ones. Managed:
	// the engine stamps it, so a supplied value does not decide it.
	Source *KindSource

	// Authority is who publishes it; absent on a repository-local kind.
	Authority *string

	// Names is what one record is called, and what the collection is.
	Names *KindNames

	// Description is what this kind is for, read above its collection.
	Description *string

	// DisplayTemplate is how a record of this kind renders its title.
	DisplayTemplate *string

	// Traits is the traits this kind binds.
	Traits []string

	// Indices is the composite indexes this kind asks for.
	Indices []KindIndices

	// Edges is the named, directed links a record of this kind may hold. Its
	// keys hold to the camel contract.
	Edges map[string]KindEdges

	// Properties is the declared value slots a record of this kind carries, as
	// the loader admits them.
	Properties Dynamic
}

// KindSource is a declared enum: the admissible set, in declaration order.
//
// builtin for seeded kinds, installed for bundle ones
type KindSource string

const (
	KindSourceBuiltin   KindSource = "builtin"
	KindSourceInstalled KindSource = "installed"
)

// KindSourceValues are the declared values in declaration order, which is
// render order.
var KindSourceValues = []string{"builtin", "installed"}

// Valid reports whether v is one of the declared values.
func (v KindSource) Valid() bool { return Declared(KindSourceValues, string(v)) }

// KindKeys is the admitted key set: every property
// core.substrate.reamde.dev/kind declares, sorted. A key outside it is refused
// by Decode, which is what replaces a hand-kept list of admitted keys in Go.
var KindKeys = []string{"authority", "description", "displayTemplate", "edges", "indices", "names", "properties", "source", "traits", "version"}

// DecodeKind decodes a properties map into Kind, refusing what the declaration
// cannot hold: an undeclared key, a value of the wrong type, an enum or state
// outside its set, a number outside its declared range or beyond exact integer
// precision, a key breaking a keyed map's contract. The value is nil unless
// the problems are empty, so a half-decoded record can never reach a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — KindRequired and Missing are where
// requiredness lives.
func DecodeKind(props map[string]any) (*Kind, []Problem) {
	d := &decoder{}
	out, _ := decodeKind(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// KindRequired names the properties the declaration marks `required:`, sorted.
// It is a FORM-LEVEL contract: the write path does not enforce it, so Decode
// admits a value that leaves one absent and this is what a client checks
// before it submits one.
var KindRequired = []string{"authority"}

// Missing names the required properties this value leaves absent, in
// declaration order. Empty means every declared requirement is answered —
// not that the value is admissible, which is the substrate's answer and not a
// type's.
func (v *Kind) Missing() []string {
	var out []string
	if v.Authority == nil {
		out = append(out, "authority")
	}
	return out
}

// decodeKindSource decodes a declared KindSource value.
func decodeKindSource(d *decoder, path string, v any) (KindSource, bool) {
	s, ok := d.text(path, v, KindSourceValues, nil)
	if !ok {
		return "", false
	}
	return KindSource(s), true
}

// decodeKind decodes one Kind value at path.
func decodeKind(d *decoder, path string, v any) (Kind, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return Kind{}, false
	}
	var out Kind
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "version":
			p := at(path, "version")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Version = &e
			}
		case "source":
			p := at(path, "source")
			if e, ok := decodeKindSource(d, p, props[key]); ok {
				out.Source = &e
			}
		case "authority":
			p := at(path, "authority")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Authority = &e
			}
		case "names":
			p := at(path, "names")
			if e, ok := decodeKindNames(d, p, props[key]); ok {
				out.Names = &e
			}
		case "description":
			p := at(path, "description")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Description = &e
			}
		case "displayTemplate":
			p := at(path, "displayTemplate")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.DisplayTemplate = &e
			}
		case "traits":
			p := at(path, "traits")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Traits = list
			}
		case "indices":
			p := at(path, "indices")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]KindIndices, 0, len(items))
				for i, item := range items {
					if e, ok := decodeKindIndices(d, index(p, i), item); ok {
						list = append(list, e)
					}
				}
				out.Indices = list
			}
		case "edges":
			p := at(path, "edges")
			if entries, isMap := d.mapping(p, props[key]); isMap {
				values := make(map[string]KindEdges, len(entries))
				for _, mk := range sortedKeys(entries) {
					if entries[mk] == nil || !d.key(p, mk, "camel") {
						continue
					}
					if e, ok := decodeKindEdges(d, at(p, mk), entries[mk]); ok {
						values[mk] = e
					}
				}
				out.Edges = values
			}
		case "properties":
			p := at(path, "properties")
			if e, ok := d.dynamic(p, props[key]); ok {
				out.Properties = e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/kind")
		}
	}
	return out, true
}

// Encode is Kind as the properties map holds it, and DecodeKind's exact
// inverse: a nil pointer, a nil slice and a nil map each omit their key, so
// absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *Kind) Encode() map[string]any {
	out := map[string]any{}
	if v.Version != nil {
		out["version"] = *v.Version
	}
	if v.Source != nil {
		out["source"] = string(*v.Source)
	}
	if v.Authority != nil {
		out["authority"] = *v.Authority
	}
	if v.Names != nil {
		out["names"] = v.Names.Encode()
	}
	if v.Description != nil {
		out["description"] = *v.Description
	}
	if v.DisplayTemplate != nil {
		out["displayTemplate"] = *v.DisplayTemplate
	}
	if v.Traits != nil {
		items := make([]any, 0, len(v.Traits))
		for i := range v.Traits {
			items = append(items, v.Traits[i])
		}
		out["traits"] = items
	}
	if v.Indices != nil {
		items := make([]any, 0, len(v.Indices))
		for i := range v.Indices {
			items = append(items, v.Indices[i].Encode())
		}
		out["indices"] = items
	}
	if v.Edges != nil {
		values := make(map[string]any, len(v.Edges))
		for key, item := range v.Edges {
			values[key] = item.Encode()
		}
		out["edges"] = values
	}
	if v.Properties != nil {
		out["properties"] = v.Properties
	}
	return out
}

// KindNames is one value of the `names` object declared on
// core.substrate.reamde.dev/kind.
//
// what one record is called, and what the collection is
type KindNames struct {
	// Singular is the kind's singular name, its identity's last segment.
	Singular *string

	// Plural is the collection segment in a path, never auto-derived.
	Plural *string
}

// KindNamesRequired names the properties the declaration marks `required:`,
// sorted. It is a FORM-LEVEL contract: the write path does not enforce it, so
// Decode admits a value that leaves one absent and this is what a client
// checks before it submits one.
var KindNamesRequired = []string{"plural", "singular"}

// Missing names the required properties this value leaves absent, in
// declaration order. Empty means every declared requirement is answered —
// not that the value is admissible, which is the substrate's answer and not a
// type's.
func (v *KindNames) Missing() []string {
	var out []string
	if v.Singular == nil {
		out = append(out, "singular")
	}
	if v.Plural == nil {
		out = append(out, "plural")
	}
	return out
}

// decodeKindNames decodes one KindNames value at path.
func decodeKindNames(d *decoder, path string, v any) (KindNames, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return KindNames{}, false
	}
	var out KindNames
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "singular":
			p := at(path, "singular")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Singular = &e
			}
		case "plural":
			p := at(path, "plural")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Plural = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/kind")
		}
	}
	return out, true
}

// Encode is KindNames as the properties map holds it, and decodeKindNames's
// exact inverse: a nil pointer, a nil slice and a nil map each omit their key,
// so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *KindNames) Encode() map[string]any {
	out := map[string]any{}
	if v.Singular != nil {
		out["singular"] = *v.Singular
	}
	if v.Plural != nil {
		out["plural"] = *v.Plural
	}
	return out
}

// KindIndices is one value of the `indices` object declared on
// core.substrate.reamde.dev/kind.
//
// the composite indexes this kind asks for
type KindIndices struct {
	// Properties is the properties the index covers, in order.
	Properties []string
}

// decodeKindIndices decodes one KindIndices value at path.
func decodeKindIndices(d *decoder, path string, v any) (KindIndices, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return KindIndices{}, false
	}
	var out KindIndices
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "properties":
			p := at(path, "properties")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Properties = list
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/kind")
		}
	}
	return out, true
}

// Encode is KindIndices as the properties map holds it, and
// decodeKindIndices's exact inverse: a nil pointer, a nil slice and a nil map
// each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *KindIndices) Encode() map[string]any {
	out := map[string]any{}
	if v.Properties != nil {
		items := make([]any, 0, len(v.Properties))
		for i := range v.Properties {
			items = append(items, v.Properties[i])
		}
		out["properties"] = items
	}
	return out
}

// KindEdges is one value of the `edges` object declared on
// core.substrate.reamde.dev/kind.
//
// the named, directed links a record of this kind may hold
type KindEdges struct {
	// To is the target kind, or `any`. Names a kind in the registry.
	To *string

	// Many is several targets instead of one.
	Many *bool

	// Required is a creation without it is refused.
	Required *bool

	// OwnerRef is the target owns this record, so a cascade collects it.
	OwnerRef *bool

	// Description is what the link means.
	Description *string

	// Inverse is what the TARGET calls this relationship.
	Inverse *string

	// InverseDescription is what the inverse means, from the target's side.
	InverseDescription *string
}

// decodeKindEdges decodes one KindEdges value at path.
func decodeKindEdges(d *decoder, path string, v any) (KindEdges, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return KindEdges{}, false
	}
	var out KindEdges
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "to":
			p := at(path, "to")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.To = &e
			}
		case "many":
			p := at(path, "many")
			if e, ok := d.flag(p, props[key]); ok {
				out.Many = &e
			}
		case "required":
			p := at(path, "required")
			if e, ok := d.flag(p, props[key]); ok {
				out.Required = &e
			}
		case "ownerRef":
			p := at(path, "ownerRef")
			if e, ok := d.flag(p, props[key]); ok {
				out.OwnerRef = &e
			}
		case "description":
			p := at(path, "description")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Description = &e
			}
		case "inverse":
			p := at(path, "inverse")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Inverse = &e
			}
		case "inverseDescription":
			p := at(path, "inverseDescription")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.InverseDescription = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/kind")
		}
	}
	return out, true
}

// Encode is KindEdges as the properties map holds it, and decodeKindEdges's
// exact inverse: a nil pointer, a nil slice and a nil map each omit their key,
// so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *KindEdges) Encode() map[string]any {
	out := map[string]any{}
	if v.To != nil {
		out["to"] = *v.To
	}
	if v.Many != nil {
		out["many"] = *v.Many
	}
	if v.Required != nil {
		out["required"] = *v.Required
	}
	if v.OwnerRef != nil {
		out["ownerRef"] = *v.OwnerRef
	}
	if v.Description != nil {
		out["description"] = *v.Description
	}
	if v.Inverse != nil {
		out["inverse"] = *v.Inverse
	}
	if v.InverseDescription != nil {
		out["inverseDescription"] = *v.InverseDescription
	}
	return out
}
