// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// Kind is core.substrate.reamde.dev/kind as its declaration admits it.
//
// One declared kind — what a record is, `{authority}/{name}`. The vocabulary
// browses through the same API as data, so every kind this repository holds is
// a row here, and its `definition` is what the engine validates every write
// against.
type Kind struct {
	// Name is the kind's singular name.
	Name *string

	// Authority is who publishes it; absent on a repository-local kind.
	Authority *string

	// Version is this declaration's version.
	Version *string

	// Plural is the collection segment.
	Plural *string

	// Source is builtin for seeded kinds, installed for bundle ones.
	Source *KindSource

	// Definition is the parsed data map, exactly as authored — descriptions
	// included.
	Definition Dynamic
}

// KindSource is a declared enum: the admissible set, in declaration order.
//
// builtin for seeded kinds, installed for bundle ones
type KindSource string

const (
	KindSourceBuiltin   KindSource = "builtin"
	KindSourceInstalled KindSource = "installed"
)

// KindSourceValues are the declared values in declaration order, which is
// render order.
var KindSourceValues = []string{"builtin", "installed"}

// Valid reports whether v is one of the declared values.
func (v KindSource) Valid() bool { return Declared(KindSourceValues, string(v)) }

// KindKeys is the admitted key set: every property
// core.substrate.reamde.dev/kind declares, sorted. A key outside it is refused
// by Decode, which is what replaces a hand-kept list of admitted keys in Go.
var KindKeys = []string{"authority", "definition", "name", "plural", "source", "version"}

// DecodeKind decodes a properties map into Kind, refusing what the declaration
// cannot hold: an undeclared key, a value of the wrong type, an enum or state
// outside its set, a number outside its declared range or beyond exact integer
// precision, a key breaking a keyed map's contract. The value is nil unless
// the problems are empty, so a half-decoded record can never reach a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — KindRequired and Missing are where
// requiredness lives.
func DecodeKind(props map[string]any) (*Kind, []Problem) {
	d := &decoder{}
	out, _ := decodeKind(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeKindSource decodes a declared KindSource value.
func decodeKindSource(d *decoder, path string, v any) (KindSource, bool) {
	s, ok := d.text(path, v, KindSourceValues, nil)
	if !ok {
		return "", false
	}
	return KindSource(s), true
}

// decodeKind decodes one Kind value at path.
func decodeKind(d *decoder, path string, v any) (Kind, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return Kind{}, false
	}
	var out Kind
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "name":
			p := at(path, "name")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Name = &e
			}
		case "authority":
			p := at(path, "authority")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Authority = &e
			}
		case "version":
			p := at(path, "version")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Version = &e
			}
		case "plural":
			p := at(path, "plural")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Plural = &e
			}
		case "source":
			p := at(path, "source")
			if e, ok := decodeKindSource(d, p, props[key]); ok {
				out.Source = &e
			}
		case "definition":
			p := at(path, "definition")
			if e, ok := d.dynamic(p, props[key]); ok {
				out.Definition = e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/kind")
		}
	}
	return out, true
}

// Properties is Kind as the properties map holds it, and DecodeKind's exact
// inverse: a nil pointer, a nil slice and a nil map each omit their key, so
// absence survives the round trip.
func (v *Kind) Properties() map[string]any {
	out := map[string]any{}
	if v.Name != nil {
		out["name"] = *v.Name
	}
	if v.Authority != nil {
		out["authority"] = *v.Authority
	}
	if v.Version != nil {
		out["version"] = *v.Version
	}
	if v.Plural != nil {
		out["plural"] = *v.Plural
	}
	if v.Source != nil {
		out["source"] = string(*v.Source)
	}
	if v.Definition != nil {
		out["definition"] = v.Definition
	}
	return out
}
