// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

import (
	"time"
)

// LLMInteraction is core.substrate.reamde.dev/llminteraction as its
// declaration admits it.
//
// One batch of questions an agent asked the user, waiting in the thread it
// came from: answering (or dismissing) it is one reviewed transition, which
// reports back into the thread and resumes the agent.
type LLMInteraction struct {
	// Thread is the thread whose ask call created this interaction. Points at
	// core.substrate.reamde.dev/llmthread.
	Thread *ReferencePath

	// Questions is the batch, fixed at creation; at most 8 questions.
	Questions []LLMInteractionQuestions

	// Answers is the user's selections, written by the answering transition.
	Answers []LLMInteractionAnswers

	// ResolvedAt is when the batch was answered or dismissed, stamped by the
	// transition. Managed: the engine stamps it, so a supplied value does not
	// decide it.
	ResolvedAt *string

	// State is pending until the user answers or dismisses; either way the
	// thread hears it. A state is NOT stored in properties: it lives in the
	// record's own state column and moves by transition. See
	// LLMInteractionState.
	State *LLMInteractionState
}

// LLMInteractionState is the state of the `state` machine.
//
// A STATE IS NOT A PROPERTY VALUE: it lives in the record's own state column
// and moves by transition, never by assignment. The declared states, the
// initial one and the legal moves are the constants and tables here; the field
// on the properties struct carries what a read reported, which is why Decode
// admits the key and Properties writes it back.
//
// pending until the user answers or dismisses; either way the thread hears it
type LLMInteractionState string

const (
	LLMInteractionStatePending   LLMInteractionState = "pending"
	LLMInteractionStateAnswered  LLMInteractionState = "answered"
	LLMInteractionStateDismissed LLMInteractionState = "dismissed"
)

// LLMInteractionStateValues are the declared states in declaration order.
var LLMInteractionStateValues = []string{"pending", "answered", "dismissed"}

// LLMInteractionStateInitial is the state a creation is born into.
const LLMInteractionStateInitial = LLMInteractionStatePending

// LLMInteractionStateTransitions are the declared moves, in declaration order.
// A move absent from this table is not performable: nothing else gates one,
// since a transition carries no guard.
var LLMInteractionStateTransitions = []StateTransition{
	{From: "pending", To: "answered", Stamps: map[string]string{"resolvedAt": "now"}, Notifies: "thread"},
	{From: "pending", To: "dismissed", Stamps: map[string]string{"resolvedAt": "now"}, Notifies: "thread"},
}

// Valid reports whether v is one of the declared states.
func (v LLMInteractionState) Valid() bool { return Declared(LLMInteractionStateValues, string(v)) }

// LLMInteractionStateCanMove reports whether from -> to is a declared move of
// the `state` machine.
func LLMInteractionStateCanMove(from, to LLMInteractionState) bool {
	for _, t := range LLMInteractionStateTransitions {
		if t.From == string(from) && t.To == string(to) {
			return true
		}
	}
	return false
}

// LLMInteractionKeys is the admitted key set: every property
// core.substrate.reamde.dev/llminteraction declares, sorted. A key outside it
// is refused by Decode, which is what replaces a hand-kept list of admitted
// keys in Go.
var LLMInteractionKeys = []string{"answers", "questions", "resolvedAt", "state", "thread"}

// DecodeLLMInteraction decodes a properties map into LLMInteraction, refusing
// what the declaration cannot hold: an undeclared key, a value of the wrong
// type, an enum or state outside its set, a number outside its declared range
// or beyond exact integer precision, a key breaking a keyed map's contract.
// The value is nil unless the problems are empty, so a half-decoded record can
// never reach a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — LLMInteractionRequired and Missing are where
// requiredness lives.
func DecodeLLMInteraction(props map[string]any) (*LLMInteraction, []Problem) {
	d := &decoder{}
	out, _ := decodeLLMInteraction(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// LLMInteractionRequired names the properties the declaration marks
// `required:`, sorted. It is a FORM-LEVEL contract: the write path does not
// enforce it, so Decode admits a value that leaves one absent and this is what
// a client checks before it submits one.
var LLMInteractionRequired = []string{"thread"}

// Missing names the required properties this value leaves absent, in
// declaration order. Empty means every declared requirement is answered —
// not that the value is admissible, which is the substrate's answer and not a
// type's.
func (v *LLMInteraction) Missing() []string {
	var out []string
	if v.Thread == nil {
		out = append(out, "thread")
	}
	return out
}

// decodeLLMInteractionState decodes a declared state of the `state` machine.
func decodeLLMInteractionState(d *decoder, path string, v any) (LLMInteractionState, bool) {
	s, ok := d.text(path, v, LLMInteractionStateValues, nil)
	if !ok {
		return "", false
	}
	return LLMInteractionState(s), true
}

// decodeLLMInteraction decodes one LLMInteraction value at path.
func decodeLLMInteraction(d *decoder, path string, v any) (LLMInteraction, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return LLMInteraction{}, false
	}
	var out LLMInteraction
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "thread":
			p := at(path, "thread")
			if e, ok := d.reference(p, props[key], "core.substrate.reamde.dev/llmthread"); ok {
				out.Thread = &e
			}
		case "questions":
			p := at(path, "questions")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]LLMInteractionQuestions, 0, len(items))
				for i, item := range items {
					if e, ok := decodeLLMInteractionQuestions(d, index(p, i), item); ok {
						list = append(list, e)
					}
				}
				out.Questions = list
			}
		case "answers":
			p := at(path, "answers")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]LLMInteractionAnswers, 0, len(items))
				for i, item := range items {
					if e, ok := decodeLLMInteractionAnswers(d, index(p, i), item); ok {
						list = append(list, e)
					}
				}
				out.Answers = list
			}
		case "resolvedAt":
			p := at(path, "resolvedAt")
			if e, ok := d.instant(p, props[key]); ok {
				out.ResolvedAt = &e
			}
		case "state":
			p := at(path, "state")
			if e, ok := decodeLLMInteractionState(d, p, props[key]); ok {
				out.State = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/llminteraction")
		}
	}
	return out, true
}

// Encode is LLMInteraction as the properties map holds it, and
// DecodeLLMInteraction's exact inverse: a nil pointer, a nil slice and a nil
// map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *LLMInteraction) Encode() map[string]any {
	out := map[string]any{}
	if v.Thread != nil {
		out["thread"] = string(*v.Thread)
	}
	if v.Questions != nil {
		items := make([]any, 0, len(v.Questions))
		for i := range v.Questions {
			items = append(items, v.Questions[i].Encode())
		}
		out["questions"] = items
	}
	if v.Answers != nil {
		items := make([]any, 0, len(v.Answers))
		for i := range v.Answers {
			items = append(items, v.Answers[i].Encode())
		}
		out["answers"] = items
	}
	if v.ResolvedAt != nil {
		out["resolvedAt"] = *v.ResolvedAt
	}
	if v.State != nil {
		out["state"] = string(*v.State)
	}
	return out
}

// ResolvedAtTime is ResolvedAt parsed. The stored form is the string, so this
// is a reading of it and never a second source of truth; an absent value reads
// as the zero time with no error, because absence is not a malformed instant.
func (v *LLMInteraction) ResolvedAtTime() (time.Time, error) {
	if v.ResolvedAt == nil {
		return time.Time{}, nil
	}
	return time.Parse(time.RFC3339, *v.ResolvedAt)
}

// LLMInteractionQuestions is one value of the `questions` object declared on
// core.substrate.reamde.dev/llminteraction.
//
// the batch, fixed at creation; at most 8 questions
type LLMInteractionQuestions struct {
	// Id is the agent's key for the question, echoed by its answer.
	Id *string

	// Prompt is the question itself, rendered as untrusted content.
	Prompt *string

	// Options is the offered answers; at most 32, values unique.
	Options []LLMInteractionQuestionsOptions

	// Multi is many-of-many; absent means exactly one.
	Multi *bool
}

// decodeLLMInteractionQuestions decodes one LLMInteractionQuestions value at path.
func decodeLLMInteractionQuestions(d *decoder, path string, v any) (LLMInteractionQuestions, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return LLMInteractionQuestions{}, false
	}
	var out LLMInteractionQuestions
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "id":
			p := at(path, "id")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Id = &e
			}
		case "prompt":
			p := at(path, "prompt")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Prompt = &e
			}
		case "options":
			p := at(path, "options")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]LLMInteractionQuestionsOptions, 0, len(items))
				for i, item := range items {
					if e, ok := decodeLLMInteractionQuestionsOptions(d, index(p, i), item); ok {
						list = append(list, e)
					}
				}
				out.Options = list
			}
		case "multi":
			p := at(path, "multi")
			if e, ok := d.flag(p, props[key]); ok {
				out.Multi = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/llminteraction")
		}
	}
	return out, true
}

// Encode is LLMInteractionQuestions as the properties map holds it, and
// decodeLLMInteractionQuestions's exact inverse: a nil pointer, a nil slice
// and a nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *LLMInteractionQuestions) Encode() map[string]any {
	out := map[string]any{}
	if v.Id != nil {
		out["id"] = *v.Id
	}
	if v.Prompt != nil {
		out["prompt"] = *v.Prompt
	}
	if v.Options != nil {
		items := make([]any, 0, len(v.Options))
		for i := range v.Options {
			items = append(items, v.Options[i].Encode())
		}
		out["options"] = items
	}
	if v.Multi != nil {
		out["multi"] = *v.Multi
	}
	return out
}

// LLMInteractionQuestionsOptions is one value of the `questions.options`
// object declared on core.substrate.reamde.dev/llminteraction.
//
// the offered answers; at most 32, values unique
type LLMInteractionQuestionsOptions struct {
	// Value is what an answer selects.
	Value *string

	// Label is what the user reads; the value renders otherwise.
	Label *string

	// Description is what picking it means.
	Description *string
}

// decodeLLMInteractionQuestionsOptions decodes one LLMInteractionQuestionsOptions value at path.
func decodeLLMInteractionQuestionsOptions(d *decoder, path string, v any) (LLMInteractionQuestionsOptions, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return LLMInteractionQuestionsOptions{}, false
	}
	var out LLMInteractionQuestionsOptions
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "value":
			p := at(path, "value")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Value = &e
			}
		case "label":
			p := at(path, "label")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Label = &e
			}
		case "description":
			p := at(path, "description")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Description = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/llminteraction")
		}
	}
	return out, true
}

// Encode is LLMInteractionQuestionsOptions as the properties map holds it, and
// decodeLLMInteractionQuestionsOptions's exact inverse: a nil pointer, a nil
// slice and a nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *LLMInteractionQuestionsOptions) Encode() map[string]any {
	out := map[string]any{}
	if v.Value != nil {
		out["value"] = *v.Value
	}
	if v.Label != nil {
		out["label"] = *v.Label
	}
	if v.Description != nil {
		out["description"] = *v.Description
	}
	return out
}

// LLMInteractionAnswers is one value of the `answers` object declared on
// core.substrate.reamde.dev/llminteraction.
//
// the user's selections, written by the answering transition
type LLMInteractionAnswers struct {
	// Question is the question id this answers.
	Question *string

	// Selected is the chosen option values.
	Selected []string
}

// decodeLLMInteractionAnswers decodes one LLMInteractionAnswers value at path.
func decodeLLMInteractionAnswers(d *decoder, path string, v any) (LLMInteractionAnswers, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return LLMInteractionAnswers{}, false
	}
	var out LLMInteractionAnswers
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "question":
			p := at(path, "question")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Question = &e
			}
		case "selected":
			p := at(path, "selected")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Selected = list
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/llminteraction")
		}
	}
	return out, true
}

// Encode is LLMInteractionAnswers as the properties map holds it, and
// decodeLLMInteractionAnswers's exact inverse: a nil pointer, a nil slice and
// a nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *LLMInteractionAnswers) Encode() map[string]any {
	out := map[string]any{}
	if v.Question != nil {
		out["question"] = *v.Question
	}
	if v.Selected != nil {
		items := make([]any, 0, len(v.Selected))
		for i := range v.Selected {
			items = append(items, v.Selected[i])
		}
		out["selected"] = items
	}
	return out
}
