// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// LLMMessage is core.substrate.reamde.dev/llmmessage as its declaration admits
// it.
//
// One turn of an agent thread — the transcript and the tool-call audit,
// written by the loop as it runs. A user turn is the envelope or the human's
// message, an assistant turn its prose and tool calls, a tool turn one
// dispatched call's result.
type LLMMessage struct {
	// Role is whose turn the row is, following the chat wire.
	Role *LLMMessageRole

	// Content is the turn's text; a tool row's result payload.
	Content *string

	// Turn is the loop iteration this row belongs to, for ordering.
	Turn *int64

	// ToolCalls is an assistant turn's dispatched calls.
	ToolCalls []LLMMessageToolCalls

	// ToolCallId is the assistant tool call a tool row answers.
	ToolCallId *string

	// Tool is the tool name a tool row answers for.
	Tool *string

	// Ok is whether the dispatch a tool row answers for succeeded.
	Ok *bool

	// Changes is the changelog entries this turn's dispatch wrote, stamped by
	// the engine.
	Changes []LLMMessageChanges

	// Thread is the thread this turn belongs to. Points at
	// core.substrate.reamde.dev/llmthread.
	Thread *ReferencePath
}

// LLMMessageRole is a declared enum: the admissible set, in declaration order.
//
// whose turn the row is, following the chat wire
type LLMMessageRole string

const (
	LLMMessageRoleUser      LLMMessageRole = "user"
	LLMMessageRoleAssistant LLMMessageRole = "assistant"
	LLMMessageRoleTool      LLMMessageRole = "tool"
	LLMMessageRoleSystem    LLMMessageRole = "system"
)

// LLMMessageRoleValues are the declared values in declaration order, which is
// render order.
var LLMMessageRoleValues = []string{"user", "assistant", "tool", "system"}

// Valid reports whether v is one of the declared values.
func (v LLMMessageRole) Valid() bool { return Declared(LLMMessageRoleValues, string(v)) }

// LLMMessageKeys is the admitted key set: every property
// core.substrate.reamde.dev/llmmessage declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var LLMMessageKeys = []string{"changes", "content", "ok", "role", "thread", "tool", "toolCallId", "toolCalls", "turn"}

// DecodeLLMMessage decodes a properties map into LLMMessage, refusing what the
// declaration cannot hold: an undeclared key, a value of the wrong type, an
// enum or state outside its set, a number outside its declared range or beyond
// exact integer precision, a key breaking a keyed map's contract. The value is
// nil unless the problems are empty, so a half-decoded record can never reach
// a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — LLMMessageRequired and Missing are where
// requiredness lives.
func DecodeLLMMessage(props map[string]any) (*LLMMessage, []Problem) {
	d := &decoder{}
	out, _ := decodeLLMMessage(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// LLMMessageRequired names the properties the declaration marks `required:`,
// sorted. It is a FORM-LEVEL contract: the write path does not enforce it, so
// Decode admits a value that leaves one absent and this is what a client
// checks before it submits one.
var LLMMessageRequired = []string{"thread"}

// Missing names the required properties this value leaves absent, in
// declaration order. Empty means every declared requirement is answered —
// not that the value is admissible, which is the substrate's answer and not a
// type's.
func (v *LLMMessage) Missing() []string {
	var out []string
	if v.Thread == nil {
		out = append(out, "thread")
	}
	return out
}

// decodeLLMMessageRole decodes a declared LLMMessageRole value.
func decodeLLMMessageRole(d *decoder, path string, v any) (LLMMessageRole, bool) {
	s, ok := d.text(path, v, LLMMessageRoleValues, nil)
	if !ok {
		return "", false
	}
	return LLMMessageRole(s), true
}

// decodeLLMMessage decodes one LLMMessage value at path.
func decodeLLMMessage(d *decoder, path string, v any) (LLMMessage, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return LLMMessage{}, false
	}
	var out LLMMessage
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "role":
			p := at(path, "role")
			if e, ok := decodeLLMMessageRole(d, p, props[key]); ok {
				out.Role = &e
			}
		case "content":
			p := at(path, "content")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Content = &e
			}
		case "turn":
			p := at(path, "turn")
			if e, ok := d.integer(p, props[key], Bounds{}); ok {
				out.Turn = &e
			}
		case "toolCalls":
			p := at(path, "toolCalls")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]LLMMessageToolCalls, 0, len(items))
				for i, item := range items {
					if e, ok := decodeLLMMessageToolCalls(d, index(p, i), item); ok {
						list = append(list, e)
					}
				}
				out.ToolCalls = list
			}
		case "toolCallId":
			p := at(path, "toolCallId")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.ToolCallId = &e
			}
		case "tool":
			p := at(path, "tool")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Tool = &e
			}
		case "ok":
			p := at(path, "ok")
			if e, ok := d.flag(p, props[key]); ok {
				out.Ok = &e
			}
		case "changes":
			p := at(path, "changes")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]LLMMessageChanges, 0, len(items))
				for i, item := range items {
					if e, ok := decodeLLMMessageChanges(d, index(p, i), item); ok {
						list = append(list, e)
					}
				}
				out.Changes = list
			}
		case "thread":
			p := at(path, "thread")
			if e, ok := d.reference(p, props[key], "core.substrate.reamde.dev/llmthread"); ok {
				out.Thread = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/llmmessage")
		}
	}
	return out, true
}

// Encode is LLMMessage as the properties map holds it, and DecodeLLMMessage's
// exact inverse: a nil pointer, a nil slice and a nil map each omit their key,
// so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *LLMMessage) Encode() map[string]any {
	out := map[string]any{}
	if v.Role != nil {
		out["role"] = string(*v.Role)
	}
	if v.Content != nil {
		out["content"] = *v.Content
	}
	if v.Turn != nil {
		out["turn"] = *v.Turn
	}
	if v.ToolCalls != nil {
		items := make([]any, 0, len(v.ToolCalls))
		for i := range v.ToolCalls {
			items = append(items, v.ToolCalls[i].Encode())
		}
		out["toolCalls"] = items
	}
	if v.ToolCallId != nil {
		out["toolCallId"] = *v.ToolCallId
	}
	if v.Tool != nil {
		out["tool"] = *v.Tool
	}
	if v.Ok != nil {
		out["ok"] = *v.Ok
	}
	if v.Changes != nil {
		items := make([]any, 0, len(v.Changes))
		for i := range v.Changes {
			items = append(items, v.Changes[i].Encode())
		}
		out["changes"] = items
	}
	if v.Thread != nil {
		out["thread"] = string(*v.Thread)
	}
	return out
}

// LLMMessageToolCalls is one value of the `toolCalls` object declared on
// core.substrate.reamde.dev/llmmessage.
//
// an assistant turn's dispatched calls
type LLMMessageToolCalls struct {
	// Id is the provider's call id, which a tool row answers by.
	Id *string

	// Name is the tool the model called.
	Name *string

	// Arguments is the call's arguments, as the provider wrote them.
	Arguments *string
}

// decodeLLMMessageToolCalls decodes one LLMMessageToolCalls value at path.
func decodeLLMMessageToolCalls(d *decoder, path string, v any) (LLMMessageToolCalls, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return LLMMessageToolCalls{}, false
	}
	var out LLMMessageToolCalls
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "id":
			p := at(path, "id")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Id = &e
			}
		case "name":
			p := at(path, "name")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Name = &e
			}
		case "arguments":
			p := at(path, "arguments")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Arguments = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/llmmessage")
		}
	}
	return out, true
}

// Encode is LLMMessageToolCalls as the properties map holds it, and
// decodeLLMMessageToolCalls's exact inverse: a nil pointer, a nil slice and a
// nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *LLMMessageToolCalls) Encode() map[string]any {
	out := map[string]any{}
	if v.Id != nil {
		out["id"] = *v.Id
	}
	if v.Name != nil {
		out["name"] = *v.Name
	}
	if v.Arguments != nil {
		out["arguments"] = *v.Arguments
	}
	return out
}

// LLMMessageChanges is one value of the `changes` object declared on
// core.substrate.reamde.dev/llmmessage.
//
// the changelog entries this turn's dispatch wrote, stamped by the engine
type LLMMessageChanges struct {
	// Seq is the changelog seq of the entry, which addresses its delta.
	Seq *int64

	// Op is the changelog op the entry landed as, verbatim.
	Op *LLMMessageChangesOp

	// Kind is the written record's kind.
	Kind *string

	// Id is the written record's id.
	Id *string
}

// LLMMessageChangesOp is a declared enum: the admissible set, in declaration
// order.
//
// the changelog op the entry landed as, verbatim
type LLMMessageChangesOp string

const (
	LLMMessageChangesOpPut    LLMMessageChangesOp = "put"
	LLMMessageChangesOpPatch  LLMMessageChangesOp = "patch"
	LLMMessageChangesOpDelete LLMMessageChangesOp = "delete"
	LLMMessageChangesOpLink   LLMMessageChangesOp = "link"
	LLMMessageChangesOpUnlink LLMMessageChangesOp = "unlink"
	LLMMessageChangesOpMerge  LLMMessageChangesOp = "merge"
	LLMMessageChangesOpSplit  LLMMessageChangesOp = "split"
)

// LLMMessageChangesOpValues are the declared values in declaration order,
// which is render order.
var LLMMessageChangesOpValues = []string{"put", "patch", "delete", "link", "unlink", "merge", "split"}

// Valid reports whether v is one of the declared values.
func (v LLMMessageChangesOp) Valid() bool { return Declared(LLMMessageChangesOpValues, string(v)) }

// decodeLLMMessageChangesOp decodes a declared LLMMessageChangesOp value.
func decodeLLMMessageChangesOp(d *decoder, path string, v any) (LLMMessageChangesOp, bool) {
	s, ok := d.text(path, v, LLMMessageChangesOpValues, nil)
	if !ok {
		return "", false
	}
	return LLMMessageChangesOp(s), true
}

// decodeLLMMessageChanges decodes one LLMMessageChanges value at path.
func decodeLLMMessageChanges(d *decoder, path string, v any) (LLMMessageChanges, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return LLMMessageChanges{}, false
	}
	var out LLMMessageChanges
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "seq":
			p := at(path, "seq")
			if e, ok := d.integer(p, props[key], Bounds{}); ok {
				out.Seq = &e
			}
		case "op":
			p := at(path, "op")
			if e, ok := decodeLLMMessageChangesOp(d, p, props[key]); ok {
				out.Op = &e
			}
		case "kind":
			p := at(path, "kind")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Kind = &e
			}
		case "id":
			p := at(path, "id")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Id = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/llmmessage")
		}
	}
	return out, true
}

// Encode is LLMMessageChanges as the properties map holds it, and
// decodeLLMMessageChanges's exact inverse: a nil pointer, a nil slice and a
// nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *LLMMessageChanges) Encode() map[string]any {
	out := map[string]any{}
	if v.Seq != nil {
		out["seq"] = *v.Seq
	}
	if v.Op != nil {
		out["op"] = string(*v.Op)
	}
	if v.Kind != nil {
		out["kind"] = *v.Kind
	}
	if v.Id != nil {
		out["id"] = *v.Id
	}
	return out
}
