// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// LLMMessage is core.substrate.reamde.dev/llmmessage as its declaration admits
// it.
//
// One turn of an agent thread — the transcript and the tool-call audit,
// written by the loop as it runs. A user turn is the envelope or the human's
// message, an assistant turn its prose and tool calls, a tool turn one
// dispatched call's result.
type LLMMessage struct {
	// Role is user, assistant or tool.
	Role *string

	// Content is the turn's text; a tool row's result payload.
	Content *string

	// Turn is the loop iteration this row belongs to, for ordering.
	Turn *int64

	// ToolCalls is an assistant turn's dispatched calls, [{id, name,
	// arguments}].
	ToolCalls Dynamic

	// ToolCallId is the assistant tool call a tool row answers.
	ToolCallId *string

	// Tool is the tool name a tool row answers for.
	Tool *string

	// Ok is whether the dispatch a tool row answers for succeeded.
	Ok *bool

	// Thread is the thread this turn belongs to. Points at
	// core.substrate.reamde.dev/llmthread.
	Thread Reference
}

// LLMMessageKeys is the admitted key set: every property
// core.substrate.reamde.dev/llmmessage declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var LLMMessageKeys = []string{"content", "ok", "role", "thread", "tool", "toolCallId", "toolCalls", "turn"}

// DecodeLLMMessage decodes an authored properties map into LLMMessage,
// refusing anything the declaration does not admit: an undeclared key, a value
// of the wrong type, an enum or state outside its set, a number outside its
// range, a required property left absent. The value is nil unless the problems
// are empty, so a half-decoded record can never reach a caller.
//
// Structural only. Whether the referent of a reference exists, whether a
// transition is legal from where the record stands, and whether this writer
// may write a managed property are the engine's questions, not this package's.
func DecodeLLMMessage(props map[string]any) (*LLMMessage, []Problem) {
	d := &decoder{}
	out, _ := decodeLLMMessage(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeLLMMessage decodes one LLMMessage value at path.
func decodeLLMMessage(d *decoder, path string, v any) (LLMMessage, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return LLMMessage{}, false
	}
	var out LLMMessage
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "role":
			p := at(path, "role")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Role = &e
			}
		case "content":
			p := at(path, "content")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Content = &e
			}
		case "turn":
			p := at(path, "turn")
			if e, ok := d.integer(p, props[key], Bounds{}); ok {
				out.Turn = &e
			}
		case "toolCalls":
			p := at(path, "toolCalls")
			if e, ok := d.dynamic(p, props[key]); ok {
				out.ToolCalls = e
			}
		case "toolCallId":
			p := at(path, "toolCallId")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.ToolCallId = &e
			}
		case "tool":
			p := at(path, "tool")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Tool = &e
			}
		case "ok":
			p := at(path, "ok")
			if e, ok := d.flag(p, props[key]); ok {
				out.Ok = &e
			}
		case "thread":
			p := at(path, "thread")
			if e, ok := d.reference(p, props[key], "core.substrate.reamde.dev/llmthread"); ok {
				out.Thread = e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/llmmessage")
		}
	}
	if props["thread"] == nil {
		d.missing(at(path, "thread"))
	}
	return out, true
}

// Properties is LLMMessage as the properties map holds it, and
// DecodeLLMMessage's exact inverse: a nil pointer, a nil slice and a nil map
// each omit their key, so absence survives the round trip.
func (v *LLMMessage) Properties() map[string]any {
	out := map[string]any{}
	if v.Role != nil {
		out["role"] = *v.Role
	}
	if v.Content != nil {
		out["content"] = *v.Content
	}
	if v.Turn != nil {
		out["turn"] = *v.Turn
	}
	if v.ToolCalls != nil {
		out["toolCalls"] = v.ToolCalls
	}
	if v.ToolCallId != nil {
		out["toolCallId"] = *v.ToolCallId
	}
	if v.Tool != nil {
		out["tool"] = *v.Tool
	}
	if v.Ok != nil {
		out["ok"] = *v.Ok
	}
	out["thread"] = v.Thread.Properties()
	return out
}
