// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// LLMProvider is core.substrate.reamde.dev/llmprovider as its declaration
// admits it.
//
// One place completions are bought: the wire an adapter speaks, the endpoint,
// the key that reaches it, and what its models cost. An agent names a provider
// and a model, so re-pointing every agent on a provider is one patch to this
// row.
type LLMProvider struct {
	// Name is a human label for the row (the id is the reference).
	Name *string

	// Wire is the wire protocol the adapter speaks; a gateway that speaks
	// OpenAI's wire is an openai row.
	Wire *LLMProviderWire

	// BaseURL is the endpoint; only anthropic may leave it empty, for its
	// official endpoint, and openai and azure both require it.
	BaseURL *string

	// ApiKey is bearer for the endpoint; every row carries its own, because
	// there is no host key to fall back to.
	ApiKey *SecretRef

	// EmbedModel is the embeddings model this row's endpoint serves; naming it
	// makes this the repository's embeddings provider, and only one row may
	// name one.
	EmbedModel *string

	// Headers is extra request headers, e.g. a gateway's attribution headers.
	Headers []LLMProviderHeaders

	// Defaults is request params the agent's own merge OVER.
	Defaults *LLMProviderDefaults

	// Pricing is approximate USD per 1M tokens, one row per model.
	Pricing []LLMProviderPricing
}

// LLMProviderWire is a declared enum: the admissible set, in declaration
// order.
//
// the wire protocol the adapter speaks; a gateway that speaks OpenAI's wire is
// an openai row
type LLMProviderWire string

const (
	LLMProviderWireOpenai    LLMProviderWire = "openai"
	LLMProviderWireAnthropic LLMProviderWire = "anthropic"
	LLMProviderWireAzure     LLMProviderWire = "azure"
)

// LLMProviderWireValues are the declared values in declaration order, which is
// render order.
var LLMProviderWireValues = []string{"openai", "anthropic", "azure"}

// LLMProviderWireLabels are the declared human labels by value: a client
// renders the label and submits the value. A value with no declared label is
// absent, and the client humanizes it.
var LLMProviderWireLabels = map[string]string{
	"openai":    "OpenAI",
	"anthropic": "Anthropic",
	"azure":     "Azure OpenAI",
}

// Valid reports whether v is one of the declared values.
func (v LLMProviderWire) Valid() bool { return Declared(LLMProviderWireValues, string(v)) }

// LLMProviderKeys is the admitted key set: every property
// core.substrate.reamde.dev/llmprovider declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var LLMProviderKeys = []string{"apiKey", "baseURL", "defaults", "embedModel", "headers", "name", "pricing", "wire"}

// DecodeLLMProvider decodes a properties map into LLMProvider, refusing what
// the declaration cannot hold: an undeclared key, a value of the wrong type,
// an enum or state outside its set, a number outside its declared range or
// beyond exact integer precision, a key breaking a keyed map's contract. The
// value is nil unless the problems are empty, so a half-decoded record can
// never reach a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — LLMProviderRequired and Missing are where
// requiredness lives.
func DecodeLLMProvider(props map[string]any) (*LLMProvider, []Problem) {
	d := &decoder{}
	out, _ := decodeLLMProvider(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeLLMProviderWire decodes a declared LLMProviderWire value.
func decodeLLMProviderWire(d *decoder, path string, v any) (LLMProviderWire, bool) {
	s, ok := d.text(path, v, LLMProviderWireValues, nil)
	if !ok {
		return "", false
	}
	return LLMProviderWire(s), true
}

// decodeLLMProvider decodes one LLMProvider value at path.
func decodeLLMProvider(d *decoder, path string, v any) (LLMProvider, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return LLMProvider{}, false
	}
	var out LLMProvider
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "name":
			p := at(path, "name")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Name = &e
			}
		case "wire":
			p := at(path, "wire")
			if e, ok := decodeLLMProviderWire(d, p, props[key]); ok {
				out.Wire = &e
			}
		case "baseURL":
			p := at(path, "baseURL")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.BaseURL = &e
			}
		case "apiKey":
			p := at(path, "apiKey")
			if e, ok := d.secret(p, props[key]); ok {
				out.ApiKey = &e
			}
		case "embedModel":
			p := at(path, "embedModel")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.EmbedModel = &e
			}
		case "headers":
			p := at(path, "headers")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]LLMProviderHeaders, 0, len(items))
				for i, item := range items {
					if e, ok := decodeLLMProviderHeaders(d, index(p, i), item); ok {
						list = append(list, e)
					}
				}
				out.Headers = list
			}
		case "defaults":
			p := at(path, "defaults")
			if e, ok := decodeLLMProviderDefaults(d, p, props[key]); ok {
				out.Defaults = &e
			}
		case "pricing":
			p := at(path, "pricing")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]LLMProviderPricing, 0, len(items))
				for i, item := range items {
					if e, ok := decodeLLMProviderPricing(d, index(p, i), item); ok {
						list = append(list, e)
					}
				}
				out.Pricing = list
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/llmprovider")
		}
	}
	return out, true
}

// Encode is LLMProvider as the properties map holds it, and
// DecodeLLMProvider's exact inverse: a nil pointer, a nil slice and a nil map
// each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *LLMProvider) Encode() map[string]any {
	out := map[string]any{}
	if v.Name != nil {
		out["name"] = *v.Name
	}
	if v.Wire != nil {
		out["wire"] = string(*v.Wire)
	}
	if v.BaseURL != nil {
		out["baseURL"] = *v.BaseURL
	}
	if v.ApiKey != nil {
		out["apiKey"] = string(*v.ApiKey)
	}
	if v.EmbedModel != nil {
		out["embedModel"] = *v.EmbedModel
	}
	if v.Headers != nil {
		items := make([]any, 0, len(v.Headers))
		for i := range v.Headers {
			items = append(items, v.Headers[i].Encode())
		}
		out["headers"] = items
	}
	if v.Defaults != nil {
		out["defaults"] = v.Defaults.Encode()
	}
	if v.Pricing != nil {
		items := make([]any, 0, len(v.Pricing))
		for i := range v.Pricing {
			items = append(items, v.Pricing[i].Encode())
		}
		out["pricing"] = items
	}
	return out
}

// LLMProviderHeaders is one value of the `headers` object declared on
// core.substrate.reamde.dev/llmprovider.
//
// extra request headers, e.g. a gateway's attribution headers
type LLMProviderHeaders struct {
	// Name is the header name, sent as written.
	Name *string

	// Value is the header value.
	Value *string
}

// decodeLLMProviderHeaders decodes one LLMProviderHeaders value at path.
func decodeLLMProviderHeaders(d *decoder, path string, v any) (LLMProviderHeaders, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return LLMProviderHeaders{}, false
	}
	var out LLMProviderHeaders
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "name":
			p := at(path, "name")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Name = &e
			}
		case "value":
			p := at(path, "value")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Value = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/llmprovider")
		}
	}
	return out, true
}

// Encode is LLMProviderHeaders as the properties map holds it, and
// decodeLLMProviderHeaders's exact inverse: a nil pointer, a nil slice and a
// nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *LLMProviderHeaders) Encode() map[string]any {
	out := map[string]any{}
	if v.Name != nil {
		out["name"] = *v.Name
	}
	if v.Value != nil {
		out["value"] = *v.Value
	}
	return out
}

// LLMProviderDefaults is one value of the `defaults` object declared on
// core.substrate.reamde.dev/llmprovider.
//
// request params the agent's own merge OVER
type LLMProviderDefaults struct {
	// Temperature is sampling temperature.
	Temperature *float64

	// MaxTokens is the completion ceiling in tokens.
	MaxTokens *int64
}

// decodeLLMProviderDefaults decodes one LLMProviderDefaults value at path.
func decodeLLMProviderDefaults(d *decoder, path string, v any) (LLMProviderDefaults, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return LLMProviderDefaults{}, false
	}
	var out LLMProviderDefaults
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "temperature":
			p := at(path, "temperature")
			if e, ok := d.number(p, props[key], Bounds{Min: bound(0), Max: bound(2)}); ok {
				out.Temperature = &e
			}
		case "maxTokens":
			p := at(path, "maxTokens")
			if e, ok := d.integer(p, props[key], Bounds{Min: bound(1)}); ok {
				out.MaxTokens = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/llmprovider")
		}
	}
	return out, true
}

// Encode is LLMProviderDefaults as the properties map holds it, and
// decodeLLMProviderDefaults's exact inverse: a nil pointer, a nil slice and a
// nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *LLMProviderDefaults) Encode() map[string]any {
	out := map[string]any{}
	if v.Temperature != nil {
		out["temperature"] = *v.Temperature
	}
	if v.MaxTokens != nil {
		out["maxTokens"] = *v.MaxTokens
	}
	return out
}

// LLMProviderPricing is one value of the `pricing` object declared on
// core.substrate.reamde.dev/llmprovider.
//
// approximate USD per 1M tokens, one row per model
type LLMProviderPricing struct {
	// Model is the model id as sent to this provider.
	Model *string

	// InputPer1M is USD per 1M input tokens, exact digits as a string.
	InputPer1M *string

	// OutputPer1M is USD per 1M output tokens, exact digits as a string.
	OutputPer1M *string
}

// decodeLLMProviderPricing decodes one LLMProviderPricing value at path.
func decodeLLMProviderPricing(d *decoder, path string, v any) (LLMProviderPricing, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return LLMProviderPricing{}, false
	}
	var out LLMProviderPricing
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "model":
			p := at(path, "model")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Model = &e
			}
		case "inputPer1M":
			p := at(path, "inputPer1M")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.InputPer1M = &e
			}
		case "outputPer1M":
			p := at(path, "outputPer1M")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.OutputPer1M = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/llmprovider")
		}
	}
	return out, true
}

// Encode is LLMProviderPricing as the properties map holds it, and
// decodeLLMProviderPricing's exact inverse: a nil pointer, a nil slice and a
// nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *LLMProviderPricing) Encode() map[string]any {
	out := map[string]any{}
	if v.Model != nil {
		out["model"] = *v.Model
	}
	if v.InputPer1M != nil {
		out["inputPer1M"] = *v.InputPer1M
	}
	if v.OutputPer1M != nil {
		out["outputPer1M"] = *v.OutputPer1M
	}
	return out
}
