// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

import (
	"time"
)

// LLMThread is core.substrate.reamde.dev/llmthread as its declaration admits
// it.
//
// One agent invocation's conversation state; there is no agent-run record, the
// thread IS the run. Status, turns, tokens and cost accumulate as the loop
// goes, and a root thread's tally rolls up every sub-agent's spend, so one
// number answers what a chain cost.
type LLMThread struct {
	// Agent is the agent this thread ran. Points at
	// core.substrate.reamde.dev/agent.
	Agent *ReferencePath

	// Provider is the llmprovider row id the run resolved.
	Provider *string

	// Model is the model id the run sent.
	Model *string

	// Mode is trigger, schedule, webhook, manual, call, subagent or chat.
	Mode *string

	// Status is running, then ok, overbudget or error.
	Status *string

	// Reason is which budget ended an overbudget run, or the error.
	Reason *string

	// AgentDepth is how many sub-agent hops sit above this thread (0 = root).
	AgentDepth *int64

	// Turns is model calls this thread burned.
	Turns *int64

	// ToolCalls is tool dispatches this thread burned.
	ToolCalls *int64

	// PromptTokens is prompt tokens; on the root thread, sub-agents included.
	PromptTokens *int64

	// CompletionTokens is completion tokens; on the root thread, sub-agents
	// included.
	CompletionTokens *int64

	// TotalTokens is total tokens; on the root thread, sub-agents included.
	TotalTokens *int64

	// CostUSD is the provider row's pricing for the model applied to the
	// tally; 0 when unpriced.
	CostUSD *float64

	// StartedAt is when the loop opened the thread.
	StartedAt *string

	// FinishedAt is when the loop settled.
	FinishedAt *string

	// LeaseUntil is the running turn's lease horizon — one active
	// continuation per thread; a second turn is refused while the lease is
	// live, and a crashed turn's expired lease is taken over.
	LeaseUntil *string

	// Parent is the calling agent's thread, on sub-agent threads. Points at
	// core.substrate.reamde.dev/llmthread.
	Parent *ReferencePath
}

// LLMThreadKeys is the admitted key set: every property
// core.substrate.reamde.dev/llmthread declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var LLMThreadKeys = []string{"agent", "agentDepth", "completionTokens", "costUSD", "finishedAt", "leaseUntil", "mode", "model", "parent", "promptTokens", "provider", "reason", "startedAt", "status", "toolCalls", "totalTokens", "turns"}

// DecodeLLMThread decodes a properties map into LLMThread, refusing what the
// declaration cannot hold: an undeclared key, a value of the wrong type, an
// enum or state outside its set, a number outside its declared range or beyond
// exact integer precision, a key breaking a keyed map's contract. The value is
// nil unless the problems are empty, so a half-decoded record can never reach
// a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — LLMThreadRequired and Missing are where
// requiredness lives.
func DecodeLLMThread(props map[string]any) (*LLMThread, []Problem) {
	d := &decoder{}
	out, _ := decodeLLMThread(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// LLMThreadRequired names the properties the declaration marks `required:`,
// sorted. It is a FORM-LEVEL contract: the write path does not enforce it, so
// Decode admits a value that leaves one absent and this is what a client
// checks before it submits one.
var LLMThreadRequired = []string{"agent"}

// Missing names the required properties this value leaves absent, in
// declaration order. Empty means every declared requirement is answered —
// not that the value is admissible, which is the substrate's answer and not a
// type's.
func (v *LLMThread) Missing() []string {
	var out []string
	if v.Agent == nil {
		out = append(out, "agent")
	}
	return out
}

// decodeLLMThread decodes one LLMThread value at path.
func decodeLLMThread(d *decoder, path string, v any) (LLMThread, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return LLMThread{}, false
	}
	var out LLMThread
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "agent":
			p := at(path, "agent")
			if e, ok := d.reference(p, props[key], "core.substrate.reamde.dev/agent"); ok {
				out.Agent = &e
			}
		case "provider":
			p := at(path, "provider")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Provider = &e
			}
		case "model":
			p := at(path, "model")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Model = &e
			}
		case "mode":
			p := at(path, "mode")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Mode = &e
			}
		case "status":
			p := at(path, "status")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Status = &e
			}
		case "reason":
			p := at(path, "reason")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Reason = &e
			}
		case "agentDepth":
			p := at(path, "agentDepth")
			if e, ok := d.integer(p, props[key], Bounds{}); ok {
				out.AgentDepth = &e
			}
		case "turns":
			p := at(path, "turns")
			if e, ok := d.integer(p, props[key], Bounds{}); ok {
				out.Turns = &e
			}
		case "toolCalls":
			p := at(path, "toolCalls")
			if e, ok := d.integer(p, props[key], Bounds{}); ok {
				out.ToolCalls = &e
			}
		case "promptTokens":
			p := at(path, "promptTokens")
			if e, ok := d.integer(p, props[key], Bounds{}); ok {
				out.PromptTokens = &e
			}
		case "completionTokens":
			p := at(path, "completionTokens")
			if e, ok := d.integer(p, props[key], Bounds{}); ok {
				out.CompletionTokens = &e
			}
		case "totalTokens":
			p := at(path, "totalTokens")
			if e, ok := d.integer(p, props[key], Bounds{}); ok {
				out.TotalTokens = &e
			}
		case "costUSD":
			p := at(path, "costUSD")
			if e, ok := d.number(p, props[key], Bounds{}); ok {
				out.CostUSD = &e
			}
		case "startedAt":
			p := at(path, "startedAt")
			if e, ok := d.instant(p, props[key]); ok {
				out.StartedAt = &e
			}
		case "finishedAt":
			p := at(path, "finishedAt")
			if e, ok := d.instant(p, props[key]); ok {
				out.FinishedAt = &e
			}
		case "leaseUntil":
			p := at(path, "leaseUntil")
			if e, ok := d.instant(p, props[key]); ok {
				out.LeaseUntil = &e
			}
		case "parent":
			p := at(path, "parent")
			if e, ok := d.reference(p, props[key], "core.substrate.reamde.dev/llmthread"); ok {
				out.Parent = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/llmthread")
		}
	}
	return out, true
}

// Encode is LLMThread as the properties map holds it, and DecodeLLMThread's
// exact inverse: a nil pointer, a nil slice and a nil map each omit their key,
// so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *LLMThread) Encode() map[string]any {
	out := map[string]any{}
	if v.Agent != nil {
		out["agent"] = string(*v.Agent)
	}
	if v.Provider != nil {
		out["provider"] = *v.Provider
	}
	if v.Model != nil {
		out["model"] = *v.Model
	}
	if v.Mode != nil {
		out["mode"] = *v.Mode
	}
	if v.Status != nil {
		out["status"] = *v.Status
	}
	if v.Reason != nil {
		out["reason"] = *v.Reason
	}
	if v.AgentDepth != nil {
		out["agentDepth"] = *v.AgentDepth
	}
	if v.Turns != nil {
		out["turns"] = *v.Turns
	}
	if v.ToolCalls != nil {
		out["toolCalls"] = *v.ToolCalls
	}
	if v.PromptTokens != nil {
		out["promptTokens"] = *v.PromptTokens
	}
	if v.CompletionTokens != nil {
		out["completionTokens"] = *v.CompletionTokens
	}
	if v.TotalTokens != nil {
		out["totalTokens"] = *v.TotalTokens
	}
	if v.CostUSD != nil {
		out["costUSD"] = *v.CostUSD
	}
	if v.StartedAt != nil {
		out["startedAt"] = *v.StartedAt
	}
	if v.FinishedAt != nil {
		out["finishedAt"] = *v.FinishedAt
	}
	if v.LeaseUntil != nil {
		out["leaseUntil"] = *v.LeaseUntil
	}
	if v.Parent != nil {
		out["parent"] = string(*v.Parent)
	}
	return out
}

// StartedAtTime is StartedAt parsed. The stored form is the string, so this is
// a reading of it and never a second source of truth; an absent value reads as
// the zero time with no error, because absence is not a malformed instant.
func (v *LLMThread) StartedAtTime() (time.Time, error) {
	if v.StartedAt == nil {
		return time.Time{}, nil
	}
	return time.Parse(time.RFC3339, *v.StartedAt)
}

// FinishedAtTime is FinishedAt parsed. The stored form is the string, so this
// is a reading of it and never a second source of truth; an absent value reads
// as the zero time with no error, because absence is not a malformed instant.
func (v *LLMThread) FinishedAtTime() (time.Time, error) {
	if v.FinishedAt == nil {
		return time.Time{}, nil
	}
	return time.Parse(time.RFC3339, *v.FinishedAt)
}

// LeaseUntilTime is LeaseUntil parsed. The stored form is the string, so this
// is a reading of it and never a second source of truth; an absent value reads
// as the zero time with no error, because absence is not a malformed instant.
func (v *LLMThread) LeaseUntilTime() (time.Time, error) {
	if v.LeaseUntil == nil {
		return time.Time{}, nil
	}
	return time.Parse(time.RFC3339, *v.LeaseUntil)
}
