// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// PropertyType is core.substrate.reamde.dev/propertytype as its declaration
// admits it.
//
// One custom property type: a built-in datatype refined by a pattern, a range
// or a value set (`isbn`, `asin`). Authority-local — only the authority that
// declares it may use it — so a shape is stated once instead of repeated on
// every property that wants it.
type PropertyType struct {
	// Version is this declaration's version.
	Version *string

	// Name is the refinement's local name.
	Name *string

	// Authority is the one authority it is usable in.
	Authority *string

	// Base is the built-in kind it refines.
	Base *string

	// Definition is the parsed manifest data.
	Definition Dynamic
}

// PropertyTypeKeys is the admitted key set: every property
// core.substrate.reamde.dev/propertytype declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var PropertyTypeKeys = []string{"authority", "base", "definition", "name", "version"}

// DecodePropertyType decodes a properties map into PropertyType, refusing what
// the declaration cannot hold: an undeclared key, a value of the wrong type,
// an enum or state outside its set, a number outside its declared range or
// beyond exact integer precision, a key breaking a keyed map's contract. The
// value is nil unless the problems are empty, so a half-decoded record can
// never reach a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — PropertyTypeRequired and Missing are where
// requiredness lives.
func DecodePropertyType(props map[string]any) (*PropertyType, []Problem) {
	d := &decoder{}
	out, _ := decodePropertyType(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodePropertyType decodes one PropertyType value at path.
func decodePropertyType(d *decoder, path string, v any) (PropertyType, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return PropertyType{}, false
	}
	var out PropertyType
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "version":
			p := at(path, "version")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Version = &e
			}
		case "name":
			p := at(path, "name")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Name = &e
			}
		case "authority":
			p := at(path, "authority")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Authority = &e
			}
		case "base":
			p := at(path, "base")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Base = &e
			}
		case "definition":
			p := at(path, "definition")
			if e, ok := d.dynamic(p, props[key]); ok {
				out.Definition = e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/propertytype")
		}
	}
	return out, true
}

// Properties is PropertyType as the properties map holds it, and
// DecodePropertyType's exact inverse: a nil pointer, a nil slice and a nil map
// each omit their key, so absence survives the round trip.
func (v *PropertyType) Properties() map[string]any {
	out := map[string]any{}
	if v.Version != nil {
		out["version"] = *v.Version
	}
	if v.Name != nil {
		out["name"] = *v.Name
	}
	if v.Authority != nil {
		out["authority"] = *v.Authority
	}
	if v.Base != nil {
		out["base"] = *v.Base
	}
	if v.Definition != nil {
		out["definition"] = v.Definition
	}
	return out
}
