// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

import (
	"time"
)

// RecordPatchRequest is core.substrate.reamde.dev/recordpatchrequest as its
// declaration admits it.
//
// A proposed change to the graph, waiting for the owner: patch an existing
// record, create one, or delete one. A learner or an app writes it, accepting
// the decision applies it, and the envelope is frozen once proposed so nobody
// can swap what was reviewed.
type RecordPatchRequest struct {
	// Op is the change verb — patch (default when absent), create, or
	// delete.
	Op *RecordPatchRequestOp

	// TargetKind is op create: the full type identity of the record to mint.
	TargetKind *string

	// TargetId is op create: a stable id for the new record.
	TargetId *string

	// TargetVersion is the target version the diff was computed against.
	TargetVersion *int64

	// Diff is the proposed change, applied whole when the decision is accepted
	// — property values under `properties` (and, for create, edges under
	// `edges`).
	Diff Dynamic

	// Rationale is why the writer proposes this change.
	Rationale *string

	// Decision is proposed until somebody decides; accepting is what applies
	// the change. A state is NOT stored in properties: it lives in the
	// record's own state column and moves by transition. See
	// RecordPatchRequestDecision.
	Decision *RecordPatchRequestDecision

	// DecidedAt is declared by a transition's stamp rather than by the
	// properties block: the engine writes it when the move it stamps is
	// performed.
	DecidedAt *string
}

// RecordPatchRequestOp is a declared enum: the admissible set, in declaration
// order.
//
// the change verb — patch (default when absent), create, or delete
type RecordPatchRequestOp string

const (
	RecordPatchRequestOpCreate RecordPatchRequestOp = "create"
	RecordPatchRequestOpPatch  RecordPatchRequestOp = "patch"
	RecordPatchRequestOpDelete RecordPatchRequestOp = "delete"
)

// RecordPatchRequestOpValues are the declared values in declaration order,
// which is render order.
var RecordPatchRequestOpValues = []string{"create", "patch", "delete"}

// Valid reports whether v is one of the declared values.
func (v RecordPatchRequestOp) Valid() bool { return Declared(RecordPatchRequestOpValues, string(v)) }

// RecordPatchRequestDecision is the state of the `decision` machine.
//
// A STATE IS NOT A PROPERTY VALUE: it lives in the record's own state column
// and moves by transition, never by assignment. The declared states, the
// initial one and the legal moves are the constants and tables here; the field
// on the properties struct carries what a read reported, which is why Decode
// admits the key and Properties writes it back.
//
// proposed until somebody decides; accepting is what applies the change
type RecordPatchRequestDecision string

const (
	RecordPatchRequestDecisionProposed RecordPatchRequestDecision = "proposed"
	RecordPatchRequestDecisionAccepted RecordPatchRequestDecision = "accepted"
	RecordPatchRequestDecisionRejected RecordPatchRequestDecision = "rejected"
)

// RecordPatchRequestDecisionValues are the declared states in declaration
// order.
var RecordPatchRequestDecisionValues = []string{"proposed", "accepted", "rejected"}

// RecordPatchRequestDecisionInitial is the state a creation is born into.
const RecordPatchRequestDecisionInitial = RecordPatchRequestDecisionProposed

// RecordPatchRequestDecisionTransitions are the declared moves, in declaration
// order. A move absent from this table is not performable: nothing else gates
// one, since a transition carries no guard.
var RecordPatchRequestDecisionTransitions = []StateTransition{
	{From: "proposed", To: "accepted", Stamps: map[string]string{"decidedAt": "now"}, OnEnter: "applyDiff"},
	{From: "proposed", To: "rejected", Stamps: map[string]string{"decidedAt": "now"}},
}

// Valid reports whether v is one of the declared states.
func (v RecordPatchRequestDecision) Valid() bool {
	return Declared(RecordPatchRequestDecisionValues, string(v))
}

// RecordPatchRequestDecisionCanMove reports whether from -> to is a declared
// move of the `decision` machine.
func RecordPatchRequestDecisionCanMove(from, to RecordPatchRequestDecision) bool {
	for _, t := range RecordPatchRequestDecisionTransitions {
		if t.From == string(from) && t.To == string(to) {
			return true
		}
	}
	return false
}

// RecordPatchRequestKeys is the admitted key set: every property
// core.substrate.reamde.dev/recordpatchrequest declares, sorted. A key outside
// it is refused by Decode, which is what replaces a hand-kept list of admitted
// keys in Go.
var RecordPatchRequestKeys = []string{"decidedAt", "decision", "diff", "op", "rationale", "targetId", "targetKind", "targetVersion"}

// DecodeRecordPatchRequest decodes an authored properties map into
// RecordPatchRequest, refusing anything the declaration does not admit: an
// undeclared key, a value of the wrong type, an enum or state outside its set,
// a number outside its range, a required property left absent. The value is
// nil unless the problems are empty, so a half-decoded record can never reach
// a caller.
//
// Structural only. Whether the referent of a reference exists, whether a
// transition is legal from where the record stands, and whether this writer
// may write a managed property are the engine's questions, not this package's.
func DecodeRecordPatchRequest(props map[string]any) (*RecordPatchRequest, []Problem) {
	d := &decoder{}
	out, _ := decodeRecordPatchRequest(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeRecordPatchRequestOp decodes a declared RecordPatchRequestOp value.
func decodeRecordPatchRequestOp(d *decoder, path string, v any) (RecordPatchRequestOp, bool) {
	s, ok := d.text(path, v, RecordPatchRequestOpValues, nil)
	if !ok {
		return "", false
	}
	return RecordPatchRequestOp(s), true
}

// decodeRecordPatchRequestDecision decodes a declared state of the `decision` machine.
func decodeRecordPatchRequestDecision(d *decoder, path string, v any) (RecordPatchRequestDecision, bool) {
	s, ok := d.text(path, v, RecordPatchRequestDecisionValues, nil)
	if !ok {
		return "", false
	}
	return RecordPatchRequestDecision(s), true
}

// decodeRecordPatchRequest decodes one RecordPatchRequest value at path.
func decodeRecordPatchRequest(d *decoder, path string, v any) (RecordPatchRequest, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return RecordPatchRequest{}, false
	}
	var out RecordPatchRequest
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "op":
			p := at(path, "op")
			if e, ok := decodeRecordPatchRequestOp(d, p, props[key]); ok {
				out.Op = &e
			}
		case "targetKind":
			p := at(path, "targetKind")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.TargetKind = &e
			}
		case "targetId":
			p := at(path, "targetId")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.TargetId = &e
			}
		case "targetVersion":
			p := at(path, "targetVersion")
			if e, ok := d.integer(p, props[key], Bounds{}); ok {
				out.TargetVersion = &e
			}
		case "diff":
			p := at(path, "diff")
			if e, ok := d.dynamic(p, props[key]); ok {
				out.Diff = e
			}
		case "rationale":
			p := at(path, "rationale")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Rationale = &e
			}
		case "decision":
			p := at(path, "decision")
			if e, ok := decodeRecordPatchRequestDecision(d, p, props[key]); ok {
				out.Decision = &e
			}
		case "decidedAt":
			p := at(path, "decidedAt")
			if e, ok := d.instant(p, props[key]); ok {
				out.DecidedAt = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/recordpatchrequest")
		}
	}
	return out, true
}

// Properties is RecordPatchRequest as the properties map holds it, and
// DecodeRecordPatchRequest's exact inverse: a nil pointer, a nil slice and a
// nil map each omit their key, so absence survives the round trip.
func (v *RecordPatchRequest) Properties() map[string]any {
	out := map[string]any{}
	if v.Op != nil {
		out["op"] = string(*v.Op)
	}
	if v.TargetKind != nil {
		out["targetKind"] = *v.TargetKind
	}
	if v.TargetId != nil {
		out["targetId"] = *v.TargetId
	}
	if v.TargetVersion != nil {
		out["targetVersion"] = *v.TargetVersion
	}
	if v.Diff != nil {
		out["diff"] = v.Diff
	}
	if v.Rationale != nil {
		out["rationale"] = *v.Rationale
	}
	if v.Decision != nil {
		out["decision"] = string(*v.Decision)
	}
	if v.DecidedAt != nil {
		out["decidedAt"] = *v.DecidedAt
	}
	return out
}

// DecidedAtTime is DecidedAt parsed. The stored form is the string, so this is
// a reading of it and never a second source of truth; an absent value reads as
// the zero time with no error, because absence is not a malformed instant.
func (v *RecordPatchRequest) DecidedAtTime() (time.Time, error) {
	if v.DecidedAt == nil {
		return time.Time{}, nil
	}
	return time.Parse(time.RFC3339, *v.DecidedAt)
}
