// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

import (
	"time"
)

// RecordMergeRequest is core.substrate.reamde.dev/recordmergerequest as its
// declaration admits it.
//
// A proposed merge of two records, waiting for the owner. A duplicate detector
// or an app writes one and accepting the decision is what performs the merge;
// the row is also the rejection memory, since an existing request suppresses
// re-suggesting the pair.
type RecordMergeRequest struct {
	// Rationale is why the writer proposes this merge, one human sentence.
	Rationale *string

	// Evidence is the signals that matched and their scores.
	Evidence Dynamic

	// Decision is proposed until somebody decides; accepting is what performs
	// the merge. A state is NOT stored in properties: it lives in the record's
	// own state column and moves by transition. See
	// RecordMergeRequestDecision.
	Decision *RecordMergeRequestDecision

	// DecidedAt is declared by a transition's stamp rather than by the
	// properties block: the engine writes it when the move it stamps is
	// performed.
	DecidedAt *string
}

// RecordMergeRequestDecision is the state of the `decision` machine.
//
// A STATE IS NOT A PROPERTY VALUE: it lives in the record's own state column
// and moves by transition, never by assignment. The declared states, the
// initial one and the legal moves are the constants and tables here; the field
// on the properties struct carries what a read reported, which is why Decode
// admits the key and Properties writes it back.
//
// proposed until somebody decides; accepting is what performs the merge
type RecordMergeRequestDecision string

const (
	RecordMergeRequestDecisionProposed RecordMergeRequestDecision = "proposed"
	RecordMergeRequestDecisionAccepted RecordMergeRequestDecision = "accepted"
	RecordMergeRequestDecisionRejected RecordMergeRequestDecision = "rejected"
)

// RecordMergeRequestDecisionValues are the declared states in declaration
// order.
var RecordMergeRequestDecisionValues = []string{"proposed", "accepted", "rejected"}

// RecordMergeRequestDecisionInitial is the state a creation is born into.
const RecordMergeRequestDecisionInitial = RecordMergeRequestDecisionProposed

// RecordMergeRequestDecisionTransitions are the declared moves, in declaration
// order. A move absent from this table is not performable: nothing else gates
// one, since a transition carries no guard.
var RecordMergeRequestDecisionTransitions = []StateTransition{
	{From: "proposed", To: "accepted", Stamps: map[string]string{"decidedAt": "now"}, OnEnter: "applyMerge"},
	{From: "proposed", To: "rejected", Stamps: map[string]string{"decidedAt": "now"}},
}

// Valid reports whether v is one of the declared states.
func (v RecordMergeRequestDecision) Valid() bool {
	return Declared(RecordMergeRequestDecisionValues, string(v))
}

// RecordMergeRequestDecisionCanMove reports whether from -> to is a declared
// move of the `decision` machine.
func RecordMergeRequestDecisionCanMove(from, to RecordMergeRequestDecision) bool {
	for _, t := range RecordMergeRequestDecisionTransitions {
		if t.From == string(from) && t.To == string(to) {
			return true
		}
	}
	return false
}

// RecordMergeRequestKeys is the admitted key set: every property
// core.substrate.reamde.dev/recordmergerequest declares, sorted. A key outside
// it is refused by Decode, which is what replaces a hand-kept list of admitted
// keys in Go.
var RecordMergeRequestKeys = []string{"decidedAt", "decision", "evidence", "rationale"}

// DecodeRecordMergeRequest decodes a properties map into RecordMergeRequest,
// refusing what the declaration cannot hold: an undeclared key, a value of the
// wrong type, an enum or state outside its set, a number outside its declared
// range or beyond exact integer precision, a key breaking a keyed map's
// contract. The value is nil unless the problems are empty, so a half-decoded
// record can never reach a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — RecordMergeRequestRequired and Missing are
// where requiredness lives.
func DecodeRecordMergeRequest(props map[string]any) (*RecordMergeRequest, []Problem) {
	d := &decoder{}
	out, _ := decodeRecordMergeRequest(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeRecordMergeRequestDecision decodes a declared state of the `decision` machine.
func decodeRecordMergeRequestDecision(d *decoder, path string, v any) (RecordMergeRequestDecision, bool) {
	s, ok := d.text(path, v, RecordMergeRequestDecisionValues, nil)
	if !ok {
		return "", false
	}
	return RecordMergeRequestDecision(s), true
}

// decodeRecordMergeRequest decodes one RecordMergeRequest value at path.
func decodeRecordMergeRequest(d *decoder, path string, v any) (RecordMergeRequest, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return RecordMergeRequest{}, false
	}
	var out RecordMergeRequest
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "rationale":
			p := at(path, "rationale")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Rationale = &e
			}
		case "evidence":
			p := at(path, "evidence")
			if e, ok := d.dynamic(p, props[key]); ok {
				out.Evidence = e
			}
		case "decision":
			p := at(path, "decision")
			if e, ok := decodeRecordMergeRequestDecision(d, p, props[key]); ok {
				out.Decision = &e
			}
		case "decidedAt":
			p := at(path, "decidedAt")
			if e, ok := d.instant(p, props[key]); ok {
				out.DecidedAt = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/recordmergerequest")
		}
	}
	return out, true
}

// Encode is RecordMergeRequest as the properties map holds it, and
// DecodeRecordMergeRequest's exact inverse: a nil pointer, a nil slice and a
// nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *RecordMergeRequest) Encode() map[string]any {
	out := map[string]any{}
	if v.Rationale != nil {
		out["rationale"] = *v.Rationale
	}
	if v.Evidence != nil {
		out["evidence"] = v.Evidence
	}
	if v.Decision != nil {
		out["decision"] = string(*v.Decision)
	}
	if v.DecidedAt != nil {
		out["decidedAt"] = *v.DecidedAt
	}
	return out
}

// DecidedAtTime is DecidedAt parsed. The stored form is the string, so this is
// a reading of it and never a second source of truth; an absent value reads as
// the zero time with no error, because absence is not a malformed instant.
func (v *RecordMergeRequest) DecidedAtTime() (time.Time, error) {
	if v.DecidedAt == nil {
		return time.Time{}, nil
	}
	return time.Parse(time.RFC3339, *v.DecidedAt)
}
