// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// RecordMerge is core.substrate.reamde.dev/recordmerge as its declaration
// admits it.
//
// One performed merge of two records, and what it moved. Command-as-record:
// creating it performs the merge, nothing waits on a decision, and the loser
// is tombstoned rather than erased so the recorded moves can be undone by a
// split.
type RecordMerge struct {
	// Moved is the edges and properties the merge moved, what a split reads
	// back.
	Moved Dynamic
}

// RecordMergeKeys is the admitted key set: every property
// core.substrate.reamde.dev/recordmerge declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var RecordMergeKeys = []string{"moved"}

// DecodeRecordMerge decodes a properties map into RecordMerge, refusing what
// the declaration cannot hold: an undeclared key, a value of the wrong type,
// an enum or state outside its set, a number outside its declared range or
// beyond exact integer precision, a key breaking a keyed map's contract. The
// value is nil unless the problems are empty, so a half-decoded record can
// never reach a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — RecordMergeRequired and Missing are where
// requiredness lives.
func DecodeRecordMerge(props map[string]any) (*RecordMerge, []Problem) {
	d := &decoder{}
	out, _ := decodeRecordMerge(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeRecordMerge decodes one RecordMerge value at path.
func decodeRecordMerge(d *decoder, path string, v any) (RecordMerge, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return RecordMerge{}, false
	}
	var out RecordMerge
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "moved":
			p := at(path, "moved")
			if e, ok := d.dynamic(p, props[key]); ok {
				out.Moved = e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/recordmerge")
		}
	}
	return out, true
}

// Properties is RecordMerge as the properties map holds it, and
// DecodeRecordMerge's exact inverse: a nil pointer, a nil slice and a nil map
// each omit their key, so absence survives the round trip.
func (v *RecordMerge) Properties() map[string]any {
	out := map[string]any{}
	if v.Moved != nil {
		out["moved"] = v.Moved
	}
	return out
}
