// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// RecordMapping is core.substrate.reamde.dev/recordmapping as its declaration
// admits it.
//
// One declared mapping: how a source record's properties reach the subject its
// edge points at, so a Google contact keeps a person up to date. One mapping
// per source kind, declared by the authority that owns that kind.
type RecordMapping struct {
	// Version is this declaration's version.
	Version *string

	// Name is the mapping's local name.
	Name *string

	// Authority is the authority that declares it, the source type's own.
	Authority *string

	// From is the source type whose records project.
	From *string

	// To is the subject type, always a full type name.
	To *string

	// Edge is the declared edge on the source type that records the link.
	Edge *string

	// Definition is the parsed manifest data.
	Definition Dynamic
}

// RecordMappingKeys is the admitted key set: every property
// core.substrate.reamde.dev/recordmapping declares, sorted. A key outside it
// is refused by Decode, which is what replaces a hand-kept list of admitted
// keys in Go.
var RecordMappingKeys = []string{"authority", "definition", "edge", "from", "name", "to", "version"}

// DecodeRecordMapping decodes a properties map into RecordMapping, refusing
// what the declaration cannot hold: an undeclared key, a value of the wrong
// type, an enum or state outside its set, a number outside its declared range
// or beyond exact integer precision, a key breaking a keyed map's contract.
// The value is nil unless the problems are empty, so a half-decoded record can
// never reach a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — RecordMappingRequired and Missing are where
// requiredness lives.
func DecodeRecordMapping(props map[string]any) (*RecordMapping, []Problem) {
	d := &decoder{}
	out, _ := decodeRecordMapping(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeRecordMapping decodes one RecordMapping value at path.
func decodeRecordMapping(d *decoder, path string, v any) (RecordMapping, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return RecordMapping{}, false
	}
	var out RecordMapping
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "version":
			p := at(path, "version")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Version = &e
			}
		case "name":
			p := at(path, "name")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Name = &e
			}
		case "authority":
			p := at(path, "authority")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Authority = &e
			}
		case "from":
			p := at(path, "from")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.From = &e
			}
		case "to":
			p := at(path, "to")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.To = &e
			}
		case "edge":
			p := at(path, "edge")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Edge = &e
			}
		case "definition":
			p := at(path, "definition")
			if e, ok := d.dynamic(p, props[key]); ok {
				out.Definition = e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/recordmapping")
		}
	}
	return out, true
}

// Properties is RecordMapping as the properties map holds it, and
// DecodeRecordMapping's exact inverse: a nil pointer, a nil slice and a nil
// map each omit their key, so absence survives the round trip.
func (v *RecordMapping) Properties() map[string]any {
	out := map[string]any{}
	if v.Version != nil {
		out["version"] = *v.Version
	}
	if v.Name != nil {
		out["name"] = *v.Name
	}
	if v.Authority != nil {
		out["authority"] = *v.Authority
	}
	if v.From != nil {
		out["from"] = *v.From
	}
	if v.To != nil {
		out["to"] = *v.To
	}
	if v.Edge != nil {
		out["edge"] = *v.Edge
	}
	if v.Definition != nil {
		out["definition"] = v.Definition
	}
	return out
}
