// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// RecordPatchPolicy is core.substrate.reamde.dev/recordpatchpolicy as its
// declaration admits it.
//
// One rule for agent writes: which kinds, ops and agents it speaks for, and
// whether their writes land, gate into recordpatchrequests, or refuse. The
// most restrictive matching policy wins; no match means the write lands.
type RecordPatchPolicy struct {
	// Selector is the writes this policy speaks for; empty lists match all.
	Selector *RecordPatchPolicySelector

	// Action is what a matched write does — land, convert into a request, or
	// bounce.
	Action *RecordPatchPolicyAction

	// Judge is the agent that judges what this policy gates; absent means the
	// owner decides everything. Points at core.substrate.reamde.dev/agent.
	Judge *ReferencePath

	// Criteria is the owner's instructions to the judge, in prose.
	Criteria *string

	// Context is how much the judge reads — the frozen envelope alone
	// (default), or the proposing thread's recent turns beside it.
	Context *RecordPatchPolicyContext

	// AutoAccept is judge confidence at or above accepts the gated request, an
	// `accept` verdict only; absent means the judge never accepts.
	AutoAccept *float64

	// AutoRefuse is judge confidence at or above rejects it, a `reject`
	// verdict only; absent means the judge never rejects; wins over
	// `autoAccept` where both floors are cleared.
	AutoRefuse *float64

	// Mode is enforce decides within the thresholds; advise only ever
	// recommends.
	Mode *RecordPatchPolicyMode

	// Disabled is a disabled policy matches nothing.
	Disabled *bool
}

// RecordPatchPolicyAction is a declared enum: the admissible set, in
// declaration order.
//
// what a matched write does — land, convert into a request, or bounce
type RecordPatchPolicyAction string

const (
	RecordPatchPolicyActionAllow  RecordPatchPolicyAction = "allow"
	RecordPatchPolicyActionGate   RecordPatchPolicyAction = "gate"
	RecordPatchPolicyActionRefuse RecordPatchPolicyAction = "refuse"
)

// RecordPatchPolicyActionValues are the declared values in declaration order,
// which is render order.
var RecordPatchPolicyActionValues = []string{"allow", "gate", "refuse"}

// Valid reports whether v is one of the declared values.
func (v RecordPatchPolicyAction) Valid() bool {
	return Declared(RecordPatchPolicyActionValues, string(v))
}

// RecordPatchPolicyContext is a declared enum: the admissible set, in
// declaration order.
//
// how much the judge reads — the frozen envelope alone (default), or the
// proposing thread's recent turns beside it
type RecordPatchPolicyContext string

const (
	RecordPatchPolicyContextEnvelope RecordPatchPolicyContext = "envelope"
	RecordPatchPolicyContextThread   RecordPatchPolicyContext = "thread"
)

// RecordPatchPolicyContextValues are the declared values in declaration order,
// which is render order.
var RecordPatchPolicyContextValues = []string{"envelope", "thread"}

// Valid reports whether v is one of the declared values.
func (v RecordPatchPolicyContext) Valid() bool {
	return Declared(RecordPatchPolicyContextValues, string(v))
}

// RecordPatchPolicyMode is a declared enum: the admissible set, in declaration
// order.
//
// enforce decides within the thresholds; advise only ever recommends
type RecordPatchPolicyMode string

const (
	RecordPatchPolicyModeEnforce RecordPatchPolicyMode = "enforce"
	RecordPatchPolicyModeAdvise  RecordPatchPolicyMode = "advise"
)

// RecordPatchPolicyModeValues are the declared values in declaration order,
// which is render order.
var RecordPatchPolicyModeValues = []string{"enforce", "advise"}

// Valid reports whether v is one of the declared values.
func (v RecordPatchPolicyMode) Valid() bool { return Declared(RecordPatchPolicyModeValues, string(v)) }

// RecordPatchPolicyKeys is the admitted key set: every property
// core.substrate.reamde.dev/recordpatchpolicy declares, sorted. A key outside
// it is refused by Decode, which is what replaces a hand-kept list of admitted
// keys in Go.
var RecordPatchPolicyKeys = []string{"action", "autoAccept", "autoRefuse", "context", "criteria", "disabled", "judge", "mode", "selector"}

// DecodeRecordPatchPolicy decodes a properties map into RecordPatchPolicy,
// refusing what the declaration cannot hold: an undeclared key, a value of the
// wrong type, an enum or state outside its set, a number outside its declared
// range or beyond exact integer precision, a key breaking a keyed map's
// contract. The value is nil unless the problems are empty, so a half-decoded
// record can never reach a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — RecordPatchPolicyRequired and Missing are
// where requiredness lives.
func DecodeRecordPatchPolicy(props map[string]any) (*RecordPatchPolicy, []Problem) {
	d := &decoder{}
	out, _ := decodeRecordPatchPolicy(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// RecordPatchPolicyRequired names the properties the declaration marks
// `required:`, sorted. It is a FORM-LEVEL contract: the write path does not
// enforce it, so Decode admits a value that leaves one absent and this is what
// a client checks before it submits one.
var RecordPatchPolicyRequired = []string{"action"}

// Missing names the required properties this value leaves absent, in
// declaration order. Empty means every declared requirement is answered —
// not that the value is admissible, which is the substrate's answer and not a
// type's.
func (v *RecordPatchPolicy) Missing() []string {
	var out []string
	if v.Action == nil {
		out = append(out, "action")
	}
	return out
}

// decodeRecordPatchPolicyAction decodes a declared RecordPatchPolicyAction value.
func decodeRecordPatchPolicyAction(d *decoder, path string, v any) (RecordPatchPolicyAction, bool) {
	s, ok := d.text(path, v, RecordPatchPolicyActionValues, nil)
	if !ok {
		return "", false
	}
	return RecordPatchPolicyAction(s), true
}

// decodeRecordPatchPolicyContext decodes a declared RecordPatchPolicyContext value.
func decodeRecordPatchPolicyContext(d *decoder, path string, v any) (RecordPatchPolicyContext, bool) {
	s, ok := d.text(path, v, RecordPatchPolicyContextValues, nil)
	if !ok {
		return "", false
	}
	return RecordPatchPolicyContext(s), true
}

// decodeRecordPatchPolicyMode decodes a declared RecordPatchPolicyMode value.
func decodeRecordPatchPolicyMode(d *decoder, path string, v any) (RecordPatchPolicyMode, bool) {
	s, ok := d.text(path, v, RecordPatchPolicyModeValues, nil)
	if !ok {
		return "", false
	}
	return RecordPatchPolicyMode(s), true
}

// decodeRecordPatchPolicy decodes one RecordPatchPolicy value at path.
func decodeRecordPatchPolicy(d *decoder, path string, v any) (RecordPatchPolicy, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return RecordPatchPolicy{}, false
	}
	var out RecordPatchPolicy
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "selector":
			p := at(path, "selector")
			if e, ok := decodeRecordPatchPolicySelector(d, p, props[key]); ok {
				out.Selector = &e
			}
		case "action":
			p := at(path, "action")
			if e, ok := decodeRecordPatchPolicyAction(d, p, props[key]); ok {
				out.Action = &e
			}
		case "judge":
			p := at(path, "judge")
			if e, ok := d.reference(p, props[key], "core.substrate.reamde.dev/agent"); ok {
				out.Judge = &e
			}
		case "criteria":
			p := at(path, "criteria")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Criteria = &e
			}
		case "context":
			p := at(path, "context")
			if e, ok := decodeRecordPatchPolicyContext(d, p, props[key]); ok {
				out.Context = &e
			}
		case "autoAccept":
			p := at(path, "autoAccept")
			if e, ok := d.number(p, props[key], Bounds{Min: bound(0), Max: bound(1)}); ok {
				out.AutoAccept = &e
			}
		case "autoRefuse":
			p := at(path, "autoRefuse")
			if e, ok := d.number(p, props[key], Bounds{Min: bound(0), Max: bound(1)}); ok {
				out.AutoRefuse = &e
			}
		case "mode":
			p := at(path, "mode")
			if e, ok := decodeRecordPatchPolicyMode(d, p, props[key]); ok {
				out.Mode = &e
			}
		case "disabled":
			p := at(path, "disabled")
			if e, ok := d.flag(p, props[key]); ok {
				out.Disabled = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/recordpatchpolicy")
		}
	}
	return out, true
}

// Encode is RecordPatchPolicy as the properties map holds it, and
// DecodeRecordPatchPolicy's exact inverse: a nil pointer, a nil slice and a
// nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *RecordPatchPolicy) Encode() map[string]any {
	out := map[string]any{}
	if v.Selector != nil {
		out["selector"] = v.Selector.Encode()
	}
	if v.Action != nil {
		out["action"] = string(*v.Action)
	}
	if v.Judge != nil {
		out["judge"] = string(*v.Judge)
	}
	if v.Criteria != nil {
		out["criteria"] = *v.Criteria
	}
	if v.Context != nil {
		out["context"] = string(*v.Context)
	}
	if v.AutoAccept != nil {
		out["autoAccept"] = *v.AutoAccept
	}
	if v.AutoRefuse != nil {
		out["autoRefuse"] = *v.AutoRefuse
	}
	if v.Mode != nil {
		out["mode"] = string(*v.Mode)
	}
	if v.Disabled != nil {
		out["disabled"] = *v.Disabled
	}
	return out
}

// RecordPatchPolicySelector is one value of the `selector` object declared on
// core.substrate.reamde.dev/recordpatchpolicy.
//
// the writes this policy speaks for; empty lists match all
type RecordPatchPolicySelector struct {
	// Kinds is kind references, `<authority>/*` or `*`; empty means every
	// kind.
	Kinds []string

	// Ops is the write verb matched: put, patch or delete, the three policy
	// evaluates (link, unlink, merge and split are outside it), never a
	// trigger's create/update/delete; empty means all three.
	Ops []RecordPatchPolicySelectorOps

	// Agents is agent identities; empty means every agent.
	Agents []string
}

// RecordPatchPolicySelectorOps is a declared enum: the admissible set, in
// declaration order.
//
// the write verb matched: put, patch or delete, the three policy evaluates
// (link, unlink, merge and split are outside it), never a trigger's
// create/update/delete; empty means all three
type RecordPatchPolicySelectorOps string

const (
	RecordPatchPolicySelectorOpsPut    RecordPatchPolicySelectorOps = "put"
	RecordPatchPolicySelectorOpsPatch  RecordPatchPolicySelectorOps = "patch"
	RecordPatchPolicySelectorOpsDelete RecordPatchPolicySelectorOps = "delete"
)

// RecordPatchPolicySelectorOpsValues are the declared values in declaration
// order, which is render order.
var RecordPatchPolicySelectorOpsValues = []string{"put", "patch", "delete"}

// Valid reports whether v is one of the declared values.
func (v RecordPatchPolicySelectorOps) Valid() bool {
	return Declared(RecordPatchPolicySelectorOpsValues, string(v))
}

// decodeRecordPatchPolicySelectorOps decodes a declared RecordPatchPolicySelectorOps value.
func decodeRecordPatchPolicySelectorOps(d *decoder, path string, v any) (RecordPatchPolicySelectorOps, bool) {
	s, ok := d.text(path, v, RecordPatchPolicySelectorOpsValues, nil)
	if !ok {
		return "", false
	}
	return RecordPatchPolicySelectorOps(s), true
}

// decodeRecordPatchPolicySelector decodes one RecordPatchPolicySelector value at path.
func decodeRecordPatchPolicySelector(d *decoder, path string, v any) (RecordPatchPolicySelector, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return RecordPatchPolicySelector{}, false
	}
	var out RecordPatchPolicySelector
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "kinds":
			p := at(path, "kinds")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Kinds = list
			}
		case "ops":
			p := at(path, "ops")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]RecordPatchPolicySelectorOps, 0, len(items))
				for i, item := range items {
					if e, ok := decodeRecordPatchPolicySelectorOps(d, index(p, i), item); ok {
						list = append(list, e)
					}
				}
				out.Ops = list
			}
		case "agents":
			p := at(path, "agents")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Agents = list
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/recordpatchpolicy")
		}
	}
	return out, true
}

// Encode is RecordPatchPolicySelector as the properties map holds it, and
// decodeRecordPatchPolicySelector's exact inverse: a nil pointer, a nil slice
// and a nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *RecordPatchPolicySelector) Encode() map[string]any {
	out := map[string]any{}
	if v.Kinds != nil {
		items := make([]any, 0, len(v.Kinds))
		for i := range v.Kinds {
			items = append(items, v.Kinds[i])
		}
		out["kinds"] = items
	}
	if v.Ops != nil {
		items := make([]any, 0, len(v.Ops))
		for i := range v.Ops {
			items = append(items, string(v.Ops[i]))
		}
		out["ops"] = items
	}
	if v.Agents != nil {
		items := make([]any, 0, len(v.Agents))
		for i := range v.Agents {
			items = append(items, v.Agents[i])
		}
		out["agents"] = items
	}
	return out
}
