// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// RecordSplit is core.substrate.reamde.dev/recordsplit as its declaration
// admits it.
//
// The undo of one merge, performed on creation exactly as the merge was. It
// names the recordmerge it reverses and reads that merge's recorded moves to
// put every edge and property back where it came from.
type RecordSplit struct {
	// Result is what the split put back where.
	Result Dynamic
}

// RecordSplitKeys is the admitted key set: every property
// core.substrate.reamde.dev/recordsplit declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var RecordSplitKeys = []string{"result"}

// DecodeRecordSplit decodes a properties map into RecordSplit, refusing what
// the declaration cannot hold: an undeclared key, a value of the wrong type,
// an enum or state outside its set, a number outside its declared range or
// beyond exact integer precision, a key breaking a keyed map's contract. The
// value is nil unless the problems are empty, so a half-decoded record can
// never reach a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — RecordSplitRequired and Missing are where
// requiredness lives.
func DecodeRecordSplit(props map[string]any) (*RecordSplit, []Problem) {
	d := &decoder{}
	out, _ := decodeRecordSplit(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeRecordSplit decodes one RecordSplit value at path.
func decodeRecordSplit(d *decoder, path string, v any) (RecordSplit, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return RecordSplit{}, false
	}
	var out RecordSplit
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "result":
			p := at(path, "result")
			if e, ok := d.dynamic(p, props[key]); ok {
				out.Result = e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/recordsplit")
		}
	}
	return out, true
}

// Properties is RecordSplit as the properties map holds it, and
// DecodeRecordSplit's exact inverse: a nil pointer, a nil slice and a nil map
// each omit their key, so absence survives the round trip.
func (v *RecordSplit) Properties() map[string]any {
	out := map[string]any{}
	if v.Result != nil {
		out["result"] = v.Result
	}
	return out
}
