// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// RecoveryKey is core.substrate.reamde.dev/recoverykey as its declaration
// admits it.
//
// The repository's one recovery key, id `self`: the age recipient the user
// enrolled and the repository's data-encryption key wrapped to it. Only the
// matching age identity, which the user keeps and the substrate never stores,
// opens the wrap.
type RecoveryKey struct {
	// Algorithm is the recovery scheme; age-x25519-v1 in this release.
	Algorithm *string

	// PublicKey is the age recipient the data-encryption key is wrapped to.
	PublicKey *string

	// SealedKey is the repository's data-encryption key wrapped to the
	// recipient; only the matching age identity opens it.
	SealedKey *string
}

// RecoveryKeyKeys is the admitted key set: every property
// core.substrate.reamde.dev/recoverykey declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var RecoveryKeyKeys = []string{"algorithm", "publicKey", "sealedKey"}

// DecodeRecoveryKey decodes an authored properties map into RecoveryKey,
// refusing anything the declaration does not admit: an undeclared key, a value
// of the wrong type, an enum or state outside its set, a number outside its
// range, a required property left absent. The value is nil unless the problems
// are empty, so a half-decoded record can never reach a caller.
//
// Structural only. Whether the referent of a reference exists, whether a
// transition is legal from where the record stands, and whether this writer
// may write a managed property are the engine's questions, not this package's.
func DecodeRecoveryKey(props map[string]any) (*RecoveryKey, []Problem) {
	d := &decoder{}
	out, _ := decodeRecoveryKey(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeRecoveryKey decodes one RecoveryKey value at path.
func decodeRecoveryKey(d *decoder, path string, v any) (RecoveryKey, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return RecoveryKey{}, false
	}
	var out RecoveryKey
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "algorithm":
			p := at(path, "algorithm")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Algorithm = &e
			}
		case "publicKey":
			p := at(path, "publicKey")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.PublicKey = &e
			}
		case "sealedKey":
			p := at(path, "sealedKey")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.SealedKey = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/recoverykey")
		}
	}
	return out, true
}

// Properties is RecoveryKey as the properties map holds it, and
// DecodeRecoveryKey's exact inverse: a nil pointer, a nil slice and a nil map
// each omit their key, so absence survives the round trip.
func (v *RecoveryKey) Properties() map[string]any {
	out := map[string]any{}
	if v.Algorithm != nil {
		out["algorithm"] = *v.Algorithm
	}
	if v.PublicKey != nil {
		out["publicKey"] = *v.PublicKey
	}
	if v.SealedKey != nil {
		out["sealedKey"] = *v.SealedKey
	}
	return out
}
