// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// Repository is core.substrate.reamde.dev/repository as its declaration admits
// it.
//
// The repository's own read-only description of itself — one record, the
// store you are reading. The control-plane row is the truth and this is its
// projection inside the repository, so a client that only speaks the record
// API can still say where it is.
type Repository struct {
	// Name is the username this repository belongs to.
	Name *string

	// Lifecycle is active until the operator suspends it. A state is NOT
	// stored in properties: it lives in the record's own state column and
	// moves by transition. See RepositoryLifecycle.
	Lifecycle *RepositoryLifecycle
}

// RepositoryLifecycle is the state of the `lifecycle` machine.
//
// A STATE IS NOT A PROPERTY VALUE: it lives in the record's own state column
// and moves by transition, never by assignment. The declared states, the
// initial one and the legal moves are the constants and tables here; the field
// on the properties struct carries what a read reported, which is why Decode
// admits the key and Properties writes it back.
//
// active until the operator suspends it
type RepositoryLifecycle string

const (
	RepositoryLifecycleActive    RepositoryLifecycle = "active"
	RepositoryLifecycleSuspended RepositoryLifecycle = "suspended"
	RepositoryLifecycleDeleting  RepositoryLifecycle = "deleting"
)

// RepositoryLifecycleValues are the declared states in declaration order.
var RepositoryLifecycleValues = []string{"active", "suspended", "deleting"}

// RepositoryLifecycleInitial is the state a creation is born into.
const RepositoryLifecycleInitial = RepositoryLifecycleActive

// RepositoryLifecycleTransitions are the declared moves, in declaration order.
// A move absent from this table is not performable: nothing else gates one,
// since a transition carries no guard.
var RepositoryLifecycleTransitions = []StateTransition{
	{From: "active", To: "suspended"},
	{From: "suspended", To: "active"},
}

// Valid reports whether v is one of the declared states.
func (v RepositoryLifecycle) Valid() bool { return Declared(RepositoryLifecycleValues, string(v)) }

// RepositoryLifecycleCanMove reports whether from -> to is a declared move of
// the `lifecycle` machine.
func RepositoryLifecycleCanMove(from, to RepositoryLifecycle) bool {
	for _, t := range RepositoryLifecycleTransitions {
		if t.From == string(from) && t.To == string(to) {
			return true
		}
	}
	return false
}

// RepositoryKeys is the admitted key set: every property
// core.substrate.reamde.dev/repository declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var RepositoryKeys = []string{"lifecycle", "name"}

// DecodeRepository decodes a properties map into Repository, refusing what the
// declaration cannot hold: an undeclared key, a value of the wrong type, an
// enum or state outside its set, a number outside its declared range or beyond
// exact integer precision, a key breaking a keyed map's contract. The value is
// nil unless the problems are empty, so a half-decoded record can never reach
// a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — RepositoryRequired and Missing are where
// requiredness lives.
func DecodeRepository(props map[string]any) (*Repository, []Problem) {
	d := &decoder{}
	out, _ := decodeRepository(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeRepositoryLifecycle decodes a declared state of the `lifecycle` machine.
func decodeRepositoryLifecycle(d *decoder, path string, v any) (RepositoryLifecycle, bool) {
	s, ok := d.text(path, v, RepositoryLifecycleValues, nil)
	if !ok {
		return "", false
	}
	return RepositoryLifecycle(s), true
}

// decodeRepository decodes one Repository value at path.
func decodeRepository(d *decoder, path string, v any) (Repository, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return Repository{}, false
	}
	var out Repository
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "name":
			p := at(path, "name")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Name = &e
			}
		case "lifecycle":
			p := at(path, "lifecycle")
			if e, ok := decodeRepositoryLifecycle(d, p, props[key]); ok {
				out.Lifecycle = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/repository")
		}
	}
	return out, true
}

// Encode is Repository as the properties map holds it, and DecodeRepository's
// exact inverse: a nil pointer, a nil slice and a nil map each omit their key,
// so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *Repository) Encode() map[string]any {
	out := map[string]any{}
	if v.Name != nil {
		out["name"] = *v.Name
	}
	if v.Lifecycle != nil {
		out["lifecycle"] = string(*v.Lifecycle)
	}
	return out
}
