// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

import (
	"time"
)

// Run is core.substrate.reamde.dev/run as its declaration admits it.
//
// One trigger delivery attempt, written by the engine after the attempt
// settles: what fired, what ran, what it applied, and why it parked. Parked
// runs are kept until their failure is retried away; the rest are pruned to
// the newest few per trigger.
type Run struct {
	// Trigger is the trigger record this delivery belongs to.
	Trigger *string

	// Callable is the callable that ran, as its actor spells it —
	// `function:<name>`.
	Callable *string

	// Mode is trigger, schedule, webhook or manual.
	Mode *string

	// Seq is the changelog seq delivered, for record-sourced runs.
	Seq *int64

	// FireId is the stable fire id, for schedule and webhook runs.
	FireId *string

	// Record is the delivered record's id, for record-sourced runs.
	Record *string

	// Status is ok (effects applied or nothing to do), skipped (the when guard
	// said no), or parked (retried out; a trigger_failures row holds the retry
	// handle).
	Status *string

	// Attempt is how many attempts the delivery burned.
	Attempt *int64

	// StartedAt is when the attempt began.
	StartedAt *string

	// FinishedAt is when the attempt settled.
	FinishedAt *string

	// Error is the last error, on parked runs.
	Error *string

	// Effects is the applied-effects summary: action → count.
	Effects map[string]int64

	// Pages is committed pages for a paged (backfill) delivery; absent for a
	// single-shot body, the durable per-chain progress lives in paged_cursors.
	Pages *int64
}

// RunKeys is the admitted key set: every property
// core.substrate.reamde.dev/run declares, sorted. A key outside it is refused
// by Decode, which is what replaces a hand-kept list of admitted keys in Go.
var RunKeys = []string{"attempt", "callable", "effects", "error", "finishedAt", "fireId", "mode", "pages", "record", "seq", "startedAt", "status", "trigger"}

// DecodeRun decodes a properties map into Run, refusing what the declaration
// cannot hold: an undeclared key, a value of the wrong type, an enum or state
// outside its set, a number outside its declared range or beyond exact integer
// precision, a key breaking a keyed map's contract. The value is nil unless
// the problems are empty, so a half-decoded record can never reach a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — RunRequired and Missing are where requiredness
// lives.
func DecodeRun(props map[string]any) (*Run, []Problem) {
	d := &decoder{}
	out, _ := decodeRun(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeRun decodes one Run value at path.
func decodeRun(d *decoder, path string, v any) (Run, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return Run{}, false
	}
	var out Run
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "trigger":
			p := at(path, "trigger")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Trigger = &e
			}
		case "callable":
			p := at(path, "callable")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Callable = &e
			}
		case "mode":
			p := at(path, "mode")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Mode = &e
			}
		case "seq":
			p := at(path, "seq")
			if e, ok := d.integer(p, props[key], Bounds{}); ok {
				out.Seq = &e
			}
		case "fireId":
			p := at(path, "fireId")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.FireId = &e
			}
		case "record":
			p := at(path, "record")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Record = &e
			}
		case "status":
			p := at(path, "status")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Status = &e
			}
		case "attempt":
			p := at(path, "attempt")
			if e, ok := d.integer(p, props[key], Bounds{}); ok {
				out.Attempt = &e
			}
		case "startedAt":
			p := at(path, "startedAt")
			if e, ok := d.instant(p, props[key]); ok {
				out.StartedAt = &e
			}
		case "finishedAt":
			p := at(path, "finishedAt")
			if e, ok := d.instant(p, props[key]); ok {
				out.FinishedAt = &e
			}
		case "error":
			p := at(path, "error")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Error = &e
			}
		case "effects":
			p := at(path, "effects")
			if entries, isMap := d.mapping(p, props[key]); isMap {
				values := make(map[string]int64, len(entries))
				for _, mk := range sortedKeys(entries) {
					if entries[mk] == nil || !d.key(p, mk, "") {
						continue
					}
					if e, ok := d.integer(at(p, mk), entries[mk], Bounds{}); ok {
						values[mk] = e
					}
				}
				out.Effects = values
			}
		case "pages":
			p := at(path, "pages")
			if e, ok := d.integer(p, props[key], Bounds{}); ok {
				out.Pages = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/run")
		}
	}
	return out, true
}

// Encode is Run as the properties map holds it, and DecodeRun's exact inverse:
// a nil pointer, a nil slice and a nil map each omit their key, so absence
// survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *Run) Encode() map[string]any {
	out := map[string]any{}
	if v.Trigger != nil {
		out["trigger"] = *v.Trigger
	}
	if v.Callable != nil {
		out["callable"] = *v.Callable
	}
	if v.Mode != nil {
		out["mode"] = *v.Mode
	}
	if v.Seq != nil {
		out["seq"] = *v.Seq
	}
	if v.FireId != nil {
		out["fireId"] = *v.FireId
	}
	if v.Record != nil {
		out["record"] = *v.Record
	}
	if v.Status != nil {
		out["status"] = *v.Status
	}
	if v.Attempt != nil {
		out["attempt"] = *v.Attempt
	}
	if v.StartedAt != nil {
		out["startedAt"] = *v.StartedAt
	}
	if v.FinishedAt != nil {
		out["finishedAt"] = *v.FinishedAt
	}
	if v.Error != nil {
		out["error"] = *v.Error
	}
	if v.Effects != nil {
		values := make(map[string]any, len(v.Effects))
		for key, item := range v.Effects {
			values[key] = item
		}
		out["effects"] = values
	}
	if v.Pages != nil {
		out["pages"] = *v.Pages
	}
	return out
}

// StartedAtTime is StartedAt parsed. The stored form is the string, so this is
// a reading of it and never a second source of truth; an absent value reads as
// the zero time with no error, because absence is not a malformed instant.
func (v *Run) StartedAtTime() (time.Time, error) {
	if v.StartedAt == nil {
		return time.Time{}, nil
	}
	return time.Parse(time.RFC3339, *v.StartedAt)
}

// FinishedAtTime is FinishedAt parsed. The stored form is the string, so this
// is a reading of it and never a second source of truth; an absent value reads
// as the zero time with no error, because absence is not a malformed instant.
func (v *Run) FinishedAtTime() (time.Time, error) {
	if v.FinishedAt == nil {
		return time.Time{}, nil
	}
	return time.Parse(time.RFC3339, *v.FinishedAt)
}
