// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

// Package corekinds is the core vocabulary as Go types: one struct per kind
// declared under kinds/core.substrate.reamde.dev, generated by cmd/kindsgen.
// The declarations are the source of truth and this package is their shadow —
// mise run kinds:gen rewrites it, and CI refuses a tree where the two disagree.
//
// Three rules are worth knowing before reading a type.
//
// THE MAP IS THE WIRE. Decode<Kind> and (*Kind).Properties are each other's
// exact inverse over map[string]any, which is the form the API, the changelog
// and jsonb all carry. There are no struct tags: a second encoder would be a
// second answer about what a property is called.
//
// AN OPTIONAL SINGLE VALUE IS A POINTER. Absence stored is absence authored,
// and a materialized zero value is the likeliest silent round-trip bug — an
// empty string written where the author wrote nothing. A required value is a
// value; slices and maps carry nil-versus-empty natively.
//
// VALIDATION HERE IS STRUCTURAL. Types, enum and state sets, required
// properties, numeric ranges, patterns, key contracts and undeclared keys. Not:
// whether a reference's referent exists, whether a transition is legal from
// where the record stands, or whether this writer may write a managed
// property. Those need the repository, and this package is a leaf that imports
// nothing.
package corekinds

import (
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
)

// Reference is a typed POINTER stored as a property value: the referent's kind
// reference and its id, the same {kind, id} pair an edge target wears.
type Reference struct {
	Kind string
	ID   string
}

// Properties is the reference as the properties map holds it.
func (r Reference) Properties() map[string]any {
	return map[string]any{"kind": r.Kind, "id": r.ID}
}

// SecretRef is what a secret property STORES: an opaque ref into the engine's
// sealed store, never the material. Reads redact even the ref, so a decoded
// value is as often Redacted as it is a ref.
type SecretRef string

// Digest is a server-minted comparator: 64 lowercase hex characters of
// SHA-256, matched in SQL and never revealed. Reads redact it too.
type Digest string

// BlobDigest names bytes in the content-addressed store by the blob record's
// id, which is the digest.
type BlobDigest string

// BlobDigestPrefix is what every blob digest starts with. It mirrors
// substrate.BlobDigestPrefix, which this package does not import: a leaf with
// no substrate imports is what lets the write path and the generator both
// depend on it.
const BlobDigestPrefix = "blob-sha256-"

// Redacted is what a sensitive property reads back as. Sending it back is a
// round trip rather than an assignment, so a decoder admits it where a digest's
// own grammar would not.
const Redacted = "<redacted>"

// Dynamic is a json property: a payload whose shape core does not own. It is an
// ALIAS rather than a named type, so a caller passes an ordinary map or slice
// without a conversion, and nil is its absence — which is why a Dynamic field
// is never a pointer.
type Dynamic = any

// Problem is one structural refusal: the property path it sits at, in the
// declaration's own spelling, and what was wrong there.
type Problem struct {
	Path    string
	Message string
}

func (p Problem) Error() string { return p.Path + ": " + p.Message }

// StateTransition is one declared move of a machine. It carries no guard:
// anyone may perform any declared move, and the stamps are the properties the
// move writes.
type StateTransition struct {
	From    string
	To      string
	Stamps  map[string]string
	OnEnter string
}

// Bounds is a declared numeric range, each half present only where the
// declaration wrote one.
type Bounds struct {
	Min *float64
	Max *float64
}

// bound is how the generated code spells a declared bound.
func bound(v float64) *float64 { return &v }

// Declared reports whether name is one of a generated key set's names: the
// membership half of every <Kind>Keys.
func Declared(keys []string, name string) bool {
	for _, k := range keys {
		if k == name {
			return true
		}
	}
	return false
}

// The contracts a keyed map's keys hold to, as anchored regular expressions.
// The grammars are vocabulary.KeyPatternRegexp's, and TestKeyContractsAgree in
// this package holds the two spellings to one answer. A keyed map's keys are
// also counted in Postgres (the narrowing guard), so a grammar that drifted
// here would be a third answer to a question that has one.
const (
	KeyPatternCamelRegexp   = `^[a-z][a-zA-Z0-9]*$`
	KeyPatternKindRefRegexp = `^([a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+/)?[a-z][a-z0-9]*$`
)

var (
	reCamel   = regexp.MustCompile(KeyPatternCamelRegexp)
	reKindRef = regexp.MustCompile(KeyPatternKindRefRegexp)
	reDigest  = regexp.MustCompile(`^[0-9a-f]{64}$`)
)

// sortedKeys is the order every decode walks a map in, so the problems a bad
// document produces read the same on every run.
func sortedKeys(m map[string]any) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// at is a property path with one segment appended. The root's own properties
// carry no prefix, so a top-level problem reads "pricing" and not ".pricing".
func at(path, segment string) string {
	if path == "" {
		return segment
	}
	return path + "." + segment
}

// index is the path of one element of a repeated value.
func index(path string, i int) string { return path + "[" + strconv.Itoa(i) + "]" }

// decoder accumulates every problem in one pass. A decoder that stopped at the
// first one would make a form show its errors one at a time, which is a form
// nobody finishes.
type decoder struct {
	problems []Problem
}

func (d *decoder) problemf(path, format string, args ...any) {
	d.problems = append(d.problems, Problem{Path: path, Message: fmt.Sprintf(format, args...)})
}

func (d *decoder) unknown(path, kind string) { d.problemf(path, "not declared on %s", kind) }

func (d *decoder) missing(path string) { d.problemf(path, "is required") }

func (d *decoder) mapping(path string, v any) (map[string]any, bool) {
	m, ok := v.(map[string]any)
	if !ok {
		d.problemf(path, "expected an object")
		return nil, false
	}
	return m, true
}

func (d *decoder) list(path string, v any) ([]any, bool) {
	items, ok := v.([]any)
	if !ok {
		d.problemf(path, "expected a list")
		return nil, false
	}
	return items, true
}

// key holds one key of a keyed map to its declared contract. The KEYS are data,
// so an undeclared one is admitted — that is what a map is for — and the
// contract is the whole check standing between a writer and the stored value.
func (d *decoder) key(path, key, pattern string) bool {
	if key == "" {
		d.problemf(path, "a keyed map's key is never empty")
		return false
	}
	switch pattern {
	case "camel":
		if !reCamel.MatchString(key) {
			d.problemf(at(path, key), "a key must be camelCase")
			return false
		}
	case "kindRef":
		if !reKindRef.MatchString(key) {
			d.problemf(at(path, key), "a key must be a kind reference")
			return false
		}
	}
	return true
}

// text decodes a string-family value, held to the declared value set and
// pattern where the declaration carries either. NOTHING is coerced: a number is
// not a string, because a decoder that accepted one would store a value the
// author never wrote.
func (d *decoder) text(path string, v any, values []string, pattern *regexp.Regexp) (string, bool) {
	s, ok := v.(string)
	if !ok {
		d.problemf(path, "expected a string")
		return "", false
	}
	if len(values) > 0 && !Declared(values, s) {
		d.problemf(path, "expected one of %s", strings.Join(values, ", "))
		return "", false
	}
	if pattern != nil && !pattern.MatchString(s) {
		d.problemf(path, "does not match %s", pattern.String())
		return "", false
	}
	return s, true
}

// instant decodes a datetime VERBATIM, checking only that it is an RFC 3339
// instant. Normalizing it to UTC is the write path's business; doing it here
// would stop Decode and Properties being each other's inverse.
func (d *decoder) instant(path string, v any) (string, bool) {
	s, ok := v.(string)
	if !ok {
		d.problemf(path, "expected an RFC 3339 instant")
		return "", false
	}
	if _, err := time.Parse(time.RFC3339, s); err != nil {
		d.problemf(path, "expected an RFC 3339 instant")
		return "", false
	}
	return s, true
}

// numeric reads a number in every spelling one arrives in. jsonb reads back as
// float64 and YAML decodes as int, so refusing either would refuse values that
// have merely been through storage.
func (d *decoder) numeric(path string, v any) (float64, bool) {
	switch n := v.(type) {
	case int:
		return float64(n), true
	case int32:
		return float64(n), true
	case int64:
		return float64(n), true
	case float32:
		return float64(n), true
	case float64:
		return n, true
	case json.Number:
		f, err := n.Float64()
		if err != nil {
			d.problemf(path, "expected a number")
			return 0, false
		}
		return f, true
	}
	d.problemf(path, "expected a number")
	return 0, false
}

func (d *decoder) integer(path string, v any, b Bounds) (int64, bool) {
	f, ok := d.numeric(path, v)
	if !ok {
		return 0, false
	}
	if f != float64(int64(f)) {
		d.problemf(path, "expected an integer")
		return 0, false
	}
	if !d.inBounds(path, f, b) {
		return 0, false
	}
	return int64(f), true
}

func (d *decoder) number(path string, v any, b Bounds) (float64, bool) {
	f, ok := d.numeric(path, v)
	if !ok || !d.inBounds(path, f, b) {
		return 0, false
	}
	return f, true
}

func (d *decoder) inBounds(path string, f float64, b Bounds) bool {
	if b.Min != nil && f < *b.Min {
		d.problemf(path, "must be >= %v", *b.Min)
		return false
	}
	if b.Max != nil && f > *b.Max {
		d.problemf(path, "must be <= %v", *b.Max)
		return false
	}
	return true
}

func (d *decoder) flag(path string, v any) (bool, bool) {
	b, ok := v.(bool)
	if !ok {
		d.problemf(path, "expected a bool")
		return false, false
	}
	return b, true
}

// secret decodes the REF a secret property stores. Any string is a shape a
// sealed store can hold — the engine mints the ref, so nothing here can know
// its alphabet — and the redaction sentinel is one of them, because a read
// hands it back and a write may hand it straight on.
func (d *decoder) secret(path string, v any) (SecretRef, bool) {
	s, ok := d.text(path, v, nil, nil)
	if !ok {
		return "", false
	}
	return SecretRef(s), true
}

// digest decodes a server-minted comparator: 64 lowercase hex, or the redaction
// sentinel a read handed back.
func (d *decoder) digest(path string, v any) (Digest, bool) {
	s, ok := d.text(path, v, nil, nil)
	if !ok {
		return "", false
	}
	if s != Redacted && !reDigest.MatchString(s) {
		d.problemf(path, "expected a SHA-256 digest (64 lowercase hex)")
		return "", false
	}
	return Digest(s), true
}

func (d *decoder) blob(path string, v any) (BlobDigest, bool) {
	s, ok := d.text(path, v, nil, nil)
	if !ok {
		return "", false
	}
	if !strings.HasPrefix(s, BlobDigestPrefix) || !reDigest.MatchString(strings.TrimPrefix(s, BlobDigestPrefix)) {
		d.problemf(path, "expected a blob digest (%s<64 hex>)", BlobDigestPrefix)
		return "", false
	}
	return BlobDigest(s), true
}

// reference decodes a {kind, id} pair, taking the kind from the declaration's
// to: where a bare id was written and the declaration pins a concrete referent
// — the shorthand a single-target edge has always admitted.
func (d *decoder) reference(path string, v any, to string) (Reference, bool) {
	var r Reference
	switch t := v.(type) {
	case map[string]any:
		r.Kind, _ = t["kind"].(string)
		r.ID, _ = t["id"].(string)
	case string:
		r.ID = t
	default:
		d.problemf(path, "expected a {kind, id} object")
		return Reference{}, false
	}
	if r.ID == "" {
		d.problemf(path, "a reference needs an id")
		return Reference{}, false
	}
	if r.Kind == "" && to != "" && to != "any" {
		r.Kind = to
	}
	if r.Kind == "" {
		d.problemf(path, "a reference to any kind needs an explicit kind")
		return Reference{}, false
	}
	return r, true
}

// dynamic decodes a json property, which is every shape: core does not own it,
// so there is nothing here to check that would not be a guess.
func (d *decoder) dynamic(path string, v any) (Dynamic, bool) { return v, true }
