// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

import (
	"time"
)

// Token is core.substrate.reamde.dev/token as its declaration admits it.
//
// One bearer credential: a label, the SHA-256 of a secret shown once at mint,
// and an optional expiry. A token has full access to its repository —
// sessions are these records, login mints one, and revoking one is an ordinary
// record delete.
type Token struct {
	// Label is what the token is for, chosen at mint.
	Label *string

	// Hash is the SHA-256 of the secret; the secret itself is shown once, at
	// mint.
	Hash *Digest

	// ExpiresAt is when the token stops authenticating; absent = until
	// deleted.
	ExpiresAt *string
}

// TokenKeys is the admitted key set: every property
// core.substrate.reamde.dev/token declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var TokenKeys = []string{"expiresAt", "hash", "label"}

// DecodeToken decodes a properties map into Token, refusing what the
// declaration cannot hold: an undeclared key, a value of the wrong type, an
// enum or state outside its set, a number outside its declared range or beyond
// exact integer precision, a key breaking a keyed map's contract. The value is
// nil unless the problems are empty, so a half-decoded record can never reach
// a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — TokenRequired and Missing are where
// requiredness lives.
func DecodeToken(props map[string]any) (*Token, []Problem) {
	d := &decoder{}
	out, _ := decodeToken(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeToken decodes one Token value at path.
func decodeToken(d *decoder, path string, v any) (Token, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return Token{}, false
	}
	var out Token
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "label":
			p := at(path, "label")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Label = &e
			}
		case "hash":
			p := at(path, "hash")
			if e, ok := d.digest(p, props[key]); ok {
				out.Hash = &e
			}
		case "expiresAt":
			p := at(path, "expiresAt")
			if e, ok := d.instant(p, props[key]); ok {
				out.ExpiresAt = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/token")
		}
	}
	return out, true
}

// Encode is Token as the properties map holds it, and DecodeToken's exact
// inverse: a nil pointer, a nil slice and a nil map each omit their key, so
// absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *Token) Encode() map[string]any {
	out := map[string]any{}
	if v.Label != nil {
		out["label"] = *v.Label
	}
	if v.Hash != nil {
		out["hash"] = string(*v.Hash)
	}
	if v.ExpiresAt != nil {
		out["expiresAt"] = *v.ExpiresAt
	}
	return out
}

// ExpiresAtTime is ExpiresAt parsed. The stored form is the string, so this is
// a reading of it and never a second source of truth; an absent value reads as
// the zero time with no error, because absence is not a malformed instant.
func (v *Token) ExpiresAtTime() (time.Time, error) {
	if v.ExpiresAt == nil {
		return time.Time{}, nil
	}
	return time.Parse(time.RFC3339, *v.ExpiresAt)
}
