// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// Trait is core.substrate.reamde.dev/trait as its declaration admits it.
//
// One declared trait: reusable typed properties with shared semantics that a
// kind binds — `temporal`, `accountconfig`, `oauth2`. Traits resolve across
// authorities, and host behavior keys on the trait a kind binds rather than on
// what the kind is called.
type Trait struct {
	// Version is this declaration's version.
	Version *string

	// Name is the trait's local name.
	Name *string

	// Authority is the authority that declares it.
	Authority *string

	// Definition is the parsed manifest data.
	Definition Dynamic
}

// TraitKeys is the admitted key set: every property
// core.substrate.reamde.dev/trait declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var TraitKeys = []string{"authority", "definition", "name", "version"}

// DecodeTrait decodes a properties map into Trait, refusing what the
// declaration cannot hold: an undeclared key, a value of the wrong type, an
// enum or state outside its set, a number outside its declared range or beyond
// exact integer precision, a key breaking a keyed map's contract. The value is
// nil unless the problems are empty, so a half-decoded record can never reach
// a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — TraitRequired and Missing are where
// requiredness lives.
func DecodeTrait(props map[string]any) (*Trait, []Problem) {
	d := &decoder{}
	out, _ := decodeTrait(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeTrait decodes one Trait value at path.
func decodeTrait(d *decoder, path string, v any) (Trait, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return Trait{}, false
	}
	var out Trait
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "version":
			p := at(path, "version")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Version = &e
			}
		case "name":
			p := at(path, "name")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Name = &e
			}
		case "authority":
			p := at(path, "authority")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Authority = &e
			}
		case "definition":
			p := at(path, "definition")
			if e, ok := d.dynamic(p, props[key]); ok {
				out.Definition = e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/trait")
		}
	}
	return out, true
}

// Properties is Trait as the properties map holds it, and DecodeTrait's exact
// inverse: a nil pointer, a nil slice and a nil map each omit their key, so
// absence survives the round trip.
func (v *Trait) Properties() map[string]any {
	out := map[string]any{}
	if v.Version != nil {
		out["version"] = *v.Version
	}
	if v.Name != nil {
		out["name"] = *v.Name
	}
	if v.Authority != nil {
		out["authority"] = *v.Authority
	}
	if v.Definition != nil {
		out["definition"] = v.Definition
	}
	return out
}
