// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

import (
	"time"
)

// Trigger is core.substrate.reamde.dev/trigger as its declaration admits it.
//
// One delivery binding: a source — matched records, a schedule, or a webhook
// — bound to the one function or agent it invokes. The trigger owns its
// cursor, so enabling, replay, parking and manual runs are all verbs on this
// row.
type Trigger struct {
	// Enabled is whether the dispatcher delivers for this trigger; false stops
	// execution without losing the cursor.
	Enabled *bool

	// Source is the one source this trigger delivers from.
	Source *TriggerSource

	// Callable is the function or agent a matched delivery invokes, as its
	// `<kind>/<id>` path. Points at any.
	Callable *ReferencePath
}

// TriggerKeys is the admitted key set: every property
// core.substrate.reamde.dev/trigger declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var TriggerKeys = []string{"callable", "enabled", "source"}

// DecodeTrigger decodes a properties map into Trigger, refusing what the
// declaration cannot hold: an undeclared key, a value of the wrong type, an
// enum or state outside its set, a number outside its declared range or beyond
// exact integer precision, a key breaking a keyed map's contract. The value is
// nil unless the problems are empty, so a half-decoded record can never reach
// a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — TriggerRequired and Missing are where
// requiredness lives.
func DecodeTrigger(props map[string]any) (*Trigger, []Problem) {
	d := &decoder{}
	out, _ := decodeTrigger(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeTrigger decodes one Trigger value at path.
func decodeTrigger(d *decoder, path string, v any) (Trigger, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return Trigger{}, false
	}
	var out Trigger
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "enabled":
			p := at(path, "enabled")
			if e, ok := d.flag(p, props[key]); ok {
				out.Enabled = &e
			}
		case "source":
			p := at(path, "source")
			if e, ok := decodeTriggerSource(d, p, props[key]); ok {
				out.Source = &e
			}
		case "callable":
			p := at(path, "callable")
			if e, ok := d.reference(p, props[key], "any"); ok {
				out.Callable = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/trigger")
		}
	}
	return out, true
}

// Encode is Trigger as the properties map holds it, and DecodeTrigger's exact
// inverse: a nil pointer, a nil slice and a nil map each omit their key, so
// absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *Trigger) Encode() map[string]any {
	out := map[string]any{}
	if v.Enabled != nil {
		out["enabled"] = *v.Enabled
	}
	if v.Source != nil {
		out["source"] = v.Source.Encode()
	}
	if v.Callable != nil {
		out["callable"] = string(*v.Callable)
	}
	return out
}

// TriggerSource is one value of the `source` object declared on
// core.substrate.reamde.dev/trigger.
//
// the one source this trigger delivers from
type TriggerSource struct {
	// Kind is which arm below carries the source.
	Kind *TriggerSourceKind

	// Record is matched records — the changelog is the source.
	Record *TriggerSourceRecord

	// Schedule is a recurrence — the clock is the source.
	Schedule *TriggerSourceSchedule

	// Webhook is an authenticated wake endpoint.
	Webhook *TriggerSourceWebhook
}

// TriggerSourceKind is a declared enum: the admissible set, in declaration
// order.
//
// which arm below carries the source
type TriggerSourceKind string

const (
	TriggerSourceKindRecord   TriggerSourceKind = "record"
	TriggerSourceKindSchedule TriggerSourceKind = "schedule"
	TriggerSourceKindWebhook  TriggerSourceKind = "webhook"
)

// TriggerSourceKindValues are the declared values in declaration order, which
// is render order.
var TriggerSourceKindValues = []string{"record", "schedule", "webhook"}

// Valid reports whether v is one of the declared values.
func (v TriggerSourceKind) Valid() bool { return Declared(TriggerSourceKindValues, string(v)) }

// decodeTriggerSourceKind decodes a declared TriggerSourceKind value.
func decodeTriggerSourceKind(d *decoder, path string, v any) (TriggerSourceKind, bool) {
	s, ok := d.text(path, v, TriggerSourceKindValues, nil)
	if !ok {
		return "", false
	}
	return TriggerSourceKind(s), true
}

// decodeTriggerSource decodes one TriggerSource value at path.
func decodeTriggerSource(d *decoder, path string, v any) (TriggerSource, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return TriggerSource{}, false
	}
	var out TriggerSource
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "kind":
			p := at(path, "kind")
			if e, ok := decodeTriggerSourceKind(d, p, props[key]); ok {
				out.Kind = &e
			}
		case "record":
			p := at(path, "record")
			if e, ok := decodeTriggerSourceRecord(d, p, props[key]); ok {
				out.Record = &e
			}
		case "schedule":
			p := at(path, "schedule")
			if e, ok := decodeTriggerSourceSchedule(d, p, props[key]); ok {
				out.Schedule = &e
			}
		case "webhook":
			p := at(path, "webhook")
			if e, ok := decodeTriggerSourceWebhook(d, p, props[key]); ok {
				out.Webhook = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/trigger")
		}
	}
	return out, true
}

// Encode is TriggerSource as the properties map holds it, and
// decodeTriggerSource's exact inverse: a nil pointer, a nil slice and a nil
// map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *TriggerSource) Encode() map[string]any {
	out := map[string]any{}
	if v.Kind != nil {
		out["kind"] = string(*v.Kind)
	}
	if v.Record != nil {
		out["record"] = v.Record.Encode()
	}
	if v.Schedule != nil {
		out["schedule"] = v.Schedule.Encode()
	}
	if v.Webhook != nil {
		out["webhook"] = v.Webhook.Encode()
	}
	return out
}

// TriggerSourceRecord is one value of the `source.record` object declared on
// core.substrate.reamde.dev/trigger.
//
// matched records — the changelog is the source
type TriggerSourceRecord struct {
	// Kinds is the kinds watched, each a reference, `<authority>/*` or `*`.
	Kinds []string

	// Ops is which changes deliver; absent is all three.
	Ops []TriggerSourceRecordOps

	// When is the CEL guard over change/record/repository.
	When *string

	// Coalesce is collapse a burst on one record into one delivery.
	Coalesce *bool
}

// TriggerSourceRecordOps is a declared enum: the admissible set, in
// declaration order.
//
// which changes deliver; absent is all three
type TriggerSourceRecordOps string

const (
	TriggerSourceRecordOpsCreate TriggerSourceRecordOps = "create"
	TriggerSourceRecordOpsUpdate TriggerSourceRecordOps = "update"
	TriggerSourceRecordOpsDelete TriggerSourceRecordOps = "delete"
)

// TriggerSourceRecordOpsValues are the declared values in declaration order,
// which is render order.
var TriggerSourceRecordOpsValues = []string{"create", "update", "delete"}

// Valid reports whether v is one of the declared values.
func (v TriggerSourceRecordOps) Valid() bool {
	return Declared(TriggerSourceRecordOpsValues, string(v))
}

// decodeTriggerSourceRecordOps decodes a declared TriggerSourceRecordOps value.
func decodeTriggerSourceRecordOps(d *decoder, path string, v any) (TriggerSourceRecordOps, bool) {
	s, ok := d.text(path, v, TriggerSourceRecordOpsValues, nil)
	if !ok {
		return "", false
	}
	return TriggerSourceRecordOps(s), true
}

// decodeTriggerSourceRecord decodes one TriggerSourceRecord value at path.
func decodeTriggerSourceRecord(d *decoder, path string, v any) (TriggerSourceRecord, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return TriggerSourceRecord{}, false
	}
	var out TriggerSourceRecord
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "kinds":
			p := at(path, "kinds")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]string, 0, len(items))
				for i, item := range items {
					if e, ok := d.text(index(p, i), item, nil, nil); ok {
						list = append(list, e)
					}
				}
				out.Kinds = list
			}
		case "ops":
			p := at(path, "ops")
			if items, listed := d.list(p, props[key]); listed {
				list := make([]TriggerSourceRecordOps, 0, len(items))
				for i, item := range items {
					if e, ok := decodeTriggerSourceRecordOps(d, index(p, i), item); ok {
						list = append(list, e)
					}
				}
				out.Ops = list
			}
		case "when":
			p := at(path, "when")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.When = &e
			}
		case "coalesce":
			p := at(path, "coalesce")
			if e, ok := d.flag(p, props[key]); ok {
				out.Coalesce = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/trigger")
		}
	}
	return out, true
}

// Encode is TriggerSourceRecord as the properties map holds it, and
// decodeTriggerSourceRecord's exact inverse: a nil pointer, a nil slice and a
// nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *TriggerSourceRecord) Encode() map[string]any {
	out := map[string]any{}
	if v.Kinds != nil {
		items := make([]any, 0, len(v.Kinds))
		for i := range v.Kinds {
			items = append(items, v.Kinds[i])
		}
		out["kinds"] = items
	}
	if v.Ops != nil {
		items := make([]any, 0, len(v.Ops))
		for i := range v.Ops {
			items = append(items, string(v.Ops[i]))
		}
		out["ops"] = items
	}
	if v.When != nil {
		out["when"] = *v.When
	}
	if v.Coalesce != nil {
		out["coalesce"] = *v.Coalesce
	}
	return out
}

// TriggerSourceSchedule is one value of the `source.schedule` object declared
// on core.substrate.reamde.dev/trigger.
//
// a recurrence — the clock is the source
type TriggerSourceSchedule struct {
	// Recurrence is the RFC 5545 RRULE the fires follow.
	Recurrence *string

	// Timezone is the IANA zone the recurrence is read in.
	Timezone *string

	// StartsAt is the instant the recurrence counts from.
	StartsAt *string
}

// decodeTriggerSourceSchedule decodes one TriggerSourceSchedule value at path.
func decodeTriggerSourceSchedule(d *decoder, path string, v any) (TriggerSourceSchedule, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return TriggerSourceSchedule{}, false
	}
	var out TriggerSourceSchedule
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "recurrence":
			p := at(path, "recurrence")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Recurrence = &e
			}
		case "timezone":
			p := at(path, "timezone")
			if e, ok := d.text(p, props[key], nil, nil); ok {
				out.Timezone = &e
			}
		case "startsAt":
			p := at(path, "startsAt")
			if e, ok := d.instant(p, props[key]); ok {
				out.StartsAt = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/trigger")
		}
	}
	return out, true
}

// Encode is TriggerSourceSchedule as the properties map holds it, and
// decodeTriggerSourceSchedule's exact inverse: a nil pointer, a nil slice and
// a nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *TriggerSourceSchedule) Encode() map[string]any {
	out := map[string]any{}
	if v.Recurrence != nil {
		out["recurrence"] = *v.Recurrence
	}
	if v.Timezone != nil {
		out["timezone"] = *v.Timezone
	}
	if v.StartsAt != nil {
		out["startsAt"] = *v.StartsAt
	}
	return out
}

// StartsAtTime is StartsAt parsed. The stored form is the string, so this is a
// reading of it and never a second source of truth; an absent value reads as
// the zero time with no error, because absence is not a malformed instant.
func (v *TriggerSourceSchedule) StartsAtTime() (time.Time, error) {
	if v.StartsAt == nil {
		return time.Time{}, nil
	}
	return time.Parse(time.RFC3339, *v.StartsAt)
}

// TriggerSourceWebhook is one value of the `source.webhook` object declared on
// core.substrate.reamde.dev/trigger.
//
// an authenticated wake endpoint
type TriggerSourceWebhook struct {
}

// decodeTriggerSourceWebhook decodes one TriggerSourceWebhook value at path.
func decodeTriggerSourceWebhook(d *decoder, path string, v any) (TriggerSourceWebhook, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return TriggerSourceWebhook{}, false
	}
	var out TriggerSourceWebhook
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/trigger")
		}
	}
	return out, true
}

// Encode is TriggerSourceWebhook as the properties map holds it, and
// decodeTriggerSourceWebhook's exact inverse: a nil pointer, a nil slice and a
// nil map each omit their key, so absence survives the round trip.
//
// It is NOT called Properties: a declaration may declare a property of that
// name (core's `kind` does), and a field and a method cannot share one.
// Decode/Encode is the pair the rest of the generator already names.
func (v *TriggerSourceWebhook) Encode() map[string]any {
	out := map[string]any{}
	return out
}
