// Code generated by cmd/kindsgen from kinds/core.substrate.reamde.dev. DO NOT EDIT.
// `mise run kinds:gen` rewrites this file; an edit here is lost.

package corekinds

// Trigger is core.substrate.reamde.dev/trigger as its declaration admits it.
//
// One delivery binding: a source — matched records, a schedule, or a webhook
// — bound to the one function or agent it invokes. The trigger owns its
// cursor, so enabling, replay, parking and manual runs are all verbs on this
// row.
type Trigger struct {
	// Enabled is whether the dispatcher delivers for this trigger; false stops
	// execution without losing the cursor.
	Enabled *bool

	// Source is the one source arm: record {kinds, ops, when, coalesce},
	// schedule {recurrence, timezone, startsAt}, or webhook {}.
	Source Dynamic

	// Callable is the function or agent a matched delivery invokes ({kind,
	// id}). Points at any.
	Callable *Reference
}

// TriggerKeys is the admitted key set: every property
// core.substrate.reamde.dev/trigger declares, sorted. A key outside it is
// refused by Decode, which is what replaces a hand-kept list of admitted keys
// in Go.
var TriggerKeys = []string{"callable", "enabled", "source"}

// DecodeTrigger decodes a properties map into Trigger, refusing what the
// declaration cannot hold: an undeclared key, a value of the wrong type, an
// enum or state outside its set, a number outside its declared range or beyond
// exact integer precision, a key breaking a keyed map's contract. The value is
// nil unless the problems are empty, so a half-decoded record can never reach
// a caller.
//
// It reads a STORED shape and is not the write-admission gate: see the
// boundary in support.go. An ABSENT required property is admitted, because the
// write path admits one too — TriggerRequired and Missing are where
// requiredness lives.
func DecodeTrigger(props map[string]any) (*Trigger, []Problem) {
	d := &decoder{}
	out, _ := decodeTrigger(d, "", props)
	if len(d.problems) > 0 {
		return nil, d.problems
	}
	return &out, nil
}

// decodeTrigger decodes one Trigger value at path.
func decodeTrigger(d *decoder, path string, v any) (Trigger, bool) {
	props, mapped := d.mapping(path, v)
	if !mapped {
		return Trigger{}, false
	}
	var out Trigger
	for _, key := range sortedKeys(props) {
		// A null is this dialect's delete marker, never a value: it decodes as
		// absence, and Properties never writes one.
		if props[key] == nil {
			continue
		}
		switch key {
		case "enabled":
			p := at(path, "enabled")
			if e, ok := d.flag(p, props[key]); ok {
				out.Enabled = &e
			}
		case "source":
			p := at(path, "source")
			if e, ok := d.dynamic(p, props[key]); ok {
				out.Source = e
			}
		case "callable":
			p := at(path, "callable")
			if e, ok := d.reference(p, props[key], "any"); ok {
				out.Callable = &e
			}
		default:
			d.unknown(at(path, key), "core.substrate.reamde.dev/trigger")
		}
	}
	return out, true
}

// Properties is Trigger as the properties map holds it, and DecodeTrigger's
// exact inverse: a nil pointer, a nil slice and a nil map each omit their key,
// so absence survives the round trip.
func (v *Trigger) Properties() map[string]any {
	out := map[string]any{}
	if v.Enabled != nil {
		out["enabled"] = *v.Enabled
	}
	if v.Source != nil {
		out["source"] = v.Source
	}
	if v.Callable != nil {
		out["callable"] = v.Callable.Properties()
	}
	return out
}
